### ISSUE TITLE
Mesh object not visible on plot.

### ISSUE THREAD

**Issue by Gulaabihaathee** [K3D-tools/K3D-jupyter#104]
points = k3d.points(tri)
mesh = k3d.mesh(tri, [0,1,2])
plot += points + mesh

After creating triangle only wireframe of mesh can be seen. The mesh is not visible.

**Comment by artur-trzesiok** [comment]
Thanks for that spot. It's our regression. It's already fixed. Please update k3d to version 2.4.16
