### ISSUE TITLE
Negative values of attributes.

### ISSUE THREAD

**Issue by Gulaabihaathee** [K3D-tools/K3D-jupyter#108]
It is possible to set line.width to negative value and it results with creepy effect - some twisted cylinder?

There is also a possibility to set points.point_size to negative value and then the displayed plot is empty.

**Comment by tgandor** [comment]
I've added validation against negative values on traitlet level.
Unfortunately, the standard validation for Float in traitlets is based on [min, max], inclusive.
So the min value is now float32 eps. Most users should be fine.

**Comment by Gulaabihaathee** [comment]
Setting any negative value as line.width attribute results with thin line, 
but 
assigning positive value to this attribute results with plane on the displayed image.

**Comment by Gulaabihaathee** [comment]
At this moment, setting a value less than float32 eps results with TraitError but
assigning greater value results with _'Plane Instead a Line Bug'_.
