### ISSUE TITLE
Transform do not change spatial attribute value.

### ISSUE THREAD

**Issue by Gulaabihaathee** [K3D-tools/K3D-jupyter#109]
Transforms: rotation, translation applied to object do not change values of attributes idicating spatial position. It works only on the displayed view.

Shown in:
https://github.com/K3D-tools/experiments/blob/master/Processed_examples/Transforms_issues.ipynb

**Comment by tgandor** [comment]
The underlying data is not supposed to be modified by modifying transform.
It only affects the presentation.
