### ISSUE TITLE
Latex labels cannot be removed interactively

### ISSUE THREAD

**Issue by marcinofulus** [K3D-tools/K3D-jupyter#11]

**Comment by artur-trzesiok** [comment]
In the version 2.0.4 this issue should be fixed. Please confirm.

**Comment by marcinofulus** [comment]
plot.labels = None | []  should work,

**Comment by artur-trzesiok** [comment]
Please look at https://github.com/K3D-tools/K3D-jupyter/blob/master/examples/vector.ipynb . I think this is good enough and we can close this bug.
