### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by marijanbeg** [K3D-tools/K3D-jupyter#119]
Hi,

we think you did an amazing job with this package. Now, we started implementing visualisation for our JOOMMF package (https://GitHub.com/joommf/joommf) using your tool. At this point we have two questions for you:

1. Do you plan creating a conda package for your module?
2. We would like to visualise a finite difference scalar field. By looking into your examples we assume the best option is to use `volume` (Are we right?). However, we cannot find a working example for that function. Could you please point us to an example of usage for that function?

Many thanks

**Comment by renefritze** [comment]
I am willing to contribute by getting a conda-forge recipe going.

**Comment by tgandor** [comment]
Hello Rene,

yes, please - help us publish this on conda-forge. I don't know the process of putting packages there - what else needs to be done except the recipe?

Anyway, such a contribution would be very appreciated!

**Comment by renefritze** [comment]
The process is pretty automated. You make a PR with the new recipe, tweak until it builds. Then you request a review, it gets merged and you end up with a repo k3d-feedstock where maintainers have access and can updated the recipe for new releases on their own. 

I've started the PR here: https://github.com/conda-forge/staged-recipes/pull/8050
It would be good if someone from the K3D project would become maintainer as well, since I do not want to promise to maintain it forever. Can I list you @tgandor ?

**Comment by renefritze** [comment]
I ran into a problem with installing K3D from source in that PR. #139 fixes the problem, but this needs to land in a release before the conda package can continue.

**Comment by tgandor** [comment]
Ok, the manifest fix is merged.
Yes, I'd like to be added to k3d's feedstock, but even more importantly please add the project owners: https://github.com/marcinofulus and https://github.com/artur-trzesiok

**Comment by tgandor** [comment]
Great, Vielen Dank!

If I understand correctly, we need now to merge it and update the PyPI package (so that the build passes - we need a new source tarball, which includes `setupbase.py`. But for this we need @artur-trzesiok  to update it. I can start a merge request to `master` before that.

**Comment by renefritze** [comment]
Right. After the a new release with a source tarball on PyPi is out, the feedstock PR should go through. Barring issues with executing tests ofc.

**Comment by renefritze** [comment]
The conda package is now live, and already updating to 2.6.3 due to some automagic on conda-forge's end. I think this issue can be closed.
