### ISSUE TITLE
Option to disable grid

### ISSUE THREAD

**Issue by jpomoell** [K3D-tools/K3D-jupyter#128]
Hi,

For many use cases, the background grid can be a bit distracting. Would it be possible to add an option to disable drawing it completely, e.g. via an extra argument to k3d.plot? This way, the user could supply a custom grid if needed as simply another Drawable that is added to the plot. 

P.S. Fantastic project!

**Comment by artur-trzesiok** [comment]
I totally agree. It's quite simply feature. I will add it in next release. @marcinofulus do you agree?

**Comment by artur-trzesiok** [comment]
Please check https://pypi.org/project/K3D/2.4.21/
