### ISSUE TITLE
Scene not rotating if cursor below the menu

### ISSUE THREAD

**Issue by jpomoell** [K3D-tools/K3D-jupyter#129]
If the cursor is anywhere below the controls menu, rotating via click and drag does not work. The issue seems to be that that the dg div sets as its height the entire window rather than just the height of the menu.

**Comment by artur-trzesiok** [comment]
Nice spot! Thanks for that. In new release this sholud be fixed

**Comment by artur-trzesiok** [comment]
Please check https://pypi.org/project/K3D/2.4.21/

**Comment by jpomoell** [comment]
Works great, thanks!
