### ISSUE TITLE
Doubled labels in Jupyter Lab

### ISSUE THREAD

**Issue by marijanbeg** [K3D-tools/K3D-jupyter#131]
Hi, we have noticed that the labels are doubled when `k3d` is used in JupyterLab (photo attached). This problem does not exist in standard Jupyter Notebook.
![screenshot from 2019-02-01 16-36-49](https://user-images.githubusercontent.com/12461206/52132529-a3897300-263f-11e9-8c20-22b91dcd9130.png)

**Comment by artur-trzesiok** [comment]
That's shame. Support for jupyterlab is still unofficial. I will try to solve it.

**Comment by oroszl** [comment]
Can confirm that this issue is still present in a fresh install from cond-forge

**Comment by luca-penasa** [comment]
having the same issue here on arch, also with k3d from git...

**Comment by artur-trzesiok** [comment]
should be fixed. The problem occurred because of missing katex css
