### ISSUE TITLE
Hide controls and lock camera?

### ISSUE THREAD

**Issue by renefritze** [K3D-tools/K3D-jupyter#136]
I'm using your excellent library to visualize 2D VTK data and I would love to be able to lock the camera. Maybe lock rotation and zoom independently. 
It would also be nice if I can start a plot with the controls panel hidden entirely or at least show the "minimized" state only.

Is this currently possible?

**Comment by renefritze** [comment]
I just saw that the develop branch as the visibility attribute for the plot controls. Great! 

Any idea about the camera? I'd also be fine to just block mouse events on the widget side, but I could not find anything towards that yet.

**Comment by artur-trzesiok** [comment]
This is something that can be easily implemented. That "lock" combine with api for setting camera give posibiliity to use k3d with any type of interaction device. @marcinofulus  what do you think?

**Comment by artur-trzesiok** [comment]
Example: https://github.com/K3D-tools/K3D-jupyter/blob/devel/examples/marching_cubes.ipynb

**Comment by renefritze** [comment]
Working great. Thank you very much for implementing this!
