### ISSUE TITLE
It should install in SageMath 7.6

### ISSUE THREAD

**Issue by marcinofulus** [K3D-tools/K3D-jupyter#14]
When installing in SageMath 7.6, one gets:

Collecting numpy>=1.11.0 (from k3d)
  Downloading numpy-1.12.1.zip (4.8MB)
    100% |################################| 4.8MB 225kB/s 
Collecting ipython>=4.0.0 (from ipywidgets>=6.0.0->k3d)
  Downloading ipython-6.0.0.tar.gz (5.1MB)
    100% |################################| 5.1MB 200kB/s 
    Complete output from command python setup.py egg_info:
    
    IPython 6.0+ does not support Python 2.6, 2.7, 3.0, 3.1, or 3.2.
    When using Python 2.7, please install IPython 5.x LTS Long Term Support version.
    Beginning with IPython 6.0, Python 3.3 and above is required.
    
    See IPython `README.rst` file for more information:
    
        https://github.com/ipython/ipython/blob/master/README.rst
    
    Python sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0) detected.
    Your pip version is out of date, please install pip >= 9.0.1. pip 8.1.2 detected.
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/8f/j1h8qzsj6fzc6kdws2r4qw6c0000gn/T/pip-build-OfJtMo/ipython/
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(sage-sh)

**Comment by artur-trzesiok** [comment]
we hade in setup.py:
    
> 'install_requires': [
>         'ipywidgets>=6.0.0',
>         'numpy>=1.11.0'
>     ],

Older version probably will not cooperate with 'jupyter-js-widgets' that we use.

**Comment by marcinofulus** [comment]
pip install -U k3d numpy==1.11.1 pyzmq==16.0.0 works,

**Comment by aishenri** [comment]
I still have this error ?
I tried sage python2 python3 installation, there is no error while installing it your way 
pip install -U k3d numpy==1.11.1 pyzmq==16.0.0 
Could not create model:
Model name 	K3DModel
Model module 	k3d
Model module version 	^2.0.0
Script error for "k3d" http://requirejs.org/docs/errors.html#scripterror

**Comment by aishenri** [comment]
Today I got it working in python2 and python3 but I don't know really why it did n't work before ?

the only differently thing I did was to install it system wide I don't know if it will work with sagemath
I use : sudo -H pip2 and 3 install -U k3d numpy==1.11.1 pyzmq==16.0.0

Thank you very much for your help
