### ISSUE TITLE
html snapshot doesn't render on chrome

### ISSUE THREAD

**Issue by fontclos** [K3D-tools/K3D-jupyter#142]
Saving a snapshot as html and then opening it on chrome/firefox seems to fail due to k3d.js not being found

![sc2](https://user-images.githubusercontent.com/10452257/55648398-82c8cf80-57e0-11e9-97ac-3b985c20ddf4.png)
![sc1](https://user-images.githubusercontent.com/10452257/55648399-83616600-57e0-11e9-9f76-4aba812338f6.png)

This happens only from jupyterlab, from a notebook it works fine.

**Comment by artur-trzesiok** [comment]
Thanks for that spot. This problem is related to be incompatibile with bandling system in lab. I add this issue to my "todo"

**Comment by fontclos** [comment]
sure, will check later from home
