### ISSUE TITLE
Expose detail parameter of IcosahedronBufferGeometry in PointsMesh

### ISSUE THREAD

**Issue by jpomoell** [K3D-tools/K3D-jupyter#147]
Sometimes the level of detail of `Points` rendered using the `mesh` shader is not sufficient. It would be great if the `detail` parameter of `THREE.IcosahedronBufferGeometry` ([currently set to 2](https://github.com/K3D-tools/K3D-jupyter/blob/d804c9fcede84672143d796ad5cbbcfd96e95264/js/src/providers/threejs/objects/PointsMesh.js#L35)) could be exposed.

**Comment by artur-trzesiok** [comment]
@jpomoell please check a leatest version (2.6.3) :).

**Comment by jpomoell** [comment]
Works great, thanks a lot!
