### ISSUE TITLE
Add ability to reset camera programmatically

### ISSUE THREAD

**Issue by ksuszka** [K3D-tools/K3D-jupyter#151]
In K3D 2.6.3, when camera_auto_fit is set to False, camera is not initialised (which is ok, I guess). However, it would be nice to have an ability to use built-in camera auto fit calculation on demand, so code like this is possible:
```
plot = k3d.plot(camera_auto_fit=False)
plot += k3d.texture(...)
plot += k3d.voxels(...)
plot.reset_camera()       # fits camera once, without changing camera_auto_fit mode
```

**Comment by artur-trzesiok** [comment]
Please download @2.6.6. API is exactly that you mention.
