### ISSUE TITLE
two sided surfaces

### ISSUE THREAD

**Issue by oroszl** [K3D-tools/K3D-jupyter#152]
In some other projects, like in [ipyvolume](https://github.com/maartenbreddels/ipyvolume/issues/60) and [pythreejs](https://github.com/jupyter-widgets/pythreejs) it is possible to tune the two sides of a surface differently, that is, for example, make them have a different colour or make one visible while hiding the other (as a workaround for some of the transparent surface problems).
Would it be possible to bubble out the appropriate threejs options so that they are also available in k3d?

**Comment by artur-trzesiok** [comment]
@oroszl for what exactly kind of object you want that functionality? k3d.mesh?

**Comment by oroszl** [comment]
I was basically thinking about orientable surfaces, surfaces which have a definite inside and outside, like a sphere. A counterexample would be a Moebius strip or a Klein bottle. 
Here is a more complicated example of an oriented surface:
![](https://aws1.discourse-cdn.com/standard17/uploads/plot/original/1X/bc964846a5738dbeffb9899f3abadac1d9b39e52.jpg)
whose one side is bluish and the other side is reddish.
And, yes I think k3d.mesh would be the ideal place for this.

**Comment by artur-trzesiok** [comment]
is already added - https://github.com/K3D-tools/K3D-jupyter/commit/0323540ed4a69eb05abd22d7536a11e8d76752f6

please look forward version 2.8.0

**Comment by oroszl** [comment]
great! thanks!
I will try it and close the issue if it works!

**Comment by artur-trzesiok** [comment]
@oroszl did you find time to check if it works or not? :)

**Comment by oroszl** [comment]
@artur-trzesiok Sorry for not answering! it works! (installing from the dev branch)
Thanks again! I guess I can close the issue!
