### ISSUE TITLE
selective clipping planes

### ISSUE THREAD

**Issue by oroszl** [K3D-tools/K3D-jupyter#153]
Is there a way to introduce clipping planes that only clip a subset of objects in the scene?

**Comment by marcinofulus** [comment]
currently we have only global clipping planes, introducing it per object would require some complication in e.g. menu and API.  What is your use case for this? Perhapes It would be easier to cut the data on python side?

**Comment by oroszl** [comment]
In the end I ended up doing precisely that (cutting data on the python side). Although it would be handy to have a cutter in K3D, ultimately I guess K3D's main goal is not to be a data manipulating tool. I think we can close the Issue.
