### ISSUE TITLE
K3D plot.display() hangs vscode Python Interactive session

### ISSUE THREAD

**Issue by RossBencina** [K3D-tools/K3D-jupyter#157]
Running cells that output K3D plots inside vscode hangs the vscode Python Interactive pane (VS Code version: 1.34.0. Windows 10).

I suspect that this is a vscode issue, so I have created an issue there:
https://github.com/microsoft/vscode-python/issues/5893

I wanted to raise the issue here in case there is some known issue with K3D-jupyter. If you have any ideas, please comment. It would be awesome to be able to render and interact with 3D plots from inside vscode.

**Comment by marcinofulus** [comment]
Do you have other webGL based ipywidgets working in this vscode? Like ipyvolume, pythreejs?

**Comment by RossBencina** [comment]
@marcinofulus I had not tried previously, but now I have installed pythreejs and tried importing this example into vscode: https://github.com/jupyter-widgets/pythreejs/blob/master/examples/test.ipynb

In this case, no WebGL graphics are displayed. I get output like:

```
[23] sphere

Preview(child=SphereGeometry(radius=12.0), shadowMap=WebGLShadowMap())
```

But on the other hand, vscode Python Interactive session does not hang.

**Comment by RossBencina** [comment]
Over on the other ticket @rchiodo wrote: "This is an ipywidgets bug. There's a comm error trying to communicate with the K3D ipywidget."

Is K3D known to work correctly with ipywidgets in other applications?

**Comment by rchiodo** [comment]
This is our bug in Python Interactive. We don't support any ipywidgets at the moment.

**Comment by RossBencina** [comment]
Sorry for the noise, I'm closing this issue.
