### ISSUE TITLE
Multiple colorbars and color bar labeling

### ISSUE THREAD

**Issue by GermanSaltar** [K3D-tools/K3D-jupyter#161]
I am rendering three different volumes in one plot each having different color maps but I'm able to display only one colormap. Is there a way to display multiple colormaps? Additionally, is there a way to label the colormaps?

**Comment by artur-trzesiok** [comment]
Color map is a quite new feature in K3D and it's still slightly immature. After internal discussion with @marcinofulus  we resign for a while from multi-colorbar feature. One of the advantages of K3D is a KISS rule - we keep things as simple as its can be. Multicolorbar will require a more complicated API to select position of colorbar etc. This is something that We definetly can adress that topic. 

Let's consider the implementation.

## API

Right now:
plot object have property "colorbar_object_id" that can be set

Multi-colormap mode:
plot object will have properties "colorbars" with list of dicts. Every dicts will lookslike:
{
"position_x": range from 0 to 1. Plot space.
"position_y": range from 0 to 1. Plot space.
"object_id": reference to object
}

## Problems

Right now we have quite usefull feature on GUI side:
![image](https://user-images.githubusercontent.com/5256837/59337353-b6eccf00-8d00-11e9-830d-8e208579ba5e.png)

When we will have multi-colorbars that feature have to be redesigned. The problem that I expect will be: how to automatically set "position_x" and "position_y" of a new colorbar. 

@Einstein11 what do you exactly mean by "label the colormaps"?

**Comment by Einstein11** [comment]
I apologize, it should've been "label the colorbars". The figure below was generated using ParaView. It contains two colorbars, each with their respective label/title. 

![VR05_Stream_2D_V_T](https://user-images.githubusercontent.com/38961789/59355809-af73f880-8cf5-11e9-834f-cbe3339a88aa.png)

Currently, I'm generating plots containing several volumes, every volume having a different colormap. For this reason, the multicolor bar feature and individual colorbar labeling would be very useful. 

My knowledge in Software Architecture is rather limited, but here is my suggestion. If the first colorbar's thickness is known, _a_, the position of the new colorbar could be _a + b_. Where _b_ is a tolerance in either direction, _x_ or _y_, that could be modified. I think the GUI feature is also useful as is.

**Comment by artur-trzesiok** [comment]
Sorry for late replay but I'm waiting for a community response. I don;t think sa that k3d will plan adding multipile color labels. We want to keep it simple.
