### ISSUE TITLE
Incorrect aspect ratio

### ISSUE THREAD

**Issue by Einstein11** [K3D-tools/K3D-jupyter#162]
I have specified the axis boundaries as follows:

_xmin, xmax = 0, 2
ymin, ymax = 0, 0.78125
zmin, zmax = 0, 1_

I am still getting a grid that is larger than my data (see image below). Is there a way to fix this?

![K3D-1559842672260](https://user-images.githubusercontent.com/38961789/59055643-52df8c00-8864-11e9-9ef0-2a192a85c500.png)

**Comment by artur-trzesiok** [comment]
This is done that way on purpose. Grid have auto-align alghoritim to nearest "major-thick" + ensurance that at least 4 major-thick segment will be on screen (for estethic reason). @marcinofulus Do you think that this is ok?

**Comment by Einstein11** [comment]
It is a good feature. However, it might be misleading, in my case, to put a figure like that in a journal article. Readers can interpret it as if a larger domain was used for the numerical modeling. It would be nice if the option could be turned off for situations like this.
