### ISSUE TITLE
Read the Docs build is failing

### ISSUE THREAD

**Issue by RossBencina** [K3D-tools/K3D-jupyter#164]
Currently it is not possible to view K3D-Jupyter docs on Read the Docs website. There is an error with rendering.

See: https://readthedocs.org/projects/k3d-jupyter/builds/8062905/

```
Extension error:
Could not import extension nbsphinx (exception: No module named nbsphinx)
```

This appears to be the same problem that someone else was having: https://github.com/spatialaudio/nbsphinx/issues/184

The fix is to add a requirements.txt file to your repository that specifies nbsphinx as a requirement and then specify this requirements.txt file in the Advanced Settings of the readthedocs.org admin site. This is described here:

https://nbsphinx.readthedocs.io/en/0.3.3/usage.html#Automatic-Creation-of-HTML-and-PDF-output-on-readthedocs.org

**Comment by artur-trzesiok** [comment]
Thanks! Our readthedocs is currently online: 
https://k3d-jupyter.readthedocs.io/en/latest/examples/index.html
