### ISSUE TITLE
Unknown keyword grid_visible

### ISSUE THREAD

**Issue by marcomusy** [K3D-tools/K3D-jupyter#168]
I get an error message from plot():
![Screenshot from 2019-06-17 13-35-35](https://user-images.githubusercontent.com/32848391/59602898-3f57df00-9108-11e9-85f1-fc6ccb14201a.png)

but the keyword seems to be there:
https://k3d-jupyter.readthedocs.io/en/latest/k3d.html#module-k3d.plot

**Comment by artur-trzesiok** [comment]
Hi,

Thanks for a discovery. I'm curently working on it. In next release that will be fixed.

**Comment by artur-trzesiok** [comment]
Please check @2.6.9

**Comment by marcomusy** [comment]
works perfectly, thanks for the faster-than-light fix :)
