### ISSUE TITLE
Disabling colorLegend programmatically

### ISSUE THREAD

**Issue by bbrument** [K3D-tools/K3D-jupyter#171]
I have a scene with severals objects. I made only one mesh of all these objects because the display can ba quite long. To display differents colors on this one mesh, I use a colormap but I would like to disable the colorLegend of the colormap via my plot function in Python so when I plot the scene, the legend does not display automatically.

**Comment by artur-trzesiok** [comment]
We have that feature right now:
```
plot = k3d.plot()
plot.display()
plot += k3d.something()
plot.colorbar_object_id = -1
```

Please let me know if that works for you.
