### ISSUE TITLE
k3d.plot().display() - can't change background color or axes labels

### ISSUE THREAD

**Issue by thiago-springer-jota** [K3D-tools/K3D-jupyter#172]
![Screen Shot 2019-07-06 at 5 25 33 PM](https://user-images.githubusercontent.com/50302382/60761312-a3890700-a013-11e9-9141-c2d8fc0e233f.png)

![Screen Shot 2019-07-06 at 6 53 06 PM](https://user-images.githubusercontent.com/50302382/60761854-63c81c80-a01f-11e9-8944-5e7df2cabaf1.png)

Hi, I attached a picture of what I see when I run k3d.plot().display() in a couple of test cases. 

It's black, no labels along the axes. I'd like to change the background color and axes labels. 

Thanks for the help

**Comment by banesullivan** [comment]
I too am trying to figure out how to change the axes label color and the scalar bar labels color.

you can change the background color by:

```py
import k3d

plot = k3d.plot()
plot.background_plotter = 5000268
plot.display()
```

**Comment by marijanbeg** [comment]
Hi, I also have a problem changing the background color. Have you found a solution to this?

Thanks

**Comment by thiago-springer-jota** [comment]
Looks like this can happen if you try other similar packages (vtkplotter & vtk), which I did. I tried installing this in another computer (from the ground up) and there was no issue. So, I would not be surprised if you get it to work by uninstalling python (and anaconda if you have it) and re-installing. I have a feeling the settings in Jupyter got messed up, and at this point I really can't tell which package did. If you try in command line python, it should be OK. But it's K3D-jupyter... as in Jupyter. So if there is a way to reset the jupyter notebook settings without reinstallation, which I am sure there is, that may to the trick. I can change the background in vtkplotter running in command line but not in Jupyter. So, logically it's Jupyter. If you know how to easily reset Jupyter without re-install, let me know.

**Comment by marijanbeg** [comment]
Hi @thiago-springer-jota, thank you for your explanation. I managed to make it work in Jupyter inside Google Chrome with the newest versions of Jupyter and k3d.

k3d in JupyterLab (any browser) and k3d in Safari (Jupyter or JupyterLab) do not work for me.

**Comment by artur-trzesiok** [comment]
Hi! I review right now latest version of k3d in latest jupyter lab and everything works like a charm. That is a very old issue so I will close it. We dont change anything in k3d. Probably latest lab have a improvement and fix for that.
