### ISSUE TITLE
Make lines using line segments

### ISSUE THREAD

**Issue by banesullivan** [K3D-tools/K3D-jupyter#173]
Is there a way to make a `k3d.line` object using a set of points and a set of indicies for each segment?

I tried doing this by creating a seperate `k3d.line` object for each segment but it took way too long to add all of them to the scene - it seems terribly inneficient to handle line sets this way.

![LineSetGeometry](https://user-images.githubusercontent.com/22067021/60849967-6d31c000-a1aa-11e9-926a-4e16febef078.png)

Example: contours lines - contours (lines) are made up of many (hundreds to thousands) segments. How would I make a K3D mesh of this type of dataset?

![download](https://user-images.githubusercontent.com/22067021/60850047-b1bd5b80-a1aa-11e9-98ed-5087e1072f46.png)

relevant to https://github.com/pyvista/pyvista/pull/300

**Comment by marcinofulus** [comment]
It is in 2.6.10 possible to set some points to [np.nan,np.nan,np.nan], they will not be displayed and will split a line into line segments. It is a sort of a hack but it works well.

e.g
phi = np.linspace(0,6*np.pi,250).astype(np.float32)
phi[::50] = np.nan
k3d.line( np.stack([np.cos(phi),np.sin(phi),0.1*phi]).T )

**Comment by artur-trzesiok** [comment]
@marcinofulus I think we should add an explicit example of that feature to our "examples" directory
