### ISSUE TITLE
Use with PyVista (VTK)

### ISSUE THREAD

**Issue by banesullivan** [K3D-tools/K3D-jupyter#174]
I've been experimenting with leveraging K3D as an option for notebook rendering with [PyVista](https://github.com/pyvista/pyvista): a pure-Python wrapping of the VTK library, directly inheriting VTK's mesh/volume types. This will likely have a lot of overlap with #156, as both `vtkplotter` and `pyvista` are VTK-based packages, however, `pyvista` has a totally different design philosophy than `vtkplotter` and `k3d` where display attributes are kept entirely separate from mesh/volume datasets so that the focus can be on the underlying finite element/volume discretizations and display attributes are only relevant when plotting.

We're experimenting with using K3D as a notebook previewer/plotter over in https://github.com/pyvista/pyvista/pull/300 and have a hefty list of TODOs for the K3D plotter. Could you all help us tackle some of the items in our todo list for implementing K3D over there?

Thanks!

**Comment by banesullivan** [comment]
**Thought experiment:** What if instead of creating a PyVista to K3D exporter over in PyVista, we expanded K3D to have more functions like `k3d.vtk_poly_data` but for more VTK types? Specifically, all the types that PyVista wraps. And maybe use PyVista to convert those datasets to `k3d` objects since PyVista makes interfacing numpy with VTK types super easy.

**Comment by banesullivan** [comment]
@marcomusy - if the K3D developers are open to my second comment above about adding more VTK conversion methods from types like `vtkRectilinearGrid`, `vtkImageData`, `vtkUnstructuredGrid`, etc. then this might be an excellent place for us to collaborate!

**Comment by artur-trzesiok** [comment]
We can add more helpers like vtk_poly_data. Probably, in that case, we should create something like k3d.vtk_helper.* to group all methods in one place. But please remember that vtk_poly_data is a one-way importer - under hood create a k3d.mesh. 

3d vtkImageData easily can be a draw as k3d.volume 
2d vtkImageData easily can be a draw as k3d.texture with attribute
vtkRectilinearGrid can be probably only incorporate as k3d.mesh with attribute
vtkUnstructuredGrid is very generic - this is something that will be quite hard to manage automatically. 

Please attach here a few examples of files that you like to open in k3d with that kind of helpers.  I would like to have an open license for that file and make from them a part of examples in k3d.
