### ISSUE TITLE
Isosurface Opacity

### ISSUE THREAD

**Issue by Einstein11** [K3D-tools/K3D-jupyter#176]
I am trying to do a plot similar to the one below.

![Q_crit_Vort](https://user-images.githubusercontent.com/38961789/60913758-14b7fc80-a256-11e9-8144-01f11aedb060.png)

Is there a way to give an isosurface some opacity? If not, could it be implemented?

**Comment by artur-trzesiok** [comment]
+1. I will add that feature in next release.

**Comment by Einstein11** [comment]
That would be great, thank you. On a different note, how feasible would it be to include an option that allows the isosurface to be colored with a scalar? For instance, have the color of the isosurface depend on the temperature at that location.

**Comment by artur-trzesiok** [comment]
please add three k3d.marching_cubes with this same data and different level and color.

**Comment by artur-trzesiok** [comment]
@Einstein11 version 2.7.0 have a opacity parameter in k3d.marching_cubes.
