### ISSUE TITLE
Screenshot Quality in Volume Rendering

### ISSUE THREAD

**Issue by Einstein11** [K3D-tools/K3D-jupyter#177]
I've extracted images of volume rendering plots using the UI, but the figure appears to be turned into some kind of contour plot. In the first image below, you can notice this near the edge of the jet.

![k3d-capture](https://user-images.githubusercontent.com/38961789/60915021-cbb57780-a258-11e9-9cc3-2b03103e827e.png)

I have found a "work-around" by printing the screen and cropping the UI out of the image, as shown below.

![Print_Screen](https://user-images.githubusercontent.com/38961789/60915200-3b2b6700-a259-11e9-9871-9e97a56721e4.png)

Is there a way this could be corrected? It is really inconvenient when trying to extract multiple images.

**Comment by artur-trzesiok** [comment]
Very strange behavior. Can you provide an npz or vti file with that volume + ipynb? I will try to figure out what is happening here. It's look like a problem of antialiasing (averaging of very small numbers). Please try 

`plot = k3d.plot(antialias=0)`

**Comment by artur-trzesiok** [comment]
@Einstein11 can you confirm that in version 2.7.0 this issue is already fixed?
