### ISSUE TITLE
Module k3d, semver range 2.6.9 is not registered as a widget module

### ISSUE THREAD

**Issue by LunarLanding** [K3D-tools/K3D-jupyter#178]
After installing via conda, and also ipywidgets like so:
`conda install -c conda-forge ipywidgets`
`jupyter labextension install @jupyter-widgets/jupyterlab-manager`

In a jupyter cell:
```python
import k3d
plot = k3d.plot()
plot.display()
```
Output:
`Error displaying widget: model not found`

In the dev window:
`Error: "Module k3d, semver range 2.6.9 is not registered as a widget module"`

Python 3.7.3
jupyterlab 1.02
k3d 2.6.9
[conda_list.txt](https://github.com/K3D-tools/K3D-jupyter/files/3443844/conda_list.txt)
[conda_list_explicit.txt](https://github.com/K3D-tools/K3D-jupyter/files/3443845/conda_list_explicit.txt)
[jupyterlab_labextension_list.txt](https://github.com/K3D-tools/K3D-jupyter/files/3443846/jupyterlab_labextension_list.txt)

I will try to install most of the components by source and see if it improves anything.

PS:
* ipywidgets's slider on jupyterlab functions correctly.
* currently installing jupyterlab, ipywidgets, and k3d via conda-forge channel. was using a mix before.
* using conda-forge, ipywidgets works as before but jupyterlab-datawidgets  fails to load:
```
Plugin 'jupyter.extensions.datawidgets' failed to activate.
No provider for: jupyter.extensions.jupyterWidgetRegistry.
```
* tried `jupyter lab clean & jupyter lab build` . does not solve it. same error.
* this kind of issue seems to be related https://github.com/jupyter-widgets/ipywidgets/issues/2361
*

**Comment by vidartf** [comment]
K3D does not seem to support Jupyterlab 1.0 yet. Needed steps to add support:
- Allow `@jupyter-widgets/base` v2 (ideally `^1.2.3 || ^2.0.0`).
- Upgrade `jupyter-dataserializers` to `^2.1.0`
- Handle any backwards incompatibilities.

**Comment by artur-trzesiok** [comment]
@vidartf I bump a version of jupyter-widgets/base . I seems to work in jupyterlab right now but still as an experimental mode (ex. https://github.com/K3D-tools/K3D-jupyter/issues/131 is still valid)

**Comment by piotrm0** [comment]
I'm getting the same problem now but with version 2.7.4:

```Uncaught (in promise) Error: Module k3d, semver range 2.7.4 is not registered as a widget module
    at b.loadClass (manager.js:319)
    at b.<anonymous> (manager-base.js:264)
    at s (manager-base.js:45)
    at Object.next (manager-base.js:26)
    at manager-base.js:20
    at new Promise (<anonymous>)
    at Rtm6.F (manager-base.js:16)
    at b.e._make_model (manager-base.js:258)
    at b.<anonymous> (manager-base.js:247)
    at s (manager-base.js:45)```
