### ISSUE TITLE
Adding k3d.points on click 

### ISSUE THREAD

**Issue by Gulaabihaathee** [K3D-tools/K3D-jupyter#179]
How to add a k3d.points object on k3d.plot on click in the position of cursor?

**Comment by tgandor** [comment]
It can only be done for Voxels, see: examples/voxel_edit.ipynb

I don't see a way to do it for Points, because a point needs 3 coordinates (x, y, z), and a click can only provide two (viewport_x, viewport_y).

**Comment by Gulaabihaathee** [comment]
I read that code and found that. Thanks for your response.
