### ISSUE TITLE
Missing validation of ASCII STL data

### ISSUE THREAD

**Issue by tgandor** [K3D-tools/K3D-jupyter#182]
Passing invalid string (ASCII) data to `k3d.stl()` doesn't raise `ValueError`.
(for example, passing a file name / path of an STL file)

Instead, an object is created which is unable to be displayed.

Expected behavior: an error should be raised.

**Comment by tgandor** [comment]
The data validation was added in commits:
2a2b8ccc8d64be7972a1a25641dbfe7f78db821b
98947a42c0fc173c58a8670714bf9baedd92c97b
on the devel/ branch.

**Comment by tgandor** [comment]
Reassigning for review and/or approval.

**Comment by artur-trzesiok** [comment]
Thanks a lot!.
