### ISSUE TITLE
update of attribute does not affect plot

### ISSUE THREAD

**Issue by marcinofulus** [K3D-tools/K3D-jupyter#185]
Suppose that we run:
import numpy as np
import k3d
k3d.version_info
plot = k3d.plot()
xyz = np.cumsum(np.random.randn(100,3),axis=0).astype(np.float32)

plt_traj = k3d.line([[0,0,0],[1,1,1]])
plot += plt_traj
plot.display()

the if the plot is already visible one does in other cell:
plt_traj.vertices = xyz

then no update is visible (however running additional  plot.display() works ).

**Comment by tgandor** [comment]
On version 2.6.10 I don't observe this.
(the Brown-motion trajectory appeared as it should). Not running plot.display() again.

**Comment by artur-trzesiok** [comment]
I agree with @tgandor . @marcinofulus can you check it again?
