### ISSUE TITLE
update problem in lines

### ISSUE THREAD

**Issue by marcinofulus** [K3D-tools/K3D-jupyter#187]
Let make a plot:
import k3d

plot = k3d.plot()
plt = k3d.line([[1,2,3],[2,3,1]])
plot += plt
plot

updating data:
plt.vertices = [[1,2,3],[2,1,1]]

suddenly changes line to be white.

It happens only with default shader='thick'

**Comment by marcinofulus** [comment]
just to confirm that in 2.6.10 is was the same

**Comment by artur-trzesiok** [comment]
Please check v2.7.1

**Comment by marcinofulus** [comment]
It works fine now in 2.7.2,
