### ISSUE TITLE
Plot a textured surface

### ISSUE THREAD

**Issue by eladrich** [K3D-tools/K3D-jupyter#188]
Hi,
Great library!
I was wondering if there is a way to plot a textured surface using the `3d.surface` function, something similar to Matlab `surf(Z,C)` functionality.

**Comment by marcinofulus** [comment]
Currently we have k3d.mesh, but is is a bit lower level.
 If you work with vtk then there is a helper k3d.vtk_poly_data which effectively makes k3.mesh object. 

Perhaps you could write a helper function for k3d.mesh object which would resemble matlab surf?

**Comment by artur-trzesiok** [comment]
Please look at https://github.com/K3D-tools/K3D-jupyter/blob/devel/examples/surface.ipynb

![image](https://user-images.githubusercontent.com/5256837/72061474-3e6de100-32d6-11ea-9533-5bc241cec7b1.png)

**Comment by eladrich** [comment]
While this allows some control using colormaps and attributes, I wasn't able to easily set a specific color for each vertex. What I think is missing is a functionallity similar to that of the colors in k3d.points. 

I ended up using  k3d.surface for a fixed color visualization and k3d.points for plotting with color, which is a bit awkward (but looks great).
![jupyter_gif](https://user-images.githubusercontent.com/7377266/81239348-4718be80-900d-11ea-8c90-4f33d557bb3b.gif)

**Comment by artur-trzesiok** [comment]
Very impressive example!

**Comment by artur-trzesiok** [comment]
@eladrich good news :)
![image](https://user-images.githubusercontent.com/5256837/81359247-e6ef4e80-90d8-11ea-8cc4-4ece5f6f8a75.png)
![image](https://user-images.githubusercontent.com/5256837/81359278-ff5f6900-90d8-11ea-97d4-aaceb11f75ae.png)

I used the data from your binder and put it in the example of this function in k3d: https://github.com/K3D-tools/K3D-jupyter/blob/devel/examples/textured_mesh.ipynb.

If you'd rather I didn't do it, please write.

**Comment by eladrich** [comment]
Awesome! No problem at all, happy to be part of the examples :-)

**Comment by godisme1220** [comment]
> @eladrich good news :) ![image](https://user-images.githubusercontent.com/5256837/81359247-e6ef4e80-90d8-11ea-8cc4-4ece5f6f8a75.png) ![image](https://user-images.githubusercontent.com/5256837/81359278-ff5f6900-90d8-11ea-97d4-aaceb11f75ae.png)
> 
> I used the data from your binder and put it in the example of this function in k3d: https://github.com/K3D-tools/K3D-jupyter/blob/devel/examples/textured_mesh.ipynb.
> 
> If you'd rather I didn't do it, please write.

the link has expired, could you please reupload?
