### ISSUE TITLE
hold_sync or equivalent for batch updating

### ISSUE THREAD

**Issue by hellcats** [K3D-tools/K3D-jupyter#191]
I'd like to perform a batch update of the state of a scene graph. Display events are generated synchronously when you naively change properties (such as a transform).  This causes a refresh for each change, which can get quite slow and results in "swimming" where partially updated state is displayed. 

ipywidgets has a method called hold_sync, but using this with a K3D drawable doesn't seem to help (e.g. I place all the objects I want to update in a Group, and use hold_sync on the group while making the changes). Assume that all `meshes[]` have been added to the `group`:
```
for i in range(50):
    with group.hold_sync():
        for j in range(len(meshes)):
            meshes[j].transform.translation = [0,float(i)/10,2*j]
```
I'm not that familiar with ipywidgets or how this should be done.

**Comment by tgandor** [comment]
Hi @hellcats,

While `Group` technically is a `Widget` (like any `Drawable`), it currently doesn't propagate the `hold_sync()` call to its members. It means, that this context manager only prevents events from modifying the group's own fields (of which there aren't any to speak of - `__objs` is not a synced traitlet.

We could implement such a feature, what do you think @artur-trzesiok ?

Right now you would need to `hold_sync` for all your `meshes` instead. I think an `ExitStack` or `nested` (python 2.7) combined with a list comprehension could do the job for now.

See more:
https://stackoverflow.com/a/3025119/1338797
https://stackoverflow.com/a/50266687/1338797

Updating the whole group is also possible by using it's `__setattr__` method, but `transform` is a special case, which would not work this way (only member fields can be set this way).

We'll look into it, and consider adding this feature.

**Comment by hellcats** [comment]
@tgandor. Thanks for the quick response.  I tried doing hold_sync on each mesh independently.  I also tried removing the group from the plot, modifying it, and then adding it back in.  But after playing around with K3D some more, I'm seeing apparent synchronous behavior even for just displaying something. For instance, create a plot with the following code.

```
import k3d
import k3d.platonic as platonic
import math
import numpy as np

plot = k3d.plot()

colors = [0xff0000, 0x00ff00, 0x0000ff, 0xffff00, 0xff00ff]

for j in range(5):
    meshes = [
        platonic.Dodecahedron().mesh,
        platonic.Cube().mesh,
        platonic.Icosahedron().mesh,
        platonic.Octahedron().mesh,
        platonic.Tetrahedron().mesh
    ]

    for i, obj in enumerate(meshes):
        rad = math.radians(i / len(meshes) * 360)
        radius = 3.5
        obj.transform.translation = [math.sin(rad) * radius, math.cos(rad) * radius, 2*j]
        obj.color = colors[i]
        plot += obj
```
Then display with 
```
plot.display()
```
You can watch as it slowly adds all the objects to the scene. The client is Chrome 78.0.3904 on Windows 10 and the Jupyter server is running Python3 from inside Docker.

**Comment by tgandor** [comment]
Right now, updating the model_matrix of an object leads to it being removed and added again. This can't be helped with `hold_sync`. Also, when you "unhold" the sync, it will not happen all at the same time - the cascade of events will just start to flow again.

If you want to have an animation, it may be better to collect a series of screenshots, and convert it to a movie using e.g. ffmpeg: https://github.com/K3D-tools/K3D-jupyter/blob/master/examples/screenshot_generator.ipynb

**Comment by hellcats** [comment]
My plan was to use K3D to visualize simulation and dynamical graphic data within a notebook environment (and not just to make movies). I was attracted to the ease of use and dynamic scene graph capabilities of K3D. I like that changing a property results in immediate display. But I also need to make big changes (like stepping forward a time step in a simulation with hundreds or thousands of objects), and for that I need some kind of batch capability.  Maybe that isn't a goal of K3D, or maybe the serialized/synchronous behavior is tied to the architecture of ipywidgets. I spent just a little time trying to read the code, but I don't really understand the gestalt of the system.  I'll check back from time to time, but for now I'll probably look for an alternative.

**Comment by artur-trzesiok** [comment]
K3D by default run "render" method after any scene graph modification (out assumption is that we should show a result as fast as possible). This is a reason why your code add objects with iterations. K3D is optimize for huge data. When you open a developer console you will be able to see that object loading is in "no time":

```
Loader.js:59 K3D: Object type "Mesh" loaded in:  0 s
Loader.js:59 K3D: Object type "Mesh" loaded in:  0.001 s
Loader.js:59 K3D: Object type "Mesh" loaded in:  0 s
Loader.js:59 K3D: Object type "Mesh" loaded in:  0.001 s
Loader.js:59 K3D: Object type "Mesh" loaded in:  0 s
Loader.js:59 K3D: Object type "Mesh" loaded in:  0.001 s
Loader.js:59 K3D: Object type "Mesh" loaded in:  0 s
```

Please give me some time. I must analyse how to implement it in the best way.

**Comment by artur-trzesiok** [comment]
First hint: To get a best performance please disable default params in plot:

`plot = k3d.plot(camera_auto_fit=False, grid_auto_fit=False, `grid_visible=False)`

and manage it manualy:

`plot.camera_reset()`

**Comment by artur-trzesiok** [comment]
https://www.youtube.com/watch?v=9gfkcLkoW6w

**Comment by artur-trzesiok** [comment]
A working version is in devel. We need still do some tests but looks promising :). Please look forward to v2.7.2

**Comment by marcinofulus** [comment]
Moving camera (or updating plot.camera) will trigger render even if `plot.auto_rendering = False`. It is probably not a big problem in practice so I think this issue can be closed.

**Comment by artur-trzesiok** [comment]
> Moving camera (or updating plot.camera) will trigger render even if `plot.auto_rendering = False`. It is probably not a big problem in practice so I think this issue can be closed.

I know. Thats why i call property "auto_rendering". It's not a hold for hole rendering - mouse interaction is still possible. But I agree that probably updating plot.camera shouldn't  trigger render function. I can fix it.

**Comment by hellcats** [comment]
@artur-trzesiok Thanks for looking into this issue - I am pretty happy with it now and will continue with my evaluation. I tried to follow the code changes you made to implement this, but I don't know javascript or how ipywidgets works.  I still have to learn a lot.
