### ISSUE TITLE
K3D menu

### ISSUE THREAD

**Issue by MattiaMartinelli** [K3D-tools/K3D-jupyter#197]
Good morning,
I have a question about the 3D plotter.
May I ask you how do you create the menu on the right where it is possible to show/hide the loaded object etc?

Thank you

Mattia

**Comment by marcinofulus** [comment]
In the Objects submenu you can find flag "visible".
Does it address your question?

**Comment by tgandor** [comment]
I'm also not exactly sure about what you're asking about.

If you mean how it is done technically, then it is based on the dat.gui library which you can find here: https://github.com/dataarts/dat.gui - here's a tutorial if you'd like to play with it: https://workshop.chromeexperiments.com/examples/gui/#1--Basic-Usage
