### ISSUE TITLE
Transparency per point in point set

### ISSUE THREAD

**Issue by mironvanderkolk** [K3D-tools/K3D-jupyter#198]
Would it be possible to add the option of passing an array of opacities to a point set, instead of setting one value for all the glyphs in a point set?

`k3d.k3d.points(positions, colors=[], color=255, point_size=1.0, shader='3dSpecular', opacity=1.0, name=None, compression_level=0, mesh_detail=2, **kwargs)`

 Another way of doing this could be to have a point set for every separate glyph, but that seems cumbersome.

**Comment by mironvanderkolk** [comment]
I have tried creating a point set for each separate glyph with the following snippet:
```import k3d
import numpy as np
nblobs = 100
positions = np.zeros([nblobs, 3], dtype=np.float32)
positions[:, 0] = np.linspace(0, 10, nblobs)
positions[:, 1] = np.random.rand(nblobs)*10
positions[:, 2] = np.random.rand(nblobs)*10
opacities = np.linspace(0, 1, nblobs)
plot = k3d.plot(antialias=False)

for i in range(nblobs):
    plt_points = k3d.points(positions=positions[i], point_size=1.0, opacity=opacities[i], shader='3d')
    plot += plt_points

plot.display()
```

This works, but it takes a long time and it crashes when I try to do a thousand. I also saw you can pass a dictionary as an argument for the opacity, I tried passing a dictionary with indices as keys and opacities as values:

```
nblobs = 100
positions = np.zeros([nblobs, 3], dtype=np.float32)
positions[:, 0] = np.linspace(0, 10, nblobs)
positions[:, 1] = np.random.rand(nblobs)*10
positions[:, 2] = np.random.rand(nblobs)*10
opacities = np.linspace(0, 1, nblobs)
opc = {}
for i in range(nblobs):
    opc[i] = opacities[i]
print(opc)
plot = k3d.plot(antialias=False)

# for i in range(nblobs):
plt_points = k3d.points(positions=positions, point_size=1.0, opacity=opc, shader='3d')
plot += plt_points

plot.display()```

It didn't throw an error, but it showed me a display empty of glyphs

**Comment by marcinofulus** [comment]
Opacity per point is a nice functionality and it will be implemented in next release.

Your last code example you passed dict to an attribute  - it is interpeted as a timeseries which can be used for animation. But in 2.7.2 still it will be one opacity per all points in one plot object.

**Comment by artur-trzesiok** [comment]
k3d.points will have attribute "opacities"

**Comment by mironvanderkolk** [comment]
Thanks a lot for the answers. Is this now implemented in 2.7.3?

**Comment by artur-trzesiok** [comment]
Unfortunately not. It will be in 2.7.4 (https://github.com/K3D-tools/K3D-jupyter/pull/206)

**Comment by artur-trzesiok** [comment]
https://github.com/K3D-tools/K3D-jupyter/blob/devel/examples/ifs-per-point-opacity.ipynb

**Comment by artur-trzesiok** [comment]
K3D@2.7.4 is released!

**Comment by mironvanderkolk** [comment]
![image](https://user-images.githubusercontent.com/56925246/74728673-7c4e1580-5243-11ea-9c1d-74e704d7db4c.png)

Upgrading to 2.7.4 seems to break my jupyter environment:
```JupyterLab v1.1.4
Known labextensions:
   app dir: /home/miron/.pyenv/versions/3.7.4/envs/labwithipyvolume/share/jupyter/lab
        @jupyter-voila/jupyterlab-preview v0.1.3  enabled  OK
        @jupyter-widgets/jupyterlab-manager v1.0.3  enabled  OK
        ipysheet v0.4.3  enabled  OK
        ipyvolume v0.5.2  enabled  OK
        itkwidgets v0.24.2  enabled  OK
        jupyter-matplotlib v0.4.2  enabled  OK
        jupyter-threejs v2.1.1  enabled  OK
        jupyter-vue v1.0.2  enabled  OK
        jupyterlab-datawidgets v6.2.0  enabled  OK
        k3d v2.7.4  enabled  OK

```

**Comment by artur-trzesiok** [comment]
Please paste javascript console output

**Comment by mironvanderkolk** [comment]
I'm sorry, I'm not sure how to access the javascript console?

**Comment by artur-trzesiok** [comment]
F12 or menu->more tools->developer console

**Comment by mironvanderkolk** [comment]
```
manager.js:292 Uncaught (in promise) Error: Module k3d, semver range 2.7.2 is not registered as a widget module
    at b.loadClass (manager.js:292)
    at b.<anonymous> (manager-base.js:263)
    at c (manager-base.js:44)
    at Object.next (manager-base.js:25)
    at manager-base.js:19
    at new Promise (<anonymous>)
    at Rtm6.A (manager-base.js:15)
    at b.e._make_model (manager-base.js:257)
    at b.<anonymous> (manager-base.js:246)
    at c (manager-base.js:44)
    at Object.next (manager-base.js:25)
    at manager-base.js:19
    at new Promise (<anonymous>)
    at Rtm6.A (manager-base.js:15)
    at b.e.new_model (manager-base.js:232)
    at b.e.handle_comm_open (manager-base.js:144)
```

Seems to be something off with version number?

**Comment by artur-trzesiok** [comment]
Please try run command from https://github.com/K3D-tools/K3D-jupyter/issues/122#issuecomment-555940976

**Comment by mironvanderkolk** [comment]
Thanks, everything is working now!

**Comment by artur-trzesiok** [comment]
@marcinofulus maybe we should add to readme FAQ section and put a sentence how to compare backend and frontend version after upadting k3d and what can help? 

Another idea is to show a warning bar in k3d if backend ver!==frontend ver. What do you think?

**Comment by tgandor** [comment]
I think we should add this to README anyway:

- move up the part about JupyterLab (it's there, but even below `pip -e .` installation)
- add a notice that the commands are also recommended after updating K3D version

The warning about version mismatch - JS can display a bar if it works at all. If it wasn't loaded, then there will be no way to help the user (especially after failed initial install, not update). Is there a way to check the extensions from Python side? Also - does the kernel know at all if it is running in Notebook or Lab?

**Comment by artur-trzesiok** [comment]
> Is there a way to check the extensions from Python side? 

No. Client browser can have agressive cache system and even if js code on server have correct version you cannot be sure that working js code have a good one.
