### ISSUE TITLE
Save interactive plot as HTML from Terminal

### ISSUE THREAD

**Issue by gautham-phenomx** [K3D-tools/K3D-jupyter#201]
I am able to save the interactive plot as html from Jupyter notebook. How can I do this from the terminal with the code as a python file?

**Comment by artur-trzesiok** [comment]
Hi,
I'm working on it right now. Look out for the next commit :)

**Comment by artur-trzesiok** [comment]
```
f = open('./output.html', 'w', encoding='UTF-8')
f.write(plot.get_snapshot(9))
f.close()
```

Do you need something like this?

**Comment by gautham-phenomx** [comment]
Yes. Below is the code I used in Jupyter notebook to output the html file. But this code doesnt work when I run the same from terminal as a .py file. 
```
plot.display()
plot.fetch_snapshot()
html = plot.snapshot
with open(os.path.join(args.outdir, "file.html"), "w") as file:
     file.write(html)
```

**Comment by gautham-phenomx** [comment]
This could be I am guessing because the code requires the plot to be generated before it can fetch the plot. Now the variable html is just returning me an empty string instead of the html file.

**Comment by artur-trzesiok** [comment]
plot.fetch_snapshot() is a async function get fetch data from javascript side. On termin mode you don't have any js code.  That's why I add plot.get_snapshot that create snapshot from kernel side only. That feature will be added in 2.7.3. Everything is ready - I still testing it.

**Comment by gautham-phenomx** [comment]
Thats Great! Would be really helpful if could release the version soon. Looking forward to the update in 2.7.3.

**Comment by gautham-phenomx** [comment]
Got the get_snapshot function working. Thank you
