### ISSUE TITLE
Pass RGB values to voxels

### ISSUE THREAD

**Issue by drwelby** [K3D-tools/K3D-jupyter#209]
`points` provides a way to pass RGB values to each point. Is there a way to do the same with `voxels` instead of using a colormap?

**Comment by marcinofulus** [comment]
Voxels are by definition "3D array of `int` in range (0, 255)."

Do you want more colors? Perhaps volume could do a job?

**Comment by drwelby** [comment]
Thanks, I will look further at using volumes.
