### ISSUE TITLE
Hardcoded dependency to dat.gui github repo for jupyterlab extension

### ISSUE THREAD

**Issue by nicolaschotard** [K3D-tools/K3D-jupyter#210]
Hello,

I'm trying to install the `k3d` jupyterlab extension from a place where I do not have access to github, with a installation made through an entreprise npm-registry. And I notice that during the installation, a git command is launched trying to reach the `dat.gui` github repo in order to get it, which ends up with a failed install::

    "dat.gui": "git+https://github.com/K3D-tools/dat.gui.git#b4123f5acf201be4275924ea89c96b9326653f49",  

in https://github.com/K3D-tools/K3D-jupyter/blob/master/js/package.json#L72

Would it be possible to remove this hardcoded dependency and instead point to an npm version of dat.gui?

In any case, thank you for your work!

**Comment by artur-trzesiok** [comment]
Unfortunately, dat.gui has limitations which forced us to make fork and make our own modifications to it.

**Comment by nicolaschotard** [comment]
Ok, I understand, thanks for your quick answer.
