### ISSUE TITLE
Standard method removing objects from plot

### ISSUE THREAD

**Issue by mironvanderkolk** [K3D-tools/K3D-jupyter#211]
I was wondering what the intended way of removing drawables from a plot instance was. 
I have been using the `__isub()__` method of the plot class, but there has to be a better way?
Is there a convenient way to remove all drawables or empty a plot?
I see some references to the Group object in the source code, but not in the documentation

**Comment by marcinofulus** [comment]
Yes:

```
plot = k3d.plot()
plts = [k3d.points([[1,2,i]]) for i in range(10)]   

for plt in plts:
    plot += plt

for plt in plts:
    plot -= plt
```

**Comment by mironvanderkolk** [comment]
Ah, so obvious. Still, it might be nice to add this to the documentation?

**Comment by marcinofulus** [comment]
if you loose handle to an plot objects, there is a list `plot.objects`.
For example removing last plot would be:
`plot -= plot.objects[-1]`
