### ISSUE TITLE
Scientific notation for axis labels

### ISSUE THREAD

**Issue by johnomotani** [K3D-tools/K3D-jupyter#213]
Would it be possible to have (automatic or to be turned on with an option/argument/control) scientific notation for the colorbar axis?

For example, the colorbar here looks a bit silly...
![K3D-1585759198272](https://user-images.githubusercontent.com/3958036/78163204-f88d6880-743f-11ea-88a9-bf8591470730.png)

Would be nice to have for coordinate axes too, although that's not something I need at the moment.

**Comment by tgandor** [comment]
I think I know how to improve it. (Number.prototype.toPrecision(something))

Attaching minimal reproducible examples is appreciated when reporting issues, but here it's clear enough.

I'll discuss with my teammates what the default could be and whether we need the precision to be configurable.

**Comment by artur-trzesiok** [comment]
K3D@2.8.0 is released. You can update package via pypi or conda. This fix is included there.

**Comment by johnomotani** [comment]
Thanks for looking at this @tgandor! On a very quick check, I sometimes get strange looking results. Will try to make a reproducible example when I get time...

**Comment by johnomotani** [comment]
```
from matplotlib.tri import Triangulation
import numpy as np
import k3d

# this code is a part of matplotlib trisurf3d_demo
n_radii = 8
n_angles = 36

radii = np.linspace(0.125, 1.0, n_radii, dtype=np.float32)
angles = np.linspace(0, 2*np.pi, n_angles, endpoint=False, dtype=np.float32)[..., np.newaxis]

x = np.append(np.float32(0), (radii*np.cos(angles)).flatten())
y = np.append(np.float32(0), (radii*np.sin(angles)).flatten())

z = np.sin(-x*y)
indices = Triangulation(x,y).triangles.astype(np.uint32)

plot = k3d.plot()

attribute = 1.0e16*z

plot += k3d.mesh(np.vstack([x,y,z]).T, indices,
                 color_map = k3d.colormaps.basic_color_maps.Jet,
                 attribute=attribute)

plot.display()

from matplotlib.tri import Triangulation
import numpy as np
import k3d

# this code is a part of matplotlib trisurf3d_demo
n_radii = 8
n_angles = 36

radii = np.linspace(0.125, 1.0, n_radii, dtype=np.float32)
angles = np.linspace(0, 2*np.pi, n_angles, endpoint=False, dtype=np.float32)[..., np.newaxis]

x = np.append(np.float32(0), (radii*np.cos(angles)).flatten())
y = np.append(np.float32(0), (radii*np.sin(angles)).flatten())

z = np.sin(-x*y)
indices = Triangulation(x,y).triangles.astype(np.uint32)

plot = k3d.plot()

attribute = 1.0e26*z

plot += k3d.mesh(np.vstack([x,y,z]).T, indices,
                 color_map = k3d.colormaps.basic_color_maps.Jet,
                 attribute=attribute)

plot.display()
```
![k3d_colorbar_scientific_1](https://user-images.githubusercontent.com/3958036/81348697-7cc5b200-90b6-11ea-94d0-02ab7aa5c216.png)
![k3d_colorbar_scientific_2](https://user-images.githubusercontent.com/3958036/81348710-83542980-90b6-11ea-999b-c1f2c979b905.png)

Looking at #216 it seems like there's a `colorbar_scientific` setting that I need to change - how do I set it to `True`? I tried doing `from k3d.plot import Plot; Plot.colorbar_scientific = True` and `plot = k3d.plot(); plot.colorbar_scientific = True` but neither seemed to have an effect.

**Comment by tgandor** [comment]
I'm sorry - this is my first try to implement a global setting and I must have missed something.
I'll try to resolve this soon, and then it should be available on our devel branch, i.e. 
`pip install git+https://github.com/K3D-tools/K3D-jupyter.git@devel`.

I'll get back to you when this is fixed. Thanks for the example, I wil use it.

**Comment by tgandor** [comment]
(WiP) I'm not sure why the setting `plot.colorbar_scientific = True` seems to have no effect unless:
- it is run after the plot is displayed
- the colorbar is turned off and then on again on the object in GUI controls

(this is not yet a solution, I need to look deeper into it; I'm comparint it to a similar setting - camera_auto_fit, a.k.a. cameraAutoFit on the JS side).
