### ISSUE TITLE
Reset camera does not reset rotation of object

### ISSUE THREAD

**Issue by johnomotani** [K3D-tools/K3D-jupyter#215]
The "Reset camera" control seems to only reset the position of the camera relative to the centre of the object. If the object was rotated interactively, it remains rotated. It therefore does not seem to be possible to return to the original view.

I think it would be nice if "Reset camera" returned to the original view. The ideal might be to have 3 buttons (or some sort of drop-down menu maybe?) allowing i) "Reset camera position" (current behaviour of "Reset camera"); ii) "Reset camera rotation"; iii) "Reset camera" - combination of i) and ii), resets view back to the original state.

**Comment by artur-trzesiok** [comment]
please look at get_snapshot result with wrong zooming or camera view #251
