### ISSUE TITLE
Unicode support in Text Drawable

### ISSUE THREAD

**Issue by ahulist** [K3D-tools/K3D-jupyter#217]
Right now KaTeX typesetter complains about characters such as `ł`:

    Error setting state: KaTeX parse error: Expected 'EOF', got 'ł'

Native Unicode support (e.g. `html-text`) would be quite useful.

**Comment by artur-trzesiok** [comment]
K3D@2.8.0 is released. You can update package via pypi or conda. This fix is included there.
