### ISSUE TITLE
K3D and Google Colab

### ISSUE THREAD

**Issue by eladrich** [K3D-tools/K3D-jupyter#220]
Hi,
I was wondering whether it's possible to use K3D inside a Google Colab notebook. Any tips on how to get it to work?

Best,
Elad

**Comment by artur-trzesiok** [comment]
@eladrich it's a very hot topic right now: https://github.com/googlecolab/colabtools/issues/60 or https://github.com/maartenbreddels/ipyvolume/issues/147 . Unfornetly it seems like at this moment Google Colab reduces support to nbextensions.

**Comment by eladrich** [comment]
What a bummer :(
If someone is looking for a solution, I found out that [mybinder](https://mybinder.org/) works great with K3D. Here is my [example](https://github.com/eladrich/pix2vertex.pytorch).
