### ISSUE TITLE
add a Box class

### ISSUE THREAD

**Issue by parmentelat** [K3D-tools/K3D-jupyter#221]
Hi

a very low-level comment, but I'd like to report that as part of my 'getting acquainted with k3d' musings I have found that it would be very nice to have a `Box` class to create parallelepipeds

also I'd like to outline that it is IMHO much more convenient to create such objets (cubes or boxes) from a **corner** and size(s) rather than from the **center** and a half-size, like `Cube` currently does

so just in case here's the beginning of my Box class that is otherwise the same as `Cube`

***
```
class Box(PlatonicSolid):
    def __init__(self, corner=[0, 0, 0], sizes=(1, 1, 1)):
        corner = np.array(corner, dtype=np.float32)

        if corner.shape == (3,):
            cube_vertices = np.array(list(product([0, 1], [0, 1], [0, 1])), np.float32)
            cube_vertices = np.float32(sizes * cube_vertices + corner)
     # rest is identical
```

just an FYI I guess; I guess people do not usually use this kind of objects for their first experiment, but it was my case and I found it more flexible with this instead of `Cube`...

thanks so much for that amazing tool !

**Comment by marcinofulus** [comment]
We would be very happy to add your code  for making parallelepipeds. 
Perhaps it would be more clear to add extra file  in codebase for that  but it depends on the range of objects you might need.

**Comment by parmentelat** [comment]
Hey

I'm all for submitting a PR; however I'd like to hear your reactions about this corner/center business 

on the one hand, it would feel very odd to ship 2 classes Cube and Box that do not work the same

but I'm finding the current interface cumbersome; is it OK to break the current API ?

**Comment by tgandor** [comment]
Hi Thierry,

sorry for these 4 weeks, but last time I glanced at this issue I thought it was all settled here.
Let me answer your questions:

1. No, there is no problem with having 2 classes which _can_ do the same thing, under specific circumstances. Or even one being more general than the other.
2. The Box is not a Platonic solid. Go ahead with your contribution, but update the class hierarchy:

```
class Solid:
  # ... mesh(), points() etc.

class PlatonicSolid(Solid): pass

class Box(Solid):
  # ...

# rest inherits PlatonicSolid
```
3. Conceptually, `Cube` is a special case of `Box`, but please - don't do `class Cube(PlatonicSolid, Box)`, because it breaks Liskov ;)

**Comment by tgandor** [comment]
Any progress on a PR? If not, we could probably close this issue.
(creating a Box-like mesh is easy to do manually, we included Cube for completeness of the platonic module)

**Comment by parmentelat** [comment]
Hi, sorry, no I am not working on a PR at this point, but thanks for everything, I am closing this
