### ISSUE TITLE
how to refer to the Plot class

### ISSUE THREAD

**Issue by parmentelat** [K3D-tools/K3D-jupyter#222]
Hi

I'd like to write a class that inherits `k3d.plot.Plot` 

However a naive approach does not let me grab the class object :
```
ipython
Python 3.7.4 (default, Aug 13 2019, 15:17:50)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import k3d

In [2]: plot = k3d.plot()

In [3]: type(plot)
Out[3]: k3d.plot.Plot

In [4]: type(k3d.plot)
Out[4]: function

# so of course here I'm at a dead end
In [5]: k3d.plot.Plot
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-da448c27b99c> in <module>
----> 1 k3d.plot.Plot

AttributeError: 'function' object has no attribute 'Plot'
```

Obviously it's too late to change the meaning of `k3d.plot` but it would make sense IMHO to either

1. rename the `k3d.plot` module into something else,
1. or to explicitly expose the `Plot` symbol right under the `k3d` package by adding in `__init__.py` something like

```
from .plot import Plot 
```

I am just a beginner with this lib, but at first sight it seems like `plot.py` only has this one class to expose to the outside, so I'd got for option 2

**Comment by parmentelat** [comment]
for the record as a workaround, for now I've had to do

```
class Animator(type(k3d.plot())):
   def __init__(self): # etc..
```

**Comment by tgandor** [comment]
Well, we have a little ambiguity here, i.e. the `k3d` module has a member named `plot`, taken from `k3d.factory` and there is also a module `k3d.plot`.

Still:
```
>>> import k3d
>>> from k3d.plot import Plot
>>> Plot
<class 'k3d.plot.Plot'>
>>> k3d.plot
<function plot at 0x7fc3a76e8320>
>>> 
```

So if you want to inherit from Plot:
```
from k3d.plot import Plot
class Animator(Plot):
    pass
```

**Comment by parmentelat** [comment]
oh yes, of course, stupid me 

because `k3d.plot` was not a module but a function, I stupidly assumed it would not work  
but, of course, in the `import` statement, `k3d.plot` is not evaluated !

this being said, how would you feel about exposing **also** 

```
from k3d import Plot
```

?

**Comment by tgandor** [comment]
No problem. It will be there in the next release.

**Comment by artur-trzesiok** [comment]
@tgandor probably it's already relesed and we can close this issue.
