### ISSUE TITLE
2.8.0 does not display plot

### ISSUE THREAD

**Issue by johnomotani** [K3D-tools/K3D-jupyter#223]
I upgraded k3d to 2.8.0 with conda. With no other changes to my Python environment, 2.7.4 gives expected output
![k3d_points_2 7 4](https://user-images.githubusercontent.com/3958036/81180579-24ea5680-8fa3-11ea-999b-d98f953f606a.png)
but 2.8.0 does not plot any points
![k3d_points_2 8 0](https://user-images.githubusercontent.com/3958036/81180622-32074580-8fa3-11ea-8837-ee010d7de0da.png)
Is this a bug, or did something change in the interface?

**Comment by artur-trzesiok** [comment]
@johnomotani please check js version and python version o GUI:
![image](https://user-images.githubusercontent.com/5256837/81181374-abeffc80-8fac-11ea-97e1-83246f0b654d.png)
What version do you have?

**Comment by johnomotani** [comment]
I have Js version 2.7.4, Python version 2.8.0. Guess I should try upgrading Js - could you tell me what package that is exactly please?

**Comment by artur-trzesiok** [comment]
There is a planty source of that problem. Please check browser cache and run
jupyter nbextension install --py k3d and jupyter nbextension enable --py k3d

**Comment by johnomotani** [comment]
Thanks @artur-trzesiok! That's fixed it, I've got plots displaying now.
