### ISSUE TITLE
`plot.time` update not triggered while playing the loop

### ISSUE THREAD

**Issue by rbnvrw** [K3D-tools/K3D-jupyter#228]
I'm trying to create sliders and/or labels that are coupled to the current `time` of the plot like so:
```
import ipywidgets as widgets
from ipywidgets import interact, FloatSlider

# plot is my k3d plot object

time_slider = FloatSlider(value=plot.time, min=0, max=duration)

def update_time(time):
    plot.time = time
    time_slider.value = time
    
l = widgets.link((plot, 'time'), (time_slider, 'value'))

interact(update_time, time=time_slider)
```
The reason is I would like to show properties of the items in the plot as a function of time (for example their `x` position as function of time in a label). Then it is easy to have a time slider above the labels.

The slider / label values should be updated when the time changes. This is working when I use the time slider under "Controls" in the above example: the custom slider value is also updated. However, when I use "Play loop" under "Controls", my custom slider is not updated.

Please let me know how I can achieve this. Thank you very much!

**Comment by artur-trzesiok** [comment]
Nice spot! I'm working on it.

**Comment by artur-trzesiok** [comment]
release 2.8.1 will include an fix :)

**Comment by artur-trzesiok** [comment]
https://anaconda.org/conda-forge/k3d
https://pypi.org/project/K3D/

**Comment by rbnvrw** [comment]
Thank you! I'm looking forward to it :+1:
