### ISSUE TITLE
Colorbar not updating itself

### ISSUE THREAD

**Issue by zbouslikhin** [K3D-tools/K3D-jupyter#229]
Hi,

After @tgandor confirming it as an unexpected behavior, here's the description of a bug related to color bar and how to reproduce it:

- **Description**
While changing programmatically the colormap of a type object (as mesh, line...), the color legend doesn't update itself automatically. Such behavior happens **_ONLY_** when the drawn object visiblity is set to `line.visible = False `. 
In the case of the object's visibility is set to `True`, everything works as expected.

- **_How to reproduce_**

```
plot_3d = k3d.plot(name='MX3D Viz', height=615)
plot_3d.display()
line = k3d.line((0, 0, 0, 5, 10, 15), 
                                         color_map=k3d.colormaps.matplotlib_color_maps.Inferno, 
                                         color_range=[0, 200])
plot_3d += line 
# Important to hide to object in order to reproduce the behavior
line.visible = False
matplotlib_color_maps = [attr for attr in dir(k3d.matplotlib_color_maps) if not attr.startswith('__')]
x = widgets.Dropdown(options=matplotlib_color_maps, 
                                               value=matplotlib_color_maps[0], 
                                               description='ColorMap')
display(x)
def observer(widg):
    colormap = getattr(k3d.matplotlib_color_maps, widg['new'])
    line.color_map = colormap
x.observe(observer, 'value')
```
Cheers,
Zaid

**Comment by artur-trzesiok** [comment]
release 2.8.1 will include an fix :)

**Comment by artur-trzesiok** [comment]
https://anaconda.org/conda-forge/k3d
https://pypi.org/project/K3D/

**Comment by zbouslikhin** [comment]
Thank you!
However, it looks like that the bug is still present.

**Comment by artur-trzesiok** [comment]
Please check js version 
![image](https://user-images.githubusercontent.com/5256837/84248510-d3853800-ab09-11ea-9613-4fc2b730ba4f.png)
