### ISSUE TITLE
Feature request: export as vector graphics?

### ISSUE THREAD

**Issue by rbnvrw** [K3D-tools/K3D-jupyter#231]
It is already possible to export as png or as interactive html. Is it also possible to export as a PDF or an SVG? Or another vector graphics format?
Thanks for the awesome software :+1:

**Comment by tgandor** [comment]
I'm afraid there are great obstackles to such a feature. I'll try to make it short.
Groups of reasons:
1) Target format limitations
2) Nature of the plot/scene
3) K3D specific stuff

1) SVG has some filtering features, gradients etc., raster image embedding, but it probably is still far from a WebGL canvas, and mapping the features would find many issues.

2) Only a few kinds of objects are vector-like (erm... Vectors..., lines, points maybe), but others have raster elements (textures, volumes ...).

3) Some elements in K3D are drawn with programmed pixel shaders, which produce the output using the GPU. This can be scaled, but the program needs to be executed anew.

For these reasons, the go to approach as of today is "render a raster image in a high enough resolution, and scale down if necessary (for display or print)."
