### ISSUE TITLE
text2d, update and sync

### ISSUE THREAD

**Issue by marcinofulus** [K3D-tools/K3D-jupyter#232]
In text2d, the position of text in front is not updated when backend attribute changes, e.g.: 

`plt_txt  = k3d.text2d("text in math")`

`plt_txt.position = [0.2,0.3]`

Also, is_html attribute is out of sync if new text is set, i.e. after:

`plt_txt.is_html = True`

this will change rendering on the frontend:

`plt_txt.text = 'but now?'

**Comment by artur-trzesiok** [comment]
It's already fixed on devel. Please wait for v2.9.0

**Comment by artur-trzesiok** [comment]
Please update package to K3D 2.9.0
