### ISSUE TITLE
Color legend remains after deleting "Line" type object

### ISSUE THREAD

**Issue by zbouslikhin** [K3D-tools/K3D-jupyter#234]
Hi,

- Description
While programmatically removing a marker type object containing the color legend, the marker gets successfully removed but not the color legend that stays.

- How to reproduce

1. First step
```
ploty = k3d.plot()
colormap = k3d.colormaps.matplotlib_color_maps.Inferno
plt_colormap_line = k3d.line((0, 0, 0, 5, 10, 15), 
                                         color_map=colormap, 
                                         color_range=[0, 100],
                                         name='Colormap')
ploty.display()
ploty += plt_colormap_line
```

2. Second step
`ploty -= plt_colormap_line`

Cheers,
Zaid

**Comment by artur-trzesiok** [comment]
Please update package to K3D 2.9.0
