### ISSUE TITLE
"Line" type object can't be deleted if not visible

### ISSUE THREAD

**Issue by zbouslikhin** [K3D-tools/K3D-jupyter#235]
Hi once again,

- **Description**
When say, "plt_line" is displayed then the visibility is set to **False**, the object can not be deleted until its visiblity is set back to **True**.

- **_How to reproduce_**
1. First step
```
ploty = k3d.plot()
colormap = k3d.colormaps.matplotlib_color_maps.Inferno
plt_colormap_line = k3d.line((0, 0, 0, 5, 10, 15), 
                                         color_map=colormap, 
                                         color_range=[0, 100],
                                         name='Colormap')
ploty.display()
ploty += plt_colormap_line
plt_colormap_line.visible = False
```

2. Second step
`ploty -= plt_colormap_line`

Cheers,
Zaid

**Comment by artur-trzesiok** [comment]
Please update package to K3D 2.9.0
