### ISSUE TITLE
volume rendering type problem

### ISSUE THREAD

**Issue by marcinofulus** [K3D-tools/K3D-jupyter#236]
Having:
plt0 = k3d.volume(np.random.randn(30,30,30).astype(np.float16))

this works:
plt0.volume = np.random.randn(30,30,30).astype(np.float16)

but this does not (i.e. plot is not updated):
plt0.volume = np.random.randn(30,30,30).astype(np.float32)

**Comment by artur-trzesiok** [comment]
It's already fixed on devel. Please wait for v2.9.0

**Comment by artur-trzesiok** [comment]
Please update package to K3D 2.9.0
