### ISSUE TITLE
Color legend not visible when object is hidden

### ISSUE THREAD

**Issue by zbouslikhin** [K3D-tools/K3D-jupyter#238]
Hi,

- Description
When say, "plt_line" is displayed then the visibility is set to False, the color legend also gets hidden.
I'm not sure if it's a normal behavior but I'd suggest to separate the color legend from the object (hide the object but display the color legend for instance)
- How to reproduce
```
ploty = k3d.plot()
colormap = k3d.colormaps.matplotlib_color_maps.Inferno
plt_colormap_line = k3d.line((0, 0, 0, 5, 10, 15), 
                                         color_map=colormap, 
                                         color_range=[0, 100],
                                         name='Colormap')
ploty.display()
ploty += plt_colormap_line
plt_colormap_line.visible = False
```

Cheers,
Zaid

**Comment by tgandor** [comment]
:( I guess the fixes of the colorbar behaviors have rendered my "invisible line" hack obsolete.
I'll have a look what can be done now.

**Comment by artur-trzesiok** [comment]
Latest fix change that behavior.

**Comment by artur-trzesiok** [comment]
Please update k3d to 2.9.1
