### ISSUE TITLE
Support for periodic colour maps

### ISSUE THREAD

**Issue by MaxPelly** [K3D-tools/K3D-jupyter#239]
I need to use the phase of a complex number to set a colour map for a mesh. This is a periodic quality (ie I want the colour to change continually as the phase jumps  from -pi to pi going through the the negative real line). K3D includes colour maps that are periodic (ie matplotlib twilight) which almost work except that whatever interpolation is used during shading doesn't cope well with the jump from the bottom to the top of the colour range, giving a rainbow bar as the phase is interpolated up from -pi through 0 to pi rather than "going the other way" and jumping directly from -pi to pi (see the image below, specifically the right of the (3,1,-1) wavefunction which ideally should all be the same colour). 

Is it possible to provide an option to properly interpolate over the shortest distance for periodic colour maps? Or failing this provide an option to simply disable interpolation (blocky is much better than a random bar)? Various algorithms exist for correctly interpolating over a periodic range, primarily used for interpolating angles (though changing from 0-2pi to -1 to 1 should be fairly simple. For example see the discussion [here](https://stackoverflow.com/questions/2708476/rotation-interpolation) or [here](https://gist.github.com/shaunlebron/8832585)
![K3D-1596639501838](https://user-images.githubusercontent.com/17359435/89435539-e482ac00-d73c-11ea-9dd3-4bc85d9ec20a.png)

(the original version of this was written somewhat in a hurry, sorry to any poor soul that had to read it)

**Comment by MaxPelly** [comment]
Alternatively is there a way to break the mesh along the pi to -pi discontinuity?

**Comment by artur-trzesiok** [comment]
You can workaround the problem with vertices duplication:

`import k3d
import numpy as np

N = 100

theta = np.linspace(0, 2.0 * np.pi, N)
phi = np.linspace(0, 2.0 * np.pi, N)
theta, phi = np.meshgrid(theta, phi)

c, a = 2, 1
x = (c + a * np.cos(theta)) * np.cos(phi)
y = (c + a * np.cos(theta)) * np.sin(phi)
z = a * np.sin(theta)

vertices = np.dstack([x, y, z])
indices = np.stack([
    np.arange(N*N) + 0, np.arange(N*N) + N, np.arange(N*N) + N + 1,
    np.arange(N*N) + 0, np.arange(N*N) + N + 1, np.arange(N*N) + 1
]).T % (N * N)

plot = k3d.plot()
plot += k3d.points(vertices, point_size=0.05, shader='3d', color=0)
plot += k3d.mesh(vertices, indices, flat_shading=False, 
                 attribute=phi,
                 color_map=k3d.matplotlib_color_maps.twilight)
plot.display()`

![K3D-1610375255484](https://user-images.githubusercontent.com/5256837/104194399-94152600-5421-11eb-8d64-f78f1b234c7c.png)

I will check how hard will be to add another strategies

**Comment by MaxPelly** [comment]
Thank you, I ended up just chopping my objects in half to avoid cross overs, but this is probably more straight forward.

**Comment by artur-trzesiok** [comment]
I analysed it. Periodic shader seems to be very tricky because pixel shader alreade get interpolated value and vertex shader dosen't have information about neighbours. I think we should leave a solution with vertices duplication
