### ISSUE TITLE
Use xor method for decrease transfer rate during array update

### ISSUE THREAD

**Issue by artur-trzesiok** [K3D-tools/K3D-jupyter#24]

**Comment by tgandor** [comment]
In current situation (development branch, after #44) this would be best done as an improvement to the `ipywidgets` library - as a feature of the traitlets synchronization protocol.

After moving to traitlets, we got clean code and robust async communication, but we lost:
- compression of the payload
- low-level control over the communication.

The latter is needed to implement such an improvement.

I am assigning @artur-trzesiok to weigh in on this issue - is my thinking correct in this regard?

**Comment by vidartf** [comment]
As far as I remember  (on mobile now), notebook messages support compression (as a notebook server setting). I'm not sure how well documented this is, or which versions this is, but I'll investigate next week when I'm back.
