### ISSUE TITLE
Clipped axes indicators

### ISSUE THREAD

**Issue by ahulist** [K3D-tools/K3D-jupyter#242]
Axes indicator is affected by the `FOV` parameter causing it to be too big (and effectively cut off) when the `FOV` is low
![image](https://user-images.githubusercontent.com/1991429/92920464-985d1280-f432-11ea-89c9-335702e7dbfe.png)
and too small when the `FOV` is high.

IMO axis indicator should be `FOV` independent.

**Comment by artur-trzesiok** [comment]
Thanks. FOV independent looks strange because leads to missunderstood of axis orientantion.

**Comment by artur-trzesiok** [comment]
Will be improved in next release
