### ISSUE TITLE
Label affecting grid

### ISSUE THREAD

**Issue by ahulist** [K3D-tools/K3D-jupyter#243]
```
import k3d
from chunky3d import Sparse
from chunky3d.k3d_connector import get_k3d_obj

p = k3d.plot()
s = Sparse((50,50,50), origin=(-0.01, -0.2, -0.7), spacing=(0.0002, 0.0002, 0.0002))
s[25:36,25:36,25:36] = 1
p += get_k3d_obj(s)

p.display()
```
The above code renders a cube, everything is fine by now:
![image](https://user-images.githubusercontent.com/1991429/92922209-bd9f5000-f435-11ea-9baa-0a7dae47220e.png)

But the following code causes the grid size to change:
```
x,y,z = np.array(s.origin) + np.array([24,24,24]) * np.array(s.spacing)
l = k3d.label('abc', position=(x,y,z), color=0xff0000, size=1, name='label')
p += l
```
![image](https://user-images.githubusercontent.com/1991429/92922290-e32c5980-f435-11ea-98ea-e9d96a25f2d2.png)

Even though `size` parameter is supposed to affect the font size only.

**Comment by artur-trzesiok** [comment]
Will be fixed in next release
