### ISSUE TITLE
Fixing Polar angle when rotating?

### ISSUE THREAD

**Issue by panangam** [K3D-tools/K3D-jupyter#244]
Is it possible to lock the polar angle for the plot rotation, so we only change the azimuth angle? In other words, can I fix the rotation to only around Z-axis? Or is there a way to set the rotation so that one up direction stays up?

**Comment by artur-trzesiok** [comment]
Hi,

We had plot.camera_no_rotate, plot.camera_no_zoom and plot.camera_no_pan . But probably orbit controls will help you:
![image](https://user-images.githubusercontent.com/5256837/93591472-beddf900-f9b0-11ea-830c-b6caf32f7f71.png)

Please check also example from three.js: https://threejs.org/examples/?q=controls#misc_controls_orbit

**Comment by panangam** [comment]
Orbit camera mode looks quite promising! I haven't updated in a while so didn't have that feature. 

OrbitControls does have exactly the parameter that I need: https://threejs.org/docs/index.html#examples/en/controls/OrbitControls.minPolarAngle

Is K3D using OrbitControls? Is there a recommended way to affect the underlying threejs stuff from the Python side?

**Comment by panangam** [comment]
Just found the `Plot.camera_mode` trait and setting it to `orbit` works perfectly for me! I could not find this in the documentation, though it also seems the doc was for version 2.7.

https://k3d-jupyter.org/k3d.html?highlight=mode#k3d.plot.Plot

Gonna keep this open for a bit because I'm still curious if there's a way for more fine-tuned control over the underlying js code.

**Comment by Dario-Mantegazza** [comment]
> Just found the `Plot.camera_mode` trait and setting it to `orbit` works perfectly for me! I could not find this in the documentation, though it also seems the doc was for version 2.7.
> 
> https://k3d-jupyter.org/k3d.html?highlight=mode#k3d.plot.Plot
> 
> Gonna keep this open for a bit because I'm still curious if there's a way for more fine-tuned control over the underlying js code.

Actually the link you put here do not refer to the camera mode. The docs (https://k3d-jupyter.org) are still at the version 2.7 while the lib is at the version 2.9.
@artur-trzesiok could you update the documentation or at least include this change?
Thanks for the otherwise great work
:)

**Comment by artur-trzesiok** [comment]
@Dario-Mantegazza good spot thanks for that! I already updated docs.
@panangam Yes K3D use OrbitControls. Direct access to js code is not allowed but we can expose some parameters. I assume that you have requirement to control minPolarAngle/maxPolarAngle?

**Comment by ea42gh** [comment]
Could you provide an example using it?
I have not been able to get it to work...

**Comment by artur-trzesiok** [comment]
@ea42gh sorry for long delay. Did you manage to solve this problem?

**Comment by ea42gh** [comment]
Unfortunately, no.

I had used pyviz panel to provide a nice k3d example
https://discourse.holoviz.org/t/panel-meets-k3d-jupyter/1604
but could not get rotation to work other than by providing a slider...
