### ISSUE TITLE
Orbit camera doesn't rotate in detached window

### ISSUE THREAD

**Issue by elor** [K3D-tools/K3D-jupyter#247]
Issue:
* Camera rotation doesn't work in a detached window when in 'orbit' mode.
* Camera rotates when starting a click-and-drag sequence in the detached and hovering over the jupyter window
* Default camera mode works as expected
* See video:
![k3d_camera](https://user-images.githubusercontent.com/921731/96851502-6212aa00-1458-11eb-9415-7bee0e5f431f.gif)

Expected behavior:
* Camera rotates when dragging cursor in detached window

Reproduction:
```
import k3d, numpy as np
plot = k3d.plot(camera_mode='orbit')
plot += k3d.points(np.random.random((100,3)).astype(np.float32), point_size=0.1)
plot.display()
```

Versions:
* k3d 2.9.0
* jupyter 
* Browser: Chrome 85.0.4183.102 (64bit, Windows 10)
* Jupyter:
```
jupyter core     : 4.6.3
jupyter-notebook : 6.1.4
qtconsole        : 4.7.7
ipython          : 5.8.0
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : not installed
nbconvert        : 6.0.7
ipywidgets       : 7.5.1
nbformat         : 5.0.8
traitlets        : 5.0.5
```
* installed via conda, from conda-forge

Assumption:
* hover event for orbit camera is caught in wrong window?

**Comment by artur-trzesiok** [comment]
Good spot and assumption. Threejs Orbit  by default handle "window". I will modify that

**Comment by artur-trzesiok** [comment]
Will be fixed in next release.

**Comment by artur-trzesiok** [comment]
Please update k3d to 2.9.1
