### ISSUE TITLE
Export K3D plot in a color file obj or ply 

### ISSUE THREAD

**Issue by MarlNox** [K3D-tools/K3D-jupyter#248]
Hi there, 

I was wondering, that if one has the the HTML code generated from K3D-jupyter, is there any method to export the cloud points along with the colors/texture as displayed on the page into ply or obj? 
Any other methods to obtain a colored object file from K3D?

Thanks

**Comment by artur-trzesiok** [comment]
K3D by definition is a viewer software. I see potential extension (aka k3d helper) that will add that feature but this is not high priority right now for package. I'm open for pull request.

**Comment by alainlhostis** [comment]
i am contemplating using k3d for three d modelling  In my situation an export function into OBJ file is a requisite
