### ISSUE TITLE
Critical Security Vulnerabilities in NPM Packages/Build Process

### ISSUE THREAD

**Issue by danieldjewell** [K3D-tools/K3D-jupyter#252]
As of now, npm automatically reports: 

```found 112 vulnerabilities (45 low, 11 moderate, 54 high, 2 critical)```

in the npm modules used when building via setup.py... 

I'm not sure whether or how this might impact generated code, but this needs some attention.

**Comment by artur-trzesiok** [comment]
Thanks. npm audit found most of problems in tests code not in production one. But still - it a good excuse to bump our dependencies a little bit. I will do it.

**Comment by artur-trzesiok** [comment]
https://github.com/K3D-tools/K3D-jupyter/commit/7751b99d5ed6c8770f4c27f97525b90c8b382f53
