### ISSUE TITLE
It's now possible to use K3D-jupyter to create awesome analytics apps using HoloViz Panel

### ISSUE THREAD

**Issue by MarcSkovMadsen** [K3D-tools/K3D-jupyter#253]
Just wanted to share the information that it is now possible to use K3D-jupyter with Holoviz Panel.

A user just showcased how in the community forum https://discourse.holoviz.org/t/panel-meets-k3d-jupyter/1604

https://user-images.githubusercontent.com/42288570/102853790-4fe5c580-4421-11eb-9c43-8072493abdf3.mp4

If you want to learn more checkout [Panel](https://panel.holoviz.org), [HoloViz](https://holoviz.org) and [awesome-panel](https://awesome-panel.org).

**Comment by artur-trzesiok** [comment]
Nice! Thanks a lot for sharing!
