### ISSUE TITLE
k3d with bokeh server problems

### ISSUE THREAD

**Issue by ea42gh** [K3D-tools/K3D-jupyter#254]
I have a jupyter notebook using pyviz panel to display a k3b plot. The notebook is in
[https://gitlab.com/ea42gh/elementary-linear-algebra/-/blob/master/QuadricSurfaceDisplay.ipynb](https://gitlab.com/ea42gh/elementary-linear-algebra/-/blob/master/QuadricSurfaceDisplay.ipynb)
and works as intended.

Panel allows serving the notebook with the bokeh server:
`panel serve QuadricSurfaceDisplay.ipynb`

This does not work:
- with Chromium, the error shown in the console is `ipywidgets_bokeh.js:1 TypeError: Cannot read property resizeHelper of undefined
    at r.handleResize (k3d.js:563)`
- with Firefox, I get `Uncaught ReferenceError: requirejs is not defined`

**Comment by artur-trzesiok** [comment]
First of all - I recommend to disable menu:
`plot = k3d.plot(menu_visibility=False)`

Please wait for a next release

**Comment by artur-trzesiok** [comment]
Bokeh have problem with serializing a model for plot. Not all parameters are stored  Probably something around:
https://github.com/bokeh/bokeh/blob/main/bokeh/embed/util.py#L333

**Comment by artur-trzesiok** [comment]
I fixed one bug and another one appear. I think that that will be too long road to run it
