### ISSUE TITLE
Sensitivity to mouse movement

### ISSUE THREAD

**Issue by ipcoder** [K3D-tools/K3D-jupyter#256]
Can it be tuned to make view change more sensitive to mouse motion?

**Comment by artur-trzesiok** [comment]
We had hardcoded variables:

```
this.rotateSpeed = 1.0;
this.zoomSpeed = 1.2;
this.panSpeed = 0.3;
```

I can expose them to plot (like plot.camera_no_rotate or plot.camera_no_zoom or plot.camera_no_pan)

I think about names: plot.camera_rotate_speed, plot.camera_zoom_speed, plot.camera_pan_speed. But I will resign from adding it to GUI side. 

Does that work for you?

**Comment by ipcoder** [comment]
Thanks, it looks quite enough to me.

**Comment by artur-trzesiok** [comment]
Done. Please look forward for next release :)

**Comment by ipcoder** [comment]
Awesome, thanks!
