### ISSUE TITLE
Screenshots do not match view in 2.9.1

### ISSUE THREAD

**Issue by mironvanderkolk** [K3D-tools/K3D-jupyter#257]
Screenshots generated by k3d (clicking the screenshot button in the controls), do not match the currently displayed view. The rendering order seems to be wrong:

Code to generate plot:
```
import k3d
import ipywidgets as widgets
import numpy as np

out = widgets.Output(layout={'width': '500px', 'height': '500px'})
plot = k3d.plot(height=500, camera_auto_fit=False, grid_auto_fit=False, screenshot_scale=1.0, auto_rendering=True)
plot += k3d.points(np.random.rand(100, 3))
with out:
    plot.display()
out
```

Result in k3d 2.8.2 (view on the left, generated screenshot on the right):
![k3d_282](https://user-images.githubusercontent.com/56925246/104921666-ee6e3380-5999-11eb-98cc-5ee0c7892e34.png)

Result in k3d 2.9.1 (view on the left, generated screenshot on the right):
![k3d_291](https://user-images.githubusercontent.com/56925246/104921724-faf28c00-5999-11eb-8016-2fd76b005f4d.png)

I also noticed in both version that the grid is displayed differently, but this is not too much of an issue.

**Comment by artur-trzesiok** [comment]
To be sure - do you mean  wrong orders in layering? (numbers from grid are on top of 3d object in screenshot)
I will try to fix that (and also grid view - it's all about opacity on screenshot)

**Comment by artur-trzesiok** [comment]
Should be fixed in next release

**Comment by mironvanderkolk** [comment]
Ah just to make it more clear I added some colors, it is also the drawing order of the circle along the view axis that changes:

![k3d_291_colors](https://user-images.githubusercontent.com/56925246/105008259-46a84280-5a39-11eb-93d6-32cbf2550a57.png)

Again the generated screenshot on the right, original view on the left. You can see for example that the pink sphere is covered by the blue and gold sphere in the screenshot, while it the original view it is more in front

**Comment by artur-trzesiok** [comment]
This is a problem related to points with "billboard" optimization  (ex. https://forum.unity.com/threads/z-sorting-of-billboard-sprites-in-3d-space-stop-tall-sprites-intersecting-with-walls.290432/). The easiest way to fixed it is:
```
k3d.points(np.random.rand(100, 3), shader='mesh')
```

**Comment by mironvanderkolk** [comment]
Did a similar comparison with the mesh shader, problems about ordering seem to persist

![k3d_291_mesh](https://user-images.githubusercontent.com/56925246/105062813-4e88d680-5a7b-11eb-9d58-a14d35347424.png)

**Comment by mironvanderkolk** [comment]
After upgrading to k3d 2.9.6, I have found this problem still exists:

![k3d_comparison_2 9 6](https://user-images.githubusercontent.com/56925246/123809188-b0cee880-d8f1-11eb-838c-a656e4a22cef.png)

On the left side is the view after generating a screenshot from the contex menu. The right side is a manual screenshot for the view in jupyterlab. The intersection between the two spheres in rendered incorrectly in the generated screenshot.

Code to reproduce:
```
import k3d
import numpy as np
k3d.points(np.array([[1.0, 1.0, 0.5], [0.75, 1.0, 0.5]]), shader='3d', colors=[int('FF0000', 16), int('0000FF', 16)])
```
