### ISSUE TITLE
Python part refactor 

### ISSUE THREAD

**Issue by artur-trzesiok** [K3D-tools/K3D-jupyter#26]
validation of arraylike parameters

**Comment by tgandor** [comment]
I propose to close this issue.

After the many changes in version 2.1 most of the Python code got refactored.

There are very minor warnings from the IDE:

1. Shadowing of global names by arguments (`def voxels(voxels, ...):`) - we should ignore this one probably. The convention is like this:
`foo = k3d.foo(bar=<initial value>)
foo.bar = <assigned_value>`, and in some cases `foo` and `bar` are the same identifier.

2. Using lists (i.e. mutable type) as default values (grid, point positions etc.) - currently there's no risk, but generally if this is passed further down it might get modified, changing the "default value".

Other changes will be maybe removing `xmin`, `xmax` etc. arguments can be done with #41 (make it a part of transform, maybe as `base_matrix`).

Do you agree to close this?

**Comment by artur-trzesiok** [comment]
I think that during this task we can add more:

1. docstrings should be added
2. Study why we need both "jupyter nbextension enable" and "jupyter nbextension install" (compare with https://github.com/jupyter-widgets/ipywidgets#install)
3. Clean up array_to_binary_or_json to remove legacy json format in case of binary data.

**Comment by artur-trzesiok** [comment]
I think we should close this issue. @marcinofulus what do you think?
