### ISSUE TITLE
Mesh vertex color

### ISSUE THREAD

**Issue by cheng-chi** [K3D-tools/K3D-jupyter#261]
Is there a way to directly display per-vertex RGB color with mesh?

**Comment by artur-trzesiok** [comment]
https://github.com/K3D-tools/K3D-jupyter/blob/devel/examples/mesh_custom.ipynb

**Comment by artur-trzesiok** [comment]
![image](https://user-images.githubusercontent.com/5256837/107296587-fa698480-6a71-11eb-802a-5262604c839b.png)

**Comment by cheng-chi** [comment]
@artur-trzesiok Thanks!

**Comment by artur-trzesiok** [comment]
Wait for next release!
