### ISSUE TITLE
“Error displaying widget: model not found” with Jupyter Lab

### ISSUE THREAD

**Issue by jessesna** [K3D-tools/K3D-jupyter#265]
I followed the pip installation instructions but get _“Error displaying widget: model not found”_ in the lab. In the notebook it works fine.
I tried to reinstall everything related but couldn't get it to work. Is this a known issue?

Here are the version infos:
```
D:\dev>jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 6.2.0
qtconsole        : 5.0.2
ipython          : 7.20.0
ipykernel        : 5.4.3
jupyter client   : 6.1.11
jupyter lab      : 3.0.7
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.2
traitlets        : 5.0.5

D:\dev>jupyter nbextension list
Known nbextensions:
  config dir: c:\prog\python39\etc\jupyter\nbconfig
    notebook section
      jupyter-datawidgets/extension enabled
      - Validating: problems found:
        - require?  X jupyter-datawidgets/extension
      jupyter-matplotlib/extension enabled
      - Validating: ok
      k3d/extension enabled
      - Validating: ok
      jupyter-js-widgets/extension enabled
      - Validating: ok

D:\dev>jupyter nbextension list
Known nbextensions:
  config dir: c:\prog\python39\etc\jupyter\nbconfig
    notebook section
      jupyter-datawidgets/extension enabled
      - Validating: problems found:
        - require?  X jupyter-datawidgets/extension
      jupyter-matplotlib/extension enabled
      - Validating: ok
      k3d/extension enabled
      - Validating: ok
      jupyter-js-widgets/extension enabled
      - Validating: ok

D:\dev>jupyter labextension list
JupyterLab v3.0.7
        jupyter-matplotlib v0.8.3 enabled ok
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled ok (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
        jupyterlab-datawidgets v7.0.0 enabled ok
        k3d v2.9.3 enabled ok

Uninstalled core extensions:
    @jupyter-widgets/jupyterlab-manager
    k3d

D:\dev>node --version
v14.15.5
```

**Comment by abcdehc** [comment]
I encountered the same problem, i thouth the module does not support jupyterlab 3.x

**Comment by CagtayFabry** [comment]
are there any plans to update the extension to the new JupyterLab 3.x extension system?
https://jupyterlab.readthedocs.io/en/stable/extension/extension_migration.html

This would also simplify installation for users

**Comment by artur-trzesiok** [comment]
Hi!

I would like to restart the topic. Today I test many times k3d at jupyter lab 3.1.4 and everything works like a charm. Do somebody still have problem with configuration?

**Comment by krassowski** [comment]
Hi @artur-trzesiok, I guess this is not about mere compatibility but about utilising the prebuilt extensions mechanism.
JupyterLab 3+ allows to ship prebuilt extensions with other Python packages (or really any other distribution system for any language) which has multiple benefits for the end users:
- one installation step less (no need for `jupyter labextension install`)
- much faster installation (no need for the build step)
- no need for installing Node.js in the first place

In other words users should be able to just `pip install k3d` (or `conda install`) and have it working in JupyterLab 3+ without any extra steps. This is what we recommend in the documentation [here](https://jupyterlab.readthedocs.io/en/stable/extension/extension_migration.html#publishing-the-extension-to-pypi-and-conda-forge) and [here](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#overview-of-extensions). Most other extensions already made the switch, including the big ones like plotly, which was very warmly welcomed by the users.

If you get stuck with the transition or wonder where to start feel free to ping me on GitHub or gitter.

**Comment by artur-trzesiok** [comment]
@krassowski thanks a lot for a hint. I will try to do that. Sorry that this is still not handled properly - I'm better in shaders and webgl than jupyter ecosystem. I'm glad from your willingness to help.

**Comment by cignoni** [comment]
Hi, I am facing the "Error displaying widget: model not found" problem. 
After a osx upgrade (to Monterey 12.0.1) and a brew update of all the bottle k3d stopped working. 
Tried to uninstall jupyterlab and doing minimally needed install: _jupyterlab_ with brew,  _k3d_ and _plotly_ with pip and the two _labextensions_ via jupiter as indicated in the documentation:
```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install k3d
```
After all these install the current configuration seems ok and is:
```
% jupyter --version
Selected Jupyter core packages...
IPython          : 7.29.0
ipykernel        : 6.5.0
ipywidgets       : 7.6.5
jupyter_client   : 7.0.6
jupyter_core     : 4.9.1
jupyter_server   : 1.11.2
jupyterlab       : 3.2.1
nbclient         : 0.5.4
nbconvert        : 6.2.0
nbformat         : 5.1.3
notebook         : 6.4.5
qtconsole        : not installed
traitlets        : 5.1.1

% jupyter nbextension list
Known nbextensions:
  config dir: /Users/cignoni/.jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
  config dir: /usr/local/etc/jupyter/nbconfig
    notebook section
      jupyterlab-plotly/extension  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
    
% jupyter labextension list
JupyterLab v3.2.1
/usr/local/share/jupyter/labextensions
        @jupyter-widgets/jupyterlab-manager v3.0.1 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /usr/local/share/jupyter/lab
        k3d v2.11.0 enabled OK

```
Unfortunately this has not helped. As shown below the k3d minimal example results in a "Error displaying widget: model not found" while other widgets, like plotly, work fine.
Any Hints?


![Screenshot 2021-11-04 at 16 50 16 PM](https://user-images.githubusercontent.com/8055819/140371291-f4a74106-208b-4133-84ef-1449915798c3.png)

**Comment by CagtayFabry** [comment]
with jupyterlab >=3 and k3d >=2.11 you schould not need to manually install the labextension any longer (though I cant test with OSX)

can you try simply skipping this step:
```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install k3d
```

**Comment by cignoni** [comment]
Actually, after installing k3d and plotly with pip I started jupyter-lab and tested the sample with the same result. 

But from my very shallow understanding of the internal of jupyterlab >=3, the "jupyter labextension install" should be in this case harmless (from what I understood since jupyterlab >=3 these steps are automatically done after the pip install)

Do you have any suggestion about configuration checking to understand what could have gone wrong?

**Comment by krassowski** [comment]
> from what I understood since jupyterlab >=3 these steps are automatically done after the pip install

No, this is not the case; the internal installation process is very different for the prebuilt (`pip install` among others) and source extensions (`jupyter labextension install`); `jupyter labextension install` required a node.js to be installed (a huge dependency) and a compilation step; it is likely going away soon, so if you spot an instruction mentioning it please consider updating it to use the prebuilt extension instructions.

Moreover, it can be harmful because if you do `jupyter labextension install` in addition to the prebuilt extension you can end up with two conflicting versions, or a broken build (if the source version was not updated or had incorrectly specified version ranges).

**Comment by cignoni** [comment]
Ok, great! My understanding was even more shallow than I thought 😄 
So it is actually harmful! 
I will try to uninstall jupyterlab and all pip installed stuff via 

```
pip freeze | xargs pip uninstall -y
brew uninstall jupyterlab
```

Trivial question is better to install jupyterlab via pip or via brew?

**Comment by CagtayFabry** [comment]
if you can I would try a fresh install only using pip (or ideally conda if that is an option) but I can't offer any specifics for OSX

**Comment by cignoni** [comment]
Thanks again for the help! 
So after uninstalling as described above I used only pip. Installing k3d after jupyterlab with pip this time resulted in an error: 

```
% pip install k3d
...
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/usr/local/k3d'
Consider using the `--user` option or check the permissions.
```
So I tried with the --user option and it went smooth. 
started again jupyter-lab and it requested to "build", I let it build and after, again sadly the same 'model not found' error... (and also the plotly stuff was not installed, but that was expected
![Screenshot 2021-11-04 at 17 43 22 PM](https://user-images.githubusercontent.com/8055819/140382180-a6ff7db8-58e3-45d5-9a5e-3af63d130db0.png)
)

**Comment by krassowski** [comment]
It looks like you have a global installation but tried to install extra packages while running JupyterLab as a normal user, not as a super user/administrator. You need to adjust the privileges of the folder you installed into, or run JupyterLab as a super user (usually not recommended), or reinstall in a location accessible by the normal user.

**Comment by tgandor** [comment]
This discussion is very advanced; but what about using, e.g., a virtualenv (or poetry etc.) -- i.e., having everything (lab, k3d, plotly...) in a custom location (and nothing system-wide)?

I remember that with notebook it was not that great (still scans `$HOME` dotfiles for jupyter configuration, and extensions could clash...).

It seems worth a try.

**Comment by cignoni** [comment]
I think that I have done the unforgivable mistake of not using isolated python environment. As hinted above the user vs admin conflict raised during the pip installation is a red flag to be investigated 
I will try to deep clean the python environment, switch to pyenv and try again...

**Comment by cignoni** [comment]
After a quick cleanup of installed pythons (uninstalled all pip packages and removed all python brew casks, I started to use pyenv and this time I installed jupyterlab and k3d only locally and everything worked. Thanks for suggesting that the local global clash could be the source of all the evil... 

Just for future memory this worked for me:
```
brew install pyenv
echo 'eval "$(pyenv init --path)"' >> ~/.zprofile\n
pyenv install 3.9.7
cd mypythonexperiments
pyenv local 3.9.7
pip install jupyterlab
pip install k3d
jupyter-lab
```
So I can continue to play with pymeshlab using k3d as viewer...

![Screenshot 2021-11-08 at 0 44 18 AM](https://user-images.githubusercontent.com/8055819/140666653-9881a94e-a912-491f-949e-7f844601cb8a.png)

Thanks again!!
