### ISSUE TITLE
Snapshot does not work in 2.9.3

### ISSUE THREAD

**Issue by marcinofulus** [K3D-tools/K3D-jupyter#266]
It is due to two lines:

https://github.com/K3D-tools/K3D-jupyter/blob/9c7f1e9ff7a5b7fcc3ffb09d2c08bec4fabb51bb/k3d/plot.py#L384

but instead of removing them, perhaps adding sliceviewer would work better ;-)

**Comment by artur-trzesiok** [comment]
Thanks a lot.

**Comment by artur-trzesiok** [comment]
v2.9.4 is on pypi and conda-forge. Please update your k3d and check if it works.
