### ISSUE TITLE
Click and hover callbacks not working

### ISSUE THREAD

**Issue by dneuhof** [K3D-tools/K3D-jupyter#267]
Nothing happens when using the click and hover callbacks shown in the example notebooks: `examples/labels.ipynb` and `examples/voxel_callback.ipynb`.
I get these errors in the Console:
![image](https://user-images.githubusercontent.com/20907755/107878179-87c93080-6ed9-11eb-9e39-94cae4261772.png)

K3D version: 2.9.3
Jupyter versions:
```
jupyter core     : 4.7.1
jupyter-notebook : 6.2.0
qtconsole        : not installed
ipython          : 7.20.0
ipykernel        : 5.4.3
jupyter client   : 6.1.11
jupyter lab      : 2.2.9
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.2
traitlets        : 5.0.5
```

**Comment by artur-trzesiok** [comment]
Bump three-mesh-bvh to 0.3.7 will help. Please wait for new release.

**Comment by artur-trzesiok** [comment]
v2.9.4 is on pypi and conda-forge. Please update your k3d and check if it works.
