### ISSUE TITLE
Non-uniformly spaced Marching Cubes?

### ISSUE THREAD

**Issue by TomNicholas** [K3D-tools/K3D-jupyter#269]
I have a dataset on a rectilinear grid, but the real-space positions of the data points are not evenly spaced. (i.e. z=[1m, 2m, 5m, 10m, 20m...]) I would like to plot an isosurface of this data with `marching_cubes`, but that function assumes that my data is evenly-spaced. Is there an easy way to do this? Perhaps by scaling the data? Or do I need some kind of "marching-cuboids" method?

(@jbusecke)

**Comment by tgandor** [comment]
Hi Tom. What do you mean by not evenly spaced? Is the spacing even in x-, y-, z-dimension, but with different spacing? Or is it a random collection of points with associated potential values?

If it's the case with uneven spacing, you can pretend that it's even, and then scale the result unevenly.

In the second case you can interpolate the values onto an even grid, and then run marching cubes. Of course, the regular, but uneven grid could also be interpolated / resampled onto a grid, but uneven scaling saves you the data transformation.

**Comment by TomNicholas** [comment]
Thanks @tgandor . Sorry, I mean we have a rectilinear grid, so it's not a random collection of points, but along a particular dimension the step size is not equal in real space (and we want our plot to look like real space). Specifically we have latitude and longitude, and then height vertically through the ocean, where the top layers of the ocean are sampled much more regularly than the bottom layers.

My understanding of the docstring was that I can only use marching_cubes for constant step size? Obviously I would rather not interpolate if I can avoid it.

**Comment by artur-trzesiok** [comment]
@TomNicholas thanks for your question. MarchingCubes in K3D is computed on frontend. Do you really need it? Maybe you can computer that kind of isosurface in vtk and end to k3d as polydata (k3d.vtk_poly_data() or k3d.mesh())?

**Comment by artur-trzesiok** [comment]
![image](https://user-images.githubusercontent.com/5256837/113225051-06610e00-928d-11eb-806a-b97c96e7701d.png)

**Comment by artur-trzesiok** [comment]
```
import k3d
import numpy as np
from numpy import sin,cos,pi
from ipywidgets import interact, interactive, fixed
import ipywidgets as widgets
import time
import math

plot = k3d.plot()

T = 1.618033988749895
r = 4.77
zmin,zmax = -r,r
xmin,xmax = -r,r
ymin,ymax = -r,r
Nx,Ny,Nz = 77,77,77

x = np.linspace(xmin,xmax,Nx)
y = np.linspace(ymin,ymax,Ny)
z = np.linspace(zmin,zmax,Nz)
x,y,z = np.meshgrid(x,y,z,indexing='ij')
p = 2 - (cos(x + T*y) + cos(x - T*y) + cos(y + T*z) + cos(y - T*z) + cos(z - T*x) + cos(z + T*x)).astype(np.float32)

iso = k3d.marching_cubes(p, level=0.0, color=k3d.nice_colors[0], bounds=[xmin, xmax, ymin, ymax, zmin, zmax])

plot += iso
plot.display()

iso.opacity = 0.7
ax = np.logspace(0, np.log10(xmax - xmin + 1), Nx, endpoint=True) + xmin - 1
ay = np.logspace(0, np.log10(ymax - ymin + 1), Nx, endpoint=True) + ymin - 1
az = np.logspace(0, np.log10(zmax - zmin + 1), Nx, endpoint=True) + zmin - 1

x,y,z = np.meshgrid(ax,ay,az,indexing='ij')
p = 2 - (cos(x + T*y) + cos(x - T*y) + cos(y + T*z) + cos(y - T*z) + cos(z - T*x) + cos(z + T*x)).astype(np.float32)

iso2 = k3d.marching_cubes(p, level=0.0, color=1,
                          spacings_x=(ax[1:] - ax[:-1]).astype(np.float32),
                          spacings_y=(ay[1:] - ay[:-1]).astype(np.float32),
                          spacings_z=(az[1:] - ay[:-1]).astype(np.float32),
                          bounds=[xmin, xmax, ymin, ymax, zmin, zmax],
                          opacity=0.15,
                          wireframe=True)
plot += iso2
```

Something like this?

**Comment by artur-trzesiok** [comment]
Please check https://github.com/K3D-tools/K3D-jupyter/blob/master/examples/marching_cubes_non_uniformly_spaced.ipynb

**Comment by artur-trzesiok** [comment]
v2.9.4 is on pypi and conda-forge. Please update your k3d and check if it works.

**Comment by TomNicholas** [comment]
This is great thank you @artur-trzesiok ! I tried your example with v2.9.4 which worked, and I think I got it working with my oceanographic data too (see in the attached image the levels are more closely spaced at the surface at the top than at the bottom). This saves us an expensive interpolation.

![Screenshot from 2021-04-12 16-44-40](https://user-images.githubusercontent.com/35968931/114459701-de3bae00-9bae-11eb-9d69-e04a0fa8c9a7.png)

**Comment by jbusecke** [comment]
I just quickly wanted to say thanks as well @artur-trzesiok. This helps me tremendously with my data!
