### ISSUE TITLE
Add Text2dViewport support

### ISSUE THREAD

**Issue by artur-trzesiok** [K3D-tools/K3D-jupyter#27]

**Comment by marcinofulus** [comment]
perhaps: text, text2d names are fine - text2d can take position (x,y,z) or (x,y) and the latter will make immovable text in viewport coordinates (perhaps 0..1 ?)

**Comment by artur-trzesiok** [comment]
Viewport coordinates are not fixed. When you detach K3D you can adjust size of window dynamically. So what kind of strategy we should take here? Map window coord to [0,1] ?

In that case we will had different axis meaning. Thats why I would recommend adding a new type of object instead overloading the current one.

**Comment by marcinofulus** [comment]
1.Map window coord to [0,1]
2. new type is ok
