### ISSUE TITLE
Support rendering cell attributes

### ISSUE THREAD

**Issue by esalehim** [K3D-tools/K3D-jupyter#270]
A far as I understand, k3d only supports vertex attributes. but in many cases we have simulation results assigned to cells rather than points/vertices. one solution would be to convert cell data to point data but its not always straightforward. It would be nice to add support for rendering cell attributes as well. Thanks

**Comment by artur-trzesiok** [comment]
I agree. Thanks for your idea

**Comment by artur-trzesiok** [comment]
Please check https://github.com/K3D-tools/K3D-jupyter/blob/master/examples/mesh_triangles_attribute.ipynb and https://github.com/K3D-tools/K3D-jupyter/blob/master/examples/mesh_triangles_attribute_vtk.ipynb

**Comment by artur-trzesiok** [comment]
v2.9.4 is on pypi and conda-forge. Please update your k3d and check if it works.

**Comment by esalehim** [comment]
works like a charm! Thanks a lot

**Comment by spanag** [comment]
Note: The current implementation cuts down meshes into triangles and saves one value per triangle. In case the "cells" include *many* triangles (~100 in my case), these modified functions can compress data further to one per abstract cell: [k3d_enhancements.js]( https://gitlab.com/c7859/neurocomputing-lab/Inferior_OliveEMC/eden/-/blob/906bd075015bda6030dbb2e3d9c04aca010fc2f2/testing/python_package/eden_simulator/display/spatial/k3d_enhancements.js#L155-L384 ) [compress_cells]( https://gitlab.com/c7859/neurocomputing-lab/Inferior_OliveEMC/eden/-/blob/906bd075015bda6030dbb2e3d9c04aca010fc2f2/testing/python_package/eden_simulator/display/spatial/k3d.py#L199-L212 )
