### ISSUE TITLE
Grid line colors

### ISSUE THREAD

**Issue by Davide-sd** [K3D-tools/K3D-jupyter#271]
I've seen it is possible to change the `background_color` of the plot but, as far as I know, it is not possible to directly change the grid lines color from the Python side. Is it possible to somehow access the Threejs backend to customize the look further?

**Comment by artur-trzesiok** [comment]
Sure we can!

**Comment by artur-trzesiok** [comment]
![image](https://user-images.githubusercontent.com/5256837/114730626-00cef200-9d7c-11eb-8930-4be98f781f6e.png)
Expect that feature in next release!

**Comment by Davide-sd** [comment]
@artur-trzesiok Thank you for the quick response! :)

My goal was to try a dark background color, with light color grids in order to blend the plot in my Jupyter notebook dark theme. In that regards, it would be helpful to change the labels color. I know it is possible to set color for texts. What about the grid labels, axis labels, the "orienter" labels?

Again, thank you for the hard work! :)

**Comment by artur-trzesiok** [comment]
@Davide-sd K3D 2.9.5 is released (for now on PyPi, we are waiting for conda-forge). If you can please check out the new version and test if what we wrote about here works. Thanks!
