### ISSUE TITLE
Issues with Voila

### ISSUE THREAD

**Issue by esalehim** [K3D-tools/K3D-jupyter#274]
Anyone has ever tried deploying k3d with voila?

Although the component is working just fine in a jupyter notebook, it shows some problems when running on voila. Notably some parameters seem to be out of sync with server side. For example,  when I set the plot mode to `'callback'` in the code, it is not reflected in the front-end (I have to change the mode from the left menu)

Any ideas what might cause this inconsistency?!

**Comment by marcinofulus** [comment]
Yes, there is known behaviour that the plot callback setting works only when  plot object exists in the front end. In voile my workaround for now  could be to make a button with callback on_click "Start interacting" with plot.mode='callback' inside.
