### ISSUE TITLE
plotting rendering

### ISSUE THREAD

**Issue by patquem** [K3D-tools/K3D-jupyter#276]
Hello,

I have just discovered k3d this day and I am really impressed by the capabilities of such a tool. (congratulations to the developpers !)

I have some questions about new features that you have probably already thought and planned (?) for the next releases.

- **opacity** : this functionality is of interest when representing different surfaces/volume in the same plot.
- **color_bar** : ipyscales proposes interesting tools to allow the users to specifiy their own colorbars (`ColorMapEditor`). Do you think to use the ipyscale formalism in k3d for the future ?
- **colorLegend** : when dealing with several objects in the same plot, the colorlegends are surimposed. The abitlity to manually move them would be greatly appreciated !

Thanks for your answers,
Patrick

**Comment by artur-trzesiok** [comment]
Hi!

### Opacity

We have support for **opacity** in most of objects. As I explain [here](https://github.com/K3D-tools/K3D-jupyter/issues/277) We will even have support to [OIT](https://en.wikipedia.org/wiki/Order-independent_transparency).

### Color_bar

About **color_bar** and ColorMapEditor - K3D have own simple transfer function + color map editor - please look [here](https://github.com/K3D-tools/K3D-jupyter/blob/devel/examples/transfer_function.ipynb):

![image](https://user-images.githubusercontent.com/5256837/118227543-aaacb600-b4c3-11eb-8c27-a34527e556b1.png)

I don't want to force anybody to use only one color_map editor thats why K3D consume color_map as numpy array in format:

```
[
[value, red, green, blue],
[value, red, green, blue],
...
]
```

Please check build-in presets:

```
np.array(k3d.colormaps.paraview_color_maps.Jet).reshape(-1,4)
array([[-1.      ,  0.      ,  0.      ,  0.5625  ],
       [-0.777778,  0.      ,  0.      ,  1.      ],
       [-0.269841,  0.      ,  1.      ,  1.      ],
       [-0.015873,  0.5     ,  1.      ,  0.5     ],
       [ 0.238095,  1.      ,  1.      ,  0.      ],
       [ 0.746032,  1.      ,  0.      ,  0.      ],
       [ 1.      ,  0.5     ,  0.      ,  0.      ]])
```

So I hope that integration between ipyscales and K3D is pretty easy to achive. And also that give you a option to produce your own colorbar if you want!

### ColorLegend

In fact colorbar in k3d is linked with only one object at scene. I remember that we have one feature request related to this topic. At this moment I want to keep it simple and I want to avoid adding multipile colorbars. If you think that this is kind of crucial I can consider to do that feature with cooperation with someone from K3D community.

Thanks for usage a K3D and sorry for late replay!
Artur

**Comment by artur-trzesiok** [comment]
@patquem do my answer meet with your expectations?

**Comment by patquem** [comment]
hello @artur-trzesiok,
It has been a while. 
For my purpose, I have finally used ipyvolume for mixing isosurface with colormap providing from another surface (with a dedicated function).
But I am glad to hear about features you have reported in your reply. (Transfer function editor is really good 👍 )
For my future investigations in visualisation, I will keep this in mind.
Thanks,
Patrick
