### ISSUE TITLE
Is it possible to modify mouse interaction behavior?

### ISSUE THREAD

**Issue by esalehim** [K3D-tools/K3D-jupyter#278]
Is it possible to change the mouse button for different interactions like panning and zooming?
I'd like to set SHIFT + left button for panning in Trackball mode

**Comment by artur-trzesiok** [comment]
We have exactly that functionality in "orbit" mode. Please look here: https://github.com/K3D-tools/K3D-jupyter/blob/master/js/src/providers/threejs/helpers/THREE.OrbitControls.js#L768

Exposing that modification to python API looks to be quite complicated. I can embed that kind of feature in trackball but we need to have something like "complete solution proposal" here to avoiding random-driven development. 

In trackball by default we have the same on 'A' / 'S' / 'D' keys but unfortunately, those keys are reserved for jupyter notebook:
https://github.com/K3D-tools/K3D-jupyter/blob/devel/js/src/providers/threejs/helpers/THREE.TrackballControls.js#L51

So I will change that to: CTRL / ALT / SHIFT

What do you think, Does that meet your expectations?

**Comment by artur-trzesiok** [comment]
@esalehim K3D 2.9.5 is released (for now on PyPi, we are waiting for conda-forge). If you can please check out the new version and test if what we wrote about here works. Thanks!

**Comment by esalehim** [comment]
Thanks for your prompt reply and super quick support!

Shift modifier for panning works now. Thanks!
There are two issues though:

1) Normally in Trackball mode, user holds SHIFT key down, and starts panning using mouse in multiple steps (i.e. click, drag, click, drag...) Right now If I release mouse click once, k3d exists panning mode even if shift key is still pressed. so solution would be to immediately switch to panning mode if SHIFT key is already pressed

2) There is a regression in 2.9.5 about setting objects opacity. I will create a separate issue for that

**Comment by artur-trzesiok** [comment]
@esalehim I updated trackball to new one from three.js without those bugs. I also adapted it to previous k3d features. Right now usage of k3d is much easier :) - thanks!

https://github.com/K3D-tools/K3D-jupyter/commit/c7b516da8ec77fad5a89f8ef1a18baba40bf7796#diff-552a4d3d5c85b99dd796ffc92e515bc4c096290b8584d02a1210143d8a4ef3a5

**Comment by esalehim** [comment]
Can't wait to test it out. It's amazing how fast you implement new features! :clap:
Thanks a lot

**Comment by artur-trzesiok** [comment]
K3D@2.9.7 is released on pypi (and soon on conda-forge) - https://pypi.org/project/K3D/2.9.7/ . Please check a new version that should contain fix for this issue.
