### ISSUE TITLE
Clipping plane hides vectors stems

### ISSUE THREAD

**Issue by Davide-sd** [K3D-tools/K3D-jupyter#279]
```
import numpy as np
import k3d

fig = k3d.plot()
n = 20
x = np.linspace(-5, 5, n)
y = np.linspace(-5, 5, n)
z = np.linspace(-5, 5, n)
xx, yy, zz = np.meshgrid(x, y, z)
uu, vv, ww = zz, yy, xx
xx, yy, zz, uu, vv, ww = [t.flatten().astype(np.float32) for t in [xx, yy, zz, uu, vv, ww]]
scale = 0.5
magnitude = np.sqrt(uu**2 + vv**2 + ww**2)
vectors = np.array((uu, vv, ww)).T * scale
origins = np.array((xx, yy, zz)).T
colors = k3d.helpers.map_colors(magnitude, k3d.matplotlib_color_maps.Plasma, [])
vec_colors = np.zeros(2 * len(colors))
for i, c in enumerate(colors):
    vec_colors[2 * i] = c
    vec_colors[2 * i + 1] = c
vec_colors = vec_colors.astype(np.uint32)
vec = k3d.vectors(
    origins = origins - vectors / 2,
    vectors = vectors,
    colors = vec_colors,
)
fig += vec
fig.display()
```

When I add a clipping plane, the stems of the vectors become invisible.

Version 2.9.4.

**Comment by artur-trzesiok** [comment]
Poor vectors steams! :D Thanks for finding this bug. It will be fixed in next release - I found source of bug.

Btw. Very eye-candy example! Can I add that to our Github "example folder"?

**Comment by Davide-sd** [comment]
> Poor vectors steams! :D Thanks for finding this bug. It will be fixed in next release - I found source of bug.

Thank you!!! 

> Btw. Very eye-candy example! I added that to our Github "example folder" (https://github.com/K3D-tools/K3D-jupyter/blob/devel/examples/vector_field_3d.ipynb) - please tell if you have anything against that.

I'm good with it :)

**Comment by artur-trzesiok** [comment]
@Davide-sd K3D 2.9.5 is released (for now on PyPi, we are waiting for conda-forge). If you can please check out the new version and test if what we wrote about here works. Thanks!

**Comment by Davide-sd** [comment]
Thanks @artur-trzesiok , the new version works great! :)

I'm closing this issue since it has been resolved! Thank you!!!
