### ISSUE TITLE
Regression in 2.9.5

### ISSUE THREAD

**Issue by esalehim** [K3D-tools/K3D-jupyter#282]
There seems to be a regression in 2.9.5 about setting objects opacity. See below

**Expected: v2.9.4**
Green object opacity is set to 0.4
![image](https://user-images.githubusercontent.com/44696797/118648600-e062df00-b7e2-11eb-94d6-4e56649be31a.png)

**2.9.5**
![image](https://user-images.githubusercontent.com/44696797/118648728-02f4f800-b7e3-11eb-85c8-884820848257.png)

**Workaround**: If I toggle object visibility off and on again, it will be displayed correctly as expected

**Comment by artur-trzesiok** [comment]
Thanks! I will release hotfix for that

wt., 18 maj 2021, 21:14 użytkownik Ehsan Salehi ***@***.***>
napisał:

**Comment by artur-trzesiok** [comment]
@esalehim please check version 2.9.6

**Comment by esalehim** [comment]
I have checked the 2.9.6 release and it looks better than 2.9.5 but still not exactly identical to 2.9.4 and older releases. I still see some glitches in transparent objects. Has something fundamentally changed about transparency?!

**Comment by artur-trzesiok** [comment]
@esalehim yes, quite big one. I prepared k3d to have OIT and that affect whole render pipeline - https://github.com/K3D-tools/K3D-jupyter/issues/277

Can you deliver snapshot from k3d@2.9.4 with your data? I will use that as regression checker for my Test Driven Deevlopment. You can share that on my email: artur.trzesiok@gmail.com - that will be very helpfully

**Comment by esalehim** [comment]
@artur-trzesiok I will send you the snapshot today. Thanks a lot!

**Comment by artur-trzesiok** [comment]
K3D@2.9.7 is released on pypi (and soon on conda-forge) - https://pypi.org/project/K3D/2.9.7/ . Please check a new version that should contain fix for this issue.
