### ISSUE TITLE
Very high aspect ratio meshes

### ISSUE THREAD

**Issue by Davide-sd** [K3D-tools/K3D-jupyter#285]
Hello,

my application might generate meshes with very high aspect ratio. An example is given with the code below:

```
import k3d
import numpy as np
from matplotlib.tri import Triangulation

f = lambda z: (z**2 + 1) / (z**2 - 1)
x = y = np.linspace(-2, 2, 300)
xx, yy = np.meshgrid(x, y)
zz = f(xx + 1j * yy)
mag = np.absolute(zz)
phase = np.angle(zz)

fig = k3d.plot()
xx, yy, mag, phase = [t.flatten().astype(np.float32) for t in [xx, yy, mag, phase]]
vertices = np.vstack([xx, yy, mag]).T.astype(np.float32)
indices = Triangulation(xx, yy).triangles.astype(np.uint32)

surf = k3d.mesh(vertices, indices,
    side = "double",
    volume_bounds = (min(xx), max(xx), min(yy), max(yy), min(phase), max(phase)),
    color_map = k3d.paraview_color_maps.Erdc_iceFire_H,
    attribute = phase)

fig += surf
fig.display()
```

Notice that the mesh ranges from -2 to 2 in the X/Y axis:

![K3D-1623147202928](https://user-images.githubusercontent.com/9921777/121168616-71adfa00-c853-11eb-86d3-b3c6c13f1579.png)

Here the problem is that I can't zoom in enough to view the details. Zooming in all the way I get this:

![K3D-1623147251200](https://user-images.githubusercontent.com/9921777/121169235-1597a580-c854-11eb-8c3b-fc68414d7bfe.png)

What can I try?

**Comment by artur-trzesiok** [comment]
Hi! Three solutions:

1. Please setup your camera from code: fig.camera = [5,5,15,0,0,0,0,0,1]
2. Please don't zoom in (wheel) but pan (right click + wheel)
3. Please use "fly" camera instead of trackball: fig = k3d.plot(camera_mode='fly')

**Comment by Davide-sd** [comment]
Thanks Artur, they works.

I thought I could try to set a clipping plane before the figure was displayed, for example `fig.clipping_planes = [[0, 0, -1, 5]]`, but it doesn't work. It only works after the figure has been shown.

I'll probably modify `Plot.get_auto_camera` to get auto camera working for such cases.

**Comment by artur-trzesiok** [comment]
K3D@2.9.7 is released on pypi (and soon on conda-forge) - https://pypi.org/project/K3D/2.9.7/ . Please check a new version that should contain fix for this issue.

**Comment by Davide-sd** [comment]
@artur-trzesiok I need a little help for the upgrade. I've tried the following:
* upgrade k3d, clear the browser cache ->  Python v2.9.7, JS v2.9.6
* removed the environment, create a new environment, reinstalled everything with --no-cache-dir, clear browser cache -> Python v2.9.7, JS v2.9.6

Where are the old JS files stored? I'm going to delete them manually .....

**Comment by artur-trzesiok** [comment]
Hi David!

It is hard to say where old version are stored. I will guess that in web browser cache.

I recommend also re run:
```
jupyter nbextension install --py k3d
jupyter nbextension enable --py k3d

```

**Comment by Davide-sd** [comment]
Thanks @artur-trzesiok . Those two lines solved the problem!!!

Going back to the issue, now the situation is greatly improved! I consider this issue resolved. Thank you very much!!!
