### ISSUE TITLE
Start Labels as not visible?

### ISSUE THREAD

**Issue by dillonhaughton** [K3D-tools/K3D-jupyter#291]
I would like to start off with label objects not visible and the user can check them as they go. Is there a way to update the labels object to have a visible=False setting. 

Also is there anyway to remove contents of the menu? I would like to simplify the menu if its possible.

**Comment by artur-trzesiok** [comment]
I'm not sure if I understand you. What do you mean by labels? k3d.labels of "name" property in every object in k3d?

Menu in K3D is a very "technical" and there is no option to customize it. You can use plot.menu_visibility = False to hide it and create your own if you like (for example with ipywidgets links).

Do you have in mind what kind of simplification you want?

**Comment by dillonhaughton** [comment]
Im experimenting using the software to turn some photometry models into interactive displays. There are a lot of labels (k3d.labels) on these models and Id like to start with their visibility checked off so the scene doesn't start so cluttered. 

I could create me own custom ipywidgets but I need to export the entire scene as an html. Is there a way to export the mesh plot and the custom ipywidget together as a single html?

**Comment by artur-trzesiok** [comment]
No straightforward. K3D have own Javascript level API so that will require manual handling interactions between your custom widgets and k3d via:

```
var jsons = K3DInstance.getWorld().ObjectsListJson; // get all objects on scene
jsons[id].visible = true; //change visibility
K3DInstance.reload(jsons[id], {visible: true}, true);
```

I recommend to use name='' attribute for taging a labels.

**Comment by artur-trzesiok** [comment]
@dillonhaughton can we close this issue?
