### ISSUE TITLE
What is the use of the Group object?

### ISSUE THREAD

**Issue by mholtmanns** [K3D-tools/K3D-jupyter#292]
I tried using k3d.objects.Group to add 2 different groups of 2 point clouds each. But in the interactive controls I only see the different Points objects, no Group objects.

If the Group is not shown as part of the controls, what is the practical application? Do you have some examples?

Thanks!

**Comment by tgandor** [comment]
It's currently a backend-only utility. It can be added to and removed from plot; and it can pass the `model_matrix` attribute down to all its members.

The frontend (plot in the browser) currently knows nothing about groups.

We may have to re-evaluate this feature, and maybe deprecate and remove it (right now it doesn't offer much more than having a Python `list` of `Drawable` objects).

**Comment by mholtmanns** [comment]
Thank you!
Too bad, would be a nice addition to thed frontend. As would be the ability to give more descriptive names to the different elements than just "points#1, points#2, ..." :-)
Anyway, closing this issue, thanks again.
