### ISSUE TITLE
fetch_snapshot of a textured mesh

### ISSUE THREAD

**Issue by tfunatomi** [K3D-tools/K3D-jupyter#293]
Hello,
this project is so great. 
Especially, fetch_snapshot is wonderful.

I enjoyed snapshots and found that the texture of a mesh is not dumped.
The following code successfully presents a textured rectangle, 
```
    plt_texture = k3d.mesh(
        vertices=[[0,0,0],[img_shape[1],0,0],[img_shape[1],img_shape[0],0],[0,img_shape[0],0]],
        indices=[[0,1,2,],[2,3,0]],
        uvs=[[0,0],[1,0],[1,1],[0,1]],
        texture=open(img_path,'rb').read(),
        texture_file_format=splitext(img_path)[1],
    )
    plot += plt_texture
```
but an error occurs when opening the dumped snapshot.

The length of the snapshot is only 125 for this object, so I think texture data is not dumped at all.
I really appreciate it if it is supported.

**Comment by artur-trzesiok** [comment]
Thanks for a kind words.
1. I highly recommend to add color=0xffffff to avoid a multiplication of whole image by blue  :)
2. Good spot. Something dosen't work here. I guess that Bytes() trait is not supported by serialization. I will try to fix that.

**Comment by artur-trzesiok** [comment]
Ok. This change https://github.com/K3D-tools/K3D-jupyter/commit/61ff4f81ba8b5fc19d0840f86de617d5f4d07138 provide new serialization behaviour of Bytes but we adapted it only for STL. Right now that will be quick to fix it ! 👍

**Comment by tfunatomi** [comment]
Dear @artur-trzesiok,

I would thank for your quick reply and fix.

I tested it on my environment, but the stored html tells an error as follows.
`"Loader Error: K3D Loader failed, please consult browser error console!"`
[test.zip](https://github.com/K3D-tools/K3D-jupyter/files/6725692/test.zip)

I really appreciate if there is something wrong with me.
The code used for it was as follows:
```
img_path = 'path-to-lib/K3D-jupyter/imgs/vr.png'
img_shape = cv2.imread(img_path,-1).shape

plot = k3d.plot()
plt_texture = k3d.mesh(
    vertices=[[0,0,0],[img_shape[1],0,0],[img_shape[1],img_shape[0],0],[0,img_shape[0],0]],
    indices=[[0,1,2,],[2,3,0]],
    uvs=[[0,0],[1,0],[1,1],[0,1]],
    texture=open(img_path,'rb').read(),
    texture_file_format=splitext(img_path)[1],
    color=0xffffff
)
plot += plt_texture

plot.fetch_snapshot()

with open('test.html','w') as f:
    f.write(plot.snapshot)
    f.close()
plot.snapshot
```

Best regards,

**Comment by artur-trzesiok** [comment]
K3D@2.9.7 is released on pypi (and soon on conda-forge) - https://pypi.org/project/K3D/2.9.7/ . Please check a new version that should contain fix for this issue.

**Comment by tfunatomi** [comment]
Hi, @artur-trzesiok 
I appreciate your work. It works fine now!
