### ISSUE TITLE
Generated Screenshot different from Jupyterlab view

### ISSUE THREAD

**Issue by mironvanderkolk** [K3D-tools/K3D-jupyter#294]
After upgrading to k3d 2.9.6, I have found this problem still exists:

![k3d_comparison_2 9 6](https://user-images.githubusercontent.com/56925246/123809188-b0cee880-d8f1-11eb-838c-a656e4a22cef.png)

On the left side is the view after generating a screenshot from the contex menu. The right side is a manual screenshot for the view in jupyterlab. The intersection between the two spheres in rendered incorrectly in the generated screenshot.

Code to reproduce:
```
import k3d
import numpy as np
k3d.points(np.array([[1.0, 1.0, 0.5], [0.75, 1.0, 0.5]]), shader='mesh', colors=[int('FF0000', 16), int('0000FF', 16)])
```

Referenced the old issue here which was closed, generated screenshots worked correctly in k3d 2.8.2
_Originally posted by @mironvanderkolk in https://github.com/K3D-tools/K3D-jupyter/issues/257#issuecomment-870620379_

**Comment by artur-trzesiok** [comment]
Hi

Do you mean shader='mesh' as attribute? Because your screens looks like mesh - not 3d.

Can you send a lines from developer console that appear after displaying plot of k3d:

Example:
```
K3D: (UNMASKED_VENDOR_WEBGL) Google Inc. (NVIDIA)
Renderer.js:120 K3D: (UNMASKED_RENDERER_WEBGL) ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6589)
Loader.js:55 K3D: Object type "Points" loaded in:  0.001 s
```
?

**Comment by mironvanderkolk** [comment]
Sorry, I indeed meant the 'mesh' shader, like in the previous issue.

```
K3D: (UNMASKED_VENDOR_WEBGL) Google Inc. (Intel)
labplugin.js:1 K3D: (UNMASKED_RENDERER_WEBGL) ANGLE (Intel, Mesa Intel(R) UHD Graphics (CML GT2), OpenGL 4.6 (Core Profile) Mesa 20.2.6)
labplugin.js:1 K3D: Object type "Points" loaded in:  0.012 s
```
This is the lines from the console when the plot if is first displayed in jupyterlab.

After clicking the 'screenshot' button in the 'control' menu, some warnings appear 
```
[Violation] 'click' handler took 184ms
vendors~main.396de1bf12207ccaaf30.js:2 [Violation] 'click' handler took 185ms
rasterizeHTML.js:572 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
(anonymous) @ rasterizeHTML.js:572
i.calculateDocumentContentSize @ rasterizeHTML.js:546
i.drawDocumentAsSvg @ rasterizeHTML.js:936
A @ rasterizeHTML.js:979
(anonymous) @ rasterizeHTML.js:1026
rasterizeHTML.js:573 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
(anonymous) @ rasterizeHTML.js:573
i.calculateDocumentContentSize @ rasterizeHTML.js:546
i.drawDocumentAsSvg @ rasterizeHTML.js:936
A @ rasterizeHTML.js:979
(anonymous) @ rasterizeHTML.js:1026
labplugin.js:1 K3D: Screenshot [html]: 1.24 s
three.module.js:23491 WebGLRenderer: .getClearColor() now requires a Color as an argument
getClearColor @ three.module.js:23491
(anonymous) @ labplugin.js:1
e.exports @ labplugin.js:1
renderOffScreen @ labplugin.js:1
(anonymous) @ labplugin.js:1
Promise.then (async)
(anonymous) @ labplugin.js:1
a @ labplugin.js:1
screenshot @ labplugin.js:1
e @ dat.gui.module.js:1272
(anonymous) @ dat.gui.module.js:1259
e @ dat.gui.module.js:835
(anonymous) @ dat.gui.module.js:2243
three.module.js:23491 WebGLRenderer: .getClearColor() now requires a Color as an argument
getClearColor @ three.module.js:23491
(anonymous) @ labplugin.js:1
e.exports @ labplugin.js:1
(anonymous) @ labplugin.js:1
Promise.then (async)
renderOffScreen @ labplugin.js:1
(anonymous) @ labplugin.js:1
Promise.then (async)
(anonymous) @ labplugin.js:1
a @ labplugin.js:1
screenshot @ labplugin.js:1
e @ dat.gui.module.js:1272
(anonymous) @ dat.gui.module.js:1259
e @ dat.gui.module.js:835
(anonymous) @ dat.gui.module.js:2243
three.module.js:23491 WebGLRenderer: .getClearColor() now requires a Color as an argument
getClearColor @ three.module.js:23491
(anonymous) @ labplugin.js:1
e.exports @ labplugin.js:1
(anonymous) @ labplugin.js:1
Promise.then (async)
(anonymous) @ labplugin.js:1
Promise.then (async)
renderOffScreen @ labplugin.js:1
(anonymous) @ labplugin.js:1
Promise.then (async)
(anonymous) @ labplugin.js:1
a @ labplugin.js:1
screenshot @ labplugin.js:1
e @ dat.gui.module.js:1272
(anonymous) @ dat.gui.module.js:1259
e @ dat.gui.module.js:835
(anonymous) @ dat.gui.module.js:2243
labplugin.js:1 K3D: Screenshot [canvas]: 1.484 s
```

The browser starts a download of the screenshot, then when I open it, it is not equal to the view in the jupyterlab plot

**Comment by sjnarmstrong** [comment]
I seem to have a similar issue when rendering a voxel structure. When Taking a screenshot of the structure odd artifacts appear both with and without the border.
I am on version 2.9.7. (K3D @ git+https://github.com/K3D-tools/K3D-jupyter@d022a45291e9593535e28e94ab043aa026cf5458)
I am on an Ubuntu System with a Chrome browser.

The code I used is:
```
plot = k3d.plot()
pts = np.random.rand(5,3)*10 
vox_pts = np.unique(np.floor(pts/voxel_size), axis=0)
vox_pts = np.pad(vox_pts, ((0,0),(0,1)), constant_values=1)

mesh = k3d.factory.sparse_voxels(
    vox_pts.astype(np.uint16), 
    vox_pts.max(axis=0)[:3].astype(np.uint16)+1
)
plot += mesh

plot.camera_auto_fit = True
plot.grid_auto_fit = True
plot
```
![Screenshot from 2021-07-31 00-55-19](https://user-images.githubusercontent.com/46250125/127719106-f90764de-a079-4af6-86df-bd428bc4b8b6.png)
![K3D-1627685648431](https://user-images.githubusercontent.com/46250125/127719127-3fe156e9-f319-48e5-8374-aeaa7d41657b.png)

**Comment by MironLeon** [comment]
I have reproduced the issue on version `2.11.0` as well.

@sjnarmstrong by accident I found out that the screenshot function works perfectly on Windows 10 with the Chrome browser, it seems to be Linux that is the issue (I run Ubuntu 20.04 locally)

Some images to show issue again:

from code:
```
import k3d
import numpy as np
import ipywidgets

out = widgets.Output(layout={'width': '600px', 'height': '600px'})

plot = k3d.plot()
plot += k3d.points(
    np.random.rand(100, 3),
    colors = (np.random.rand(100) * 16777215).astype(int),
    shader='3d'
)
with out:
    display(plot)
display(out)
```

**3d shader generated screenshot**
![K3D-1638960756873](https://user-images.githubusercontent.com/89517300/145197619-c9e20062-1ebf-49a2-be57-bec564007f17.png)

**3d shader manual screenshot**
![3d_shader_original](https://user-images.githubusercontent.com/89517300/145197693-530be8b1-2737-43db-92b2-75a313b04541.png)

**mesh shader generated screenshot**
![K3D-1638960696219](https://user-images.githubusercontent.com/89517300/145197766-4fef8498-29df-44b1-a360-0efdfe3b2c57.png)

**mesh shader manual screenshot**
![mesh_shader_original](https://user-images.githubusercontent.com/89517300/145197861-73476543-146b-4bae-8287-145258e1b5fc.png)

**Comment by MironLeon** [comment]
I have tried writing some custom scripts to generate the screenshots myself. Interestingly, when selecting the canvas element that k3d draws on and calling `toDataURL()` I can generate a correct screenshot:

```
target_div = document.getElementsByClassName('k3d-target')[0]
target_canvas = target_div.getElementsByTagName('canvas')[0]
const linkElement = document.createElement("a");
linkElement.href = target_canvas.toDataURL();
linkElement.setAttribute("download", 'test.png');
linkElement.click();
```

Produces the following image:
![test (30)](https://user-images.githubusercontent.com/89517300/145198656-4994e8f0-604b-48ac-b0c7-2d0dee1c0cf1.png)

Which at least have the intersections between the meshes rendered correctly, the gridlines are missing and all the text labels (those are separate katex spans placed on top of the canvas element)

Looking through the k3d source, it seems internally the same tactic is used, so I'm not sure why it produces different results:
https://github.com/K3D-tools/K3D-jupyter/blob/main/js/src/k3d.js#L227

**Comment by artur-trzesiok** [comment]
Maybe latest change will help here. I realized that software rendering was not good enough.

Change:

```
        const sampleRenderTarget = new THREE.WebGLRenderTarget(rt.width, rt.height, {
            minFilter: THREE.LinearFilter,
            magFilter: THREE.LinearFilter,
            format: THREE.RGBAFormat
        });
```

to:

```
        const sampleRenderTarget = new THREE.WebGLRenderTarget(rt.width, rt.height, {
            minFilter: THREE.LinearFilter,
            magFilter: THREE.LinearFilter,
            format: THREE.RGBAFormat,
            stencilBuffer: true,
        });
```
