### ISSUE TITLE
Per point size in `k3d.points`

### ISSUE THREAD

**Issue by hgarrereyn** [K3D-tools/K3D-jupyter#295]
It would be awesome to be able to specify a per-point size in `k3d.points` as an alternative to a single, global `point_size`. I.e. in the same vein as #198 except specifying point size rather than opacity.

Current api looks like this:
```py
plot = k3d.plot()
pos = np.random.randn(100,3)
plot += k3d.points(pos, point_size=0.2)
plot.display()
```

It would be nice to be able to do this:
```py
plot = k3d.plot()
pos = np.random.randn(100,3)
sz = np.random.randn(100)
plot += k3d.points(pos, point_sizes=sz)
plot.display()
```

I don't imagine this will add much overhead to the shader. I'm happy to try to tackle this myself if someone points me in the right direction.

**Comment by artur-trzesiok** [comment]
I like your suggestions. It its a complicated a little bit because we have two strategies for points (flat/3d/3dspectular) is a bilboard points and mesh is a ... triangle mesh point. I will investigated that

**Comment by artur-trzesiok** [comment]
K3D@2.9.7 is released on pypi (and soon on conda-forge) - https://pypi.org/project/K3D/2.9.7/ . Please check a new version that should contain fix for this issue.

**Comment by hgarrereyn** [comment]
Thanks, just updated and it's working perfectly!

**Comment by artur-trzesiok** [comment]
Glad to hear that :). Enjoy!
