### ISSUE TITLE
Standalone HTML representation of animation not loading

### ISSUE THREAD

**Issue by renefritze** [K3D-tools/K3D-jupyter#296]
I've tried running the hydrogen example notebook through nbconvert to get a "static" representation. The produced html file will generally load, but the plot will not. 
Browser console (same error in firefox)
[k3d.log](https://github.com/K3D-tools/K3D-jupyter/files/6765093/k3d.log)
I've added the converted html too (zipped since GitHub doesn't allow html attachments:
[k3d.html.zip](https://github.com/K3D-tools/K3D-jupyter/files/6765102/k3d.html.zip)

**Comment by artur-trzesiok** [comment]
@renefritze snapshot with this example should have 241mb. Please run

```
with open('dump.html', 'w') as f:
    f.write(plot.get_snapshot(9))
```

nvconvert probably dosen't have state of widget stored in ipynb file. Please chek size of hydrogen_orbitals.ipynb. Probably you didn't run "save notebook widget state" option:
![image](https://user-images.githubusercontent.com/5256837/124991222-a921e900-e041-11eb-9387-1903cbdc4715.png)


Can you try that again?

**Comment by renefritze** [comment]
> napshot with this example should have 241mb. Please run

Yes, can confirm it's 242MB for me.
(Getting the snapshots needs msgpack installed btw, which does not seem to be a dependency for k3d)



> nvconvert probably dosen't have state of widget stored in ipynb file. Please check size of hydrogen_orbitals.ipynb. Probably you didn't run "save notebook widget state" option

I've actually tried a two step conversion (this is paraphrased from a script I want to use on a bunch of notebooks):
 1. `jupyter nbconvert --execute --ExecutePreprocessor.store_widget_state=True --to notebook k3d.ipynb  --output executed.k3d.ipynb`
 2. `jupyter nbconvert --to html executed.k3d.ipynb`

The `executed.k3d.ipynb` is indeed only 87K where the original is 4K. Now if I manually run a copy of the notebook (`with_saved.k3d.ipynb`) and save the widget state, then its size is 509M. If this is again executed like above with nbconvert it's dropping back to 87K. 
If I manually convert `with_saved.k3d.ipynb` to html the resulting file is indeed 509M. That page however will also not show the plot: 
[with_saved.txt](https://github.com/K3D-tools/K3D-jupyter/files/6789996/with_saved.txt)

Aside from this load failure, I think that generally it would be great if the manual save wasn't necessary. For the documentation nbsphinx doesn't do anything magic, right? There the states are already in the notebooks?

**Comment by artur-trzesiok** [comment]
Good spot - I will add "msgpack" as 'install_requires'.
I guess that @marcinofulus have bigger experience with nbconvert and probably solve that kind of problem. @marcinofulus can you help here?

**Comment by artur-trzesiok** [comment]
@renefritze I like your idea! https://github.com/K3D-tools/K3D-jupyter/blob/devel/examples/points.ipynb

**Comment by artur-trzesiok** [comment]
if you want to have autoplay option in snapshot you need to pass param:

`plot.get_snapshot(additional_js_code='K3DInstance.startAutoPlay()')`

**Comment by renefritze** [comment]
Awesome. It'll be a while before I can play with this, but great turnaround on the feature :+1:
