### ISSUE TITLE
Snapshot issue

### ISSUE THREAD

**Issue by dodointhesnow** [K3D-tools/K3D-jupyter#300]
I have a k3d snapshot html created using vedo. I was hoping to read the html into a k3d plot object so I could change some of the mesh and point colors/size in my code. Is this possible? Thanks

**Comment by artur-trzesiok** [comment]
@dodointhesnow That will be possible. In k3d@2.10.0 we will introduce new snapshot system.

**Comment by artur-trzesiok** [comment]
https://github.com/K3D-tools/K3D-jupyter/blob/devel/examples/snapshots.ipynb
