### ISSUE TITLE
Advanced html snapshot

### ISSUE THREAD

**Issue by Davide-sd** [K3D-tools/K3D-jupyter#301]
I have to include multiple K3D plots into a sphinx documentation page. I thought I could insert the snapshot html file with:

```
.. raw:: html
	:file: figs/tut/fig-01.html
```

But it doesn't work, in the console i see this error:

```
Uncaught ReferenceError: pako is not defined

Uncaught Error: Mismatched anonymous define() module: function(e){"use strict";var t=(e,t,i,n)=>{let a=65535&e|0,r=e>>>16&65535|0,s=0;for(;0!==i;){s=i>2e3?2e3:i,i-=s;do{a=a+t[n++]|0,r=r+a|0}while(--s);a%=65521,r%=65521}return a|r<<16|0};const i=new Uint32Array((()=>{let e,t=[];for(var i=0;i<256;i++){e=i;for(var n=0;n<8;n++)e=1&e?3988292384^e>>>1:e>>>1;t[i]=e}return t})());var n=(e,t,n,a)=>{const r=i,s=a+n;e^=-1;for(let i=a;i<s;i++)e=e>>>8^r[255&(e^t[i])];return-1^e};var a=function(e,t){let i,n,a,r,s,o,l,d,f,h,c,u,w,b,k,m,_,g,v,p,y,x,E,R;const A=e.state;i=e.next_in,E=e.input,n=i+(e.avail_in-5),a=e.next_out,R=e.output,r=a-(t-e.avail_out),s=a+(e.avail_out-257),o=A.dmax,l=A.wsize,d=A.whave,f=A.wnext,h=A.window,c=A.hold,u=A.bits,w=A.lencode,b=A.distcode,k=(1<<A.lenbits)-1,m=(1<<A.distbits)-1;e:do{u<15&&(c+=E[i++]<<u,u+=8,c+=E[i++]<<u,u+=8),_=w[c&k];t:for(;;){if(g=_>>>24,c>>>=g,u-=g,g=_>>>16&255,0===g)R[a++]=65535&_;else{if(!(16&g)){if(0==(64&g)){_=w[(65535&_)+(c&(1<<g)-1)];continue t}if(32&g){A.mode=12;bre…
    makeError https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    ...
```

I think the requirejs included with the snapshot is in conflict with the requirejs of the documentation page.

Would it be possible to create an advanced snapshot that:

1. separates the different javascript libraries into their own files. For example, `pako.js`, `k3d.js`... In doing so, when multiple plots need to be included in the same document, the overall file size would be (potentially) much smaller.
2. It assigns a unique ID to the wrapper div, maybe some kind of hash based on the data, or an option passed in by the user. In doing so, it minimizes the overall chances of conflicts when including multiple plots in the same document.
3. Allows the possibility to create an html file without the html/head/body tags. This will create a file ready to be inserted into other documents.
4. It minimizes all the output files.

For reference, Plotly does something similar with the [Interactive HTML export](https://plotly.com/python/interactive-html-export/), by setting `fig.write_html(path, include_plotlyjs="require", full_html=False)`. The html files created with that command are ready to be inserted into a documentation page: it works like a charm.

**Comment by artur-trzesiok** [comment]
@Davide-sd ok, nice spot. But this fig-01.html - how do you generate it? 
```
with open('snapshot_standalone.html', 'w') as f:
    f.write(plot.get_snapshot())
```
?

and second question: what did happen when you open a fig-01.html in webbrowser outside a sphinx documentation page?

**Comment by artur-trzesiok** [comment]
>Allows the possibility to create an html file without the html/head/body tags. This will create a file ready to be inserted into other documents.

Thats will come with K3D@2.10.0 - https://github.com/K3D-tools/K3D-jupyter/blob/devel/examples/snapshots.ipynb

**Comment by Davide-sd** [comment]
In my first attempt I clicked the "Snapshot HTML" button. This creates a file containing all the necessary Javascript. If I open it on the browser, the plot will be correctly shown. If I insert this file into sphinx, I get the above errors.

In the second attempt, after looking at the source code, I did:

```
with open('fig-01.html', 'w') as f:
    plot.snapshot_include_js = False
    f.write(plot.get_snapshot())
```

This creates a much lighter file, which is easier to edit. Again, once opened on the browser, the plot is correctly shown after the JS libraries are downloaded from the web.

**Comment by artur-trzesiok** [comment]
@Davide-sd ok, I got it. btw. amazing work with  https://github.com/Davide-sd/sympy-plot-backends . Congratulations! I will try to reproduce your case with my sphinx and I will try to find a solution. 

But... In my case I prefer to store k3d plot as *.k3d file (new feature that I shared above) and on website write few lines of code:

```
  function fileLoader(url, callback) {
    var xhrLoad = new XMLHttpRequest();
    xhrLoad.responseType = "arraybuffer";
    xhrLoad.open('GET', url, true);

    xhrLoad.onreadystatechange = function () {
      if (xhrLoad.readyState === 4) {
        callback(xhrLoad.response);
      }
    };

    xhrLoad.send(null);
  }

  require(['k3d'], function (lib) {
    fileLoader('mip_opacity_function.k3d', function (data) {
      K3DInstance = lib.CreateK3DAndLoadBinarySnapshot(
        data,
        document.getElementById('canvasTarget')
      ).then(function (ret) {
        K3DInstance = ret;
        setTimeout(function () {
          K3DInstance.resetCamera(0.5);
        }, 250);
      });
    });
  });
```

So K3D expose method CreateK3DAndLoadBinarySnapshot that load pure plot-data state file (*.k3d). So I will add line:

`<script src="https://unpkg.com/k3d@[VERSION]/dist/standalone.js"></script>`

Into my template and prepare snippet like before to load plot into sphinx. This is alternative way and I hope soon we will have something like that in k3d docs (that is based on Sphinx). But still I think that your version should works too so I will investigate that.

**Comment by artur-trzesiok** [comment]
@Davide-sd fast workaround:
```
.. raw:: html
    <iframe src="_static/figs/tut/fig-01.html" frameborder="0" height="300px" width="300px"></iframe>
```

**Comment by artur-trzesiok** [comment]
https://github.com/K3D-tools/K3D-jupyter/blob/devel/examples/snapshots.ipynb

```
Save to inline *.html file
Inline element can be embeded in any html document like Sphinx documentation:

.. raw:: html
    :file: inline_shapshot.html
```

Usage:

```
plot5 = get_plot()
plot5.snapshot_type = 'inline'
plot5.display()

data = plot5.get_snapshot()

with open('snapshot_inline.html', 'w') as f:
    f.write(data)
```

**Comment by Davide-sd** [comment]
> btw. amazing work with https://github.com/Davide-sd/sympy-plot-backends .

Thank you! :D

> But... In my case I prefer to store k3d plot as *.k3d file (new feature that I shared above) and on website write few lines of code:

This is an even better solution!

**Comment by artur-trzesiok** [comment]
Hi @Davide-sd I pushed a prototype into devel:

please look at: https://github.com/K3D-tools/K3D-jupyter/blob/devel/docs/source/conf.py

```
def setup(app):
    try:
        app.add_stylesheet('style.css')
    except AttributeError:
        app.add_css_file('style.css')

    app.add_directive('k3d_plot', K3D_Plot)
```

That new directive in Sphinx give a abbility to do something like here:
https://github.com/K3D-tools/K3D-jupyter/blob/devel/docs/source/intro.rst
```

.. k3d_plot ::
   :filename: screenshot.py
   :screenshot:

.. figure:: _static/screenshot.png
   :alt: Dynamic screenshot of K3D plot
   :width: 540px
   :align: center
   :figclass: align-center

   Dynamic screenshot of K3D plot

.. k3d_plot ::
   :filename: snapshot_inline.py
```

flag :screenshot: save a image into _static folder. Without this flag it puts k3d as inline widget (without any iframes). That solution will not work until I will release k3D@2.10.0 at npm (by default snippet will download a correct version of k3d from unpgk.com but I will do that soon. I regenerated k3d docs: https://k3d-jupyter.org/basic_functionality/Mesh.html . You can see here that eveny functionalities like animation works.

This solution is zero-jupyter and zero-ipywidgets. So no more struggle with "save widgets state" in ipynb. I hope this is something that you find as usefull.  Pleaes check the source of k3d docs here: https://github.com/K3D-tools/K3D-jupyter/tree/devel/docs/source/basic_functionality 

Example code for snippet looks like that: https://github.com/K3D-tools/K3D-jupyter/blob/devel/docs/source/basic_functionality/mesh/Mesh03.py

So in our case we need to produce some redundant code like Mesh01/Mesh02/Mesh03 but I'm fine with that in docs.

**Comment by Davide-sd** [comment]
Thanks @artur-trzesiok for your work, really appreciated.

**Comment by artur-trzesiok** [comment]
@Davide-sd https://k3d-jupyter.org/showcase/ - all images and snapshot inside are fully dynamic (make clean & make html)
