### ISSUE TITLE
How to change the size of displayed widgets?

### ISSUE THREAD

**Issue by jatentaki** [K3D-tools/K3D-jupyter#302]
Dzień dobry,

I would like to change the size of the plots generated with k3d and displayed in jupyter lab. Currently they occupy only a small extent of height of my display:
![image](https://user-images.githubusercontent.com/22394841/128890496-6588bf6e-42c6-4e61-b993-af09f9bea2c1.png)

Googling revealed that I can use `pywidgets.Layout` to modify the layout of the _widget_, however it doesn't seem to affect the extent of the actual plot within that widget (notice how the plot gets clipped on the bottom if I pan it too far down).
![image](https://user-images.githubusercontent.com/22394841/128890756-3e5b7ecb-10f6-4ddc-bde3-3f283df45064.png)

What is the best way to increase the extent of the plot in those cases?

Thank you for this wonderful tool!

**Comment by artur-trzesiok** [comment]
Dear Michał,

Thanks for your kind words. Please try pass height argument to k3d.plot and put number of pixels that you want to have.

**Comment by jatentaki** [comment]
Thanks a lot, I feel a bit stupid having missed that in the documentation...
