### ISSUE TITLE
Show mesh surfaces + wireframe together from the same mesh

### ISSUE THREAD

**Issue by ishomam** [K3D-tools/K3D-jupyter#304]
It would be nice if one can also show both the mesh surfaces and the wireframe together. Currently, the behaviour is either show this or that, but sometimes it's useful to see both (maybe with different colors). Like here:
![image](https://user-images.githubusercontent.com/39214874/131390223-374e5498-eaef-4d9c-9d90-64e28310aec8.png)

To show both currently I'm adding the same mesh two times which is not efficient.

Any thoughts on this would be appreciated.

Thanks!

**Comment by artur-trzesiok** [comment]
I did the same trick in my case :). I'll check how hard that will be

**Comment by artur-trzesiok** [comment]
new k3d.lines are dedicaded to do that. Still that reqiure adding two objects to scene but that is better because wireframes in k3d.lines can have shader='simple' or shader='thick' or shader='mesh' so it is much more flexible compare to just wireframe that we have right now.

**Comment by artur-trzesiok** [comment]
Please download new version of k3d@2.13.0:
- https://pypi.org/project/k3d/
- https://anaconda.org/conda-forge/k3d

It should be there :)

**Comment by ishomam** [comment]
Great, thanks! I have the k3d.lines now ;)

**Comment by artur-trzesiok** [comment]
:)

**Comment by ishomam** [comment]
Actually, after I updated to 2.13.0, the k3d widget is unfortunately not showing in Jupyter, could you please tell me what could be the reason or check it?

![image](https://user-images.githubusercontent.com/39214874/169244930-0dac8e50-2fe0-4731-98bf-667cd188d46e.png)


Thanks!
