### ISSUE TITLE
Port k3d to plotly dash?

### ISSUE THREAD

**Issue by esalehim** [K3D-tools/K3D-jupyter#306]
K3D is an amazing tool for jupyter notebooks. How feasible is it to try to port k3d as a plotly dash component?
If its doable, I can probably put some time on it myself. Any thoughts?

**Comment by artur-trzesiok** [comment]
esalehim - do you know more about dash compontents? Or do you have source of any ipywidgets-based library that is ported into plotly dash compontent in open soruce to check how many modifications they need to apply?

**Comment by esalehim** [comment]
dash components are build on top of react. Wrapping k3d in react is a too much work I assume...
closing this ticket
