### ISSUE TITLE
Changing an attribute of an object resets the camera

### ISSUE THREAD

**Issue by martinal** [K3D-tools/K3D-jupyter#31]
To reproduce (with current devel branch, 3142b54b4040103ba5782f31f4da0b006f45f281)
- open `examples/line.ipynb`
- run the first cell
- zoom in with camera
- click slider widget or run the next cell
The camera resets on both `line.line_width = width` and `line.color = 0xFFFF00`.

**Comment by marcinofulus** [comment]
it is a feature ;-), in the line example: 
plot.camera_auto_fit = False
and probably 
plot.grid_auto_fit = False

will fix the scene.

**Comment by martinal** [comment]
Ok! :)
