### ISSUE TITLE
logarithmic scale colorLegend?

### ISSUE THREAD

**Issue by esalehim** [K3D-tools/K3D-jupyter#311]
How hard is it to add a logarithmic scale colorLegend? some attributes require a log scale legend rather than a linear one

something similar to below screenshot:

![image](https://user-images.githubusercontent.com/44696797/135828168-8d27ff1c-8d8b-48b6-8500-ffe22c2c1784.png)

**Comment by artur-trzesiok** [comment]
@marcinofulus this is actual a good question. Current state is that in k3d everything is "plain". If you want to change logarithmic scale for x axis you simple should apply simple re-compute for x-coordinates. But number of axis/color legend will not match then. 

Can we setup a call or discuss here what will be your sugestions about that? I feel that if we will introduce differents scales that should be generic both for colorlegends and axes (i remember that we had already request for that kind of feature)

**Comment by esalehim** [comment]
Hi, is this finally implemented?
