### ISSUE TITLE
automate screenshot in script

### ISSUE THREAD

**Issue by HumHongeKamyaab** [K3D-tools/K3D-jupyter#315]
I want to save the figure as a PNG file in particular  camera orientation.
While we can set camera using `plot.camera`, I couldn't find something like `plot.save`, so that a png image can be saved using a python script, and we don't have to manually select screenshot from the widget to save the image,

**Comment by youssefassis** [comment]
Hi Artur, 

Thanks for providing this veryuseful visualization library.

I have a problem when I try to take a single screenshot using the exact same code provided in the documentation [here](https://github.com/K3D-tools/K3D-jupyter/blob/main/examples/screenshot_generator.ipynb).
After running this line of code:` plt.fetch_screenshot()` , the output of `plt.screenshot` is empty `''` !!
Do you please have any idea why it didn't work?

Best regards,

**Comment by tgandor** [comment]
Hi Youssef,

this is the old, non-headless screenshot mechanism. For the new mechanism see this example: https://github.com/K3D-tools/K3D-jupyter/blob/main/examples/headless.ipynb

For this example: https://github.com/K3D-tools/K3D-jupyter/blob/main/examples/screenshot_generator.ipynb you need a few things:
- running in jupyter notebook or lab (which you probably do)
- execute cells one by one (not: Kernel -> Restart and run all)
- pause a little after `fetch_screenshot`

or use the generator approach further down in the example.

**Comment by youssefassis** [comment]
Thank you Tgandor, It works using the headless screenshot mechanism.
