### ISSUE TITLE
`camera_fov` argument of `k3d.plot` init function has no effect

### ISSUE THREAD

**Issue by MironLeon** [K3D-tools/K3D-jupyter#316]
```
import k3d
plot = k3d.plot(camera_fov=10.0)
plot
```

Has no effect on the actual FOV used. As you can see in the screenshot, the fov is still set to the default (60.)

![image](https://user-images.githubusercontent.com/89517300/137299751-8789aa67-b849-47dc-80ce-b1915e75cac3.png)

Changing the attribute **after** the plot is displayed does change the fov. 

Tested with k3d==2.11.0

**Comment by artur-trzesiok** [comment]
@MironLeon 

Thanks a lot. Very good bug hunting :). In constructing of k3d (https://github.com/K3D-tools/K3D-jupyter/blob/main/js/src/k3d.js#L306) I miss "camera_fov" parameter :(. But at the same moment I handle change of camera_fov (https://github.com/K3D-tools/K3D-jupyter/blob/main/js/src/k3d.js#L296) thats why it working when you changed it after plot was created.
