### ISSUE TITLE
Embedding using ipywidgets.embed not working properly

### ISSUE THREAD

**Issue by jpomoell** [K3D-tools/K3D-jupyter#320]
I am using k3d in a setting where the user can interact with the k3d.plot via an interface built using ipywidgets. While everything works great in the notebook, I would also like to embed snapshots in html pages, which is causing issues. As an example, in the following

```
import k3d
import k3d.platonic
import ipywidgets as widgets
import ipywidgets.embed as embed

mesh = k3d.platonic.Dodecahedron().mesh
plot = k3d.plot(menu_visibility=False)
plot += mesh

checkbox = widgets.Checkbox(value=True, description="Visible")
widgets.jslink((checkbox, 'value'), (mesh, 'visible'))
widget = widgets.VBox([checkbox, plot])

embed.embed_minimal_html("k3d_embedded.html", views=[widget])
```

the generated html file shows the plot and the checkbox works. However, the usual mouse interaction does not work, e.g. rotating the view does not work. When trying to rotate the view, the browser console reports

`embed-amd.js:69 Uncaught Syncing error: no comm channel defined`

Creating a snapshot of only the plot using `plot.get_snapshot()` works, but I am unsure how to get both the widgets and the plot embedded at the same time. Any help would be very much appreciated!

**Comment by artur-trzesiok** [comment]
Thanks for a feedback. I can reproduce this error. It is in save here:

```
        this.cameraChangeId = this.K3DInstance.on(this.K3DInstance.events.CAMERA_CHANGE, (control) => {
            if ((new Date()).getTime() - self.model.lastCameraSync > 200) {
                self.model.lastCameraSync = (new Date()).getTime();
                self.model.save('camera', control, { patch: true });
            }
        });
```

I don't know why I cannot save this model. For sure we can wrap it in K3D with try/catch to avoid stoping whole process. I will check that and return with outcome!

**Comment by artur-trzesiok** [comment]
Yup! That solves the problem :)

**Comment by marscher** [comment]
I just tried it out, but when I load the generated HTML file (exported via jupyter lab fronted), I just receive a text representation of the objects.
![Screenshot_20220512_144050](https://user-images.githubusercontent.com/170287/168079333-7a539b05-ee5d-4b02-9679-240bff977c61.png)
