### ISSUE TITLE
Weird voxels behavior

### ISSUE THREAD

**Issue by panangam** [K3D-tools/K3D-jupyter#321]
I'm trying to visualize some voxels, but neither `k3d.voxels` nor `k3d.sparse_voxels` seem to work correctly.

When using `k3d.voxels` on a dense grid, the orientation is wrong, and the plot is mirrored. 
```python
print(voxel_grid.shape)
k3d.voxels(voxel_grid)
```
![Screenshot from 2021-12-21 19-49-06](https://user-images.githubusercontent.com/17264683/147032618-2768cdfd-6ab0-46b1-88e3-7dad48799264.png)

When using `k3d.sparse_voxels`, the orientation is correct but the plot is repeated for some reason. 
```python
k3d.sparse_voxels(np.c_[voxel_coords, np.ones(voxel_coords.shape[0])], [384, 255, 12])
```
![Screenshot from 2021-12-21 19-49-30](https://user-images.githubusercontent.com/17264683/147032628-b32f3541-0c0e-4980-a39f-d592783e893d.png)

Here's the data:
[voxel_data.zip](https://github.com/K3D-tools/K3D-jupyter/files/7759874/voxel_data.zip)

Any idea what is going on???

**Comment by artur-trzesiok** [comment]
It is expected order of axis. To learn more please visit https://en.wikipedia.org/wiki/Row-_and_column-major_order

So K3D assumption is that "the fastest" axis is a x-axis.
