### ISSUE TITLE
Snapshots mobile browsers support

### ISSUE THREAD

**Issue by qubvel** [K3D-tools/K3D-jupyter#322]
Hi, thanks for the awesome library!

I have faced with a problem, my `html` snapshots does not work on any mobile devices. The page is loaded correctly, but zooming and rotations are unavailable. Is there any solution for that?

**Comment by artur-trzesiok** [comment]
Hi @qubvel could you share that snapshot with me and tell me what kind of mobile devices do you use (android or ios?)

If the snapshots contain private information pleaes share that on my email: artur.trzesiok@gmail.com

**Comment by artur-trzesiok** [comment]
update: i realize that: `plot.camera_mode = 'orbit'` dosen't work on mobile!

**Comment by qubvel** [comment]
Hi!
Yes, that's my case, changing camera mode to `trackball` works on mobile. Would be happy to see a fix for the `orbit` mode, it is more suitable for my case. Thank you very much for your work!

**Comment by qubvel** [comment]
I have installed the fixed version from the `devel` branch and now it's working with snapshot_type = "full", thank you!
(commit hash b7240ed4681bbe38e07586d6daadb3af35cfc9ea)
