### ISSUE TITLE
screenshot button not working

### ISSUE THREAD

**Issue by HumHongeKamyaab** [K3D-tools/K3D-jupyter#323]
screenshot button in the k3d widget in either jupyter lab / notebook is not working. There is no action/new window on pressing it by mouse.

![image](https://user-images.githubusercontent.com/19993444/147959893-b513f188-0123-4088-93e2-b9368f004e25.png)

versions
k3d : 2.11.0
jupyterlab : 3.2.5
python version : 3.8.10
Ubuntu 20.04.3 LTS

**Comment by artur-trzesiok** [comment]
Hi @HumHongeKamyaab !

I cannot reproduce your issue. Could you provide dump from browser console?

Example:
```
screenshot.js:62 K3D: Screenshot [html]: 1.684 s
screenshot.js:62 K3D: Screenshot [canvas]: 0.698 s
```

**Comment by HumHongeKamyaab** [comment]
It got resolved using Jupyter-lab.
