### ISSUE TITLE
404 GET /static/k3d.js

### ISSUE THREAD

**Issue by nlgranger** [K3D-tools/K3D-jupyter#324]
When installing k3d via pip in a clean conda environment and using jupyter notebook, the plot won't show up and the console reports:

```
[W 12:30:01.933 NotebookApp] 404 GET /static/k3d.js?v=20220104122942 (127.0.0.1) 9.910000ms referer=http://localhost:8888/notebooks/scripts/preview.ipynb
```

k3d works when installed via conda using conda-forge channel.

**Comment by nlgranger** [comment]
Apparently one simply needs to manually enable the jupyter extension:
```
jupyter nbextension install --py --user k3d
jupyter nbextension enable --py --user k3d
```
I'm gonna leave this issue open till the documentation mentions it if you d'ont mind.

**Comment by tgandor** [comment]
Hi Nicolas,
while the commands you mentioned are not necessary in all circumstances (since Notebook 7.x there is a mechanism for auto-installation; I think the conda-forge version also doesn't need it).
However, these commands shouldn't hurt in any case, so I added them to the README. This will be merged to `main` in the next release, so stay tuned.

Also, we were getting questions about this earlier, especially after users upgraded their K3D and got a Python/JS version mismatch. So I also put there a note about upgrade.

**Comment by nlgranger** [comment]
Great, thank you (and thanks for this project too, it works really well and is simple to use).

**Comment by ChHarding** [comment]
Based on 86cucv's comment about running k3d within a docker notebook, I've tried the same but within a colab notebook.

I run` !jupyter nbextension install --py --user k3d` and `!jupyter nbextension enable --py --user k3d` and the validations both show OK.

I then run this code:

```
from k3d.helpers import download
import k3d
plot = k3d.plot()
filename = download('https://upload.wikimedia.org/wikipedia/commons/a/af/Asad_Al-Lat.stl')
plot += k3d.stl(open(filename, 'rb').read())
plot.display()
```
which should give me this:
![image](https://github.com/K3D-tools/K3D-jupyter/assets/19935989/4a664675-83b3-434e-a310-b5be03a9c7d9)

however, I only see this:
![image](https://github.com/K3D-tools/K3D-jupyter/assets/19935989/dd851e44-ca7d-4b7e-be05-b94b47ab4986)

Any idea why the stl doen't get "attached" to the viewer within colab?

**Comment by artur-trzesiok** [comment]
Hi @ChHarding 

As We explain here: https://github.com/K3D-tools/K3D-jupyter?tab=readme-ov-file#google-colab

For Google Colab you need to activate custom widgets and switch k3d to text protocol:

```
import k3d
from google.colab import output

output.enable_custom_widget_manager()

k3d.switch_to_text_protocol()
```

The reason for that is that colab have no support to binary websockets

**Comment by ChHarding** [comment]
Cool!  Thank you very much!

**Comment by ChHarding** [comment]
Thank you but that still doesn't work. I read up on how to activate custom widgets but this might be wrong(?) Here's what I'm doing:

![image](https://github.com/K3D-tools/K3D-jupyter/assets/19935989/73f97f2b-7705-4c9e-907c-2927a7e2b92e)

Any idea what I'm doing wrong?

Thanks!
