### ISSUE TITLE
Automated screenshot issue

### ISSUE THREAD

**Issue by smajee** [K3D-tools/K3D-jupyter#326]
The method for getting automated screenshot outlined in [link](https://github.com/K3D-tools/K3D-jupyter/blob/main/examples/screenshot_generator.ipynb) doesn't work for me. The resulting screenshot has garbage values. The manual screenshot option via the widget still works though.

Note that I am not running jupyter in a browser but in VS Code via remote developement.

**Comment by tgandor** [comment]
Please have a look at headless rendering:
https://github.com/K3D-tools/K3D-jupyter/blob/main/examples/headless.ipynb

You might also like:
https://github.com/K3D-tools/K3D-jupyter/blob/main/examples/snapshots.ipynb

**Comment by artur-trzesiok** [comment]
Hi! Any news with this issue. @smajee did a explanation from @tgandor solve your problem?
