### ISSUE TITLE
Is there any way we can use k3d in flutter, has anyone tried it?

### ISSUE THREAD

**Issue by Arhan13** [K3D-tools/K3D-jupyter#330]
I was working on a mobile application using flutter, and I wanted to use k3d as a visualization library. If yes can anyone explain how?

**Comment by tgandor** [comment]
Tough question -- you're writing in Dart? Well, k3d is for Python and JS. However, K3D snapshots work in mobile browsers, and they can be generated 'headless' (although Python and Jupyter are still a dependency).

So, if your application can have a 'browser widget', which would support OpenGL ES, and you could generate a snapshot (for write-once visualization, which is interactive for viewing) or run Jupyter inside it (for a modifiable scene), it could be possible. Still, this is a very daring idea.
