### ISSUE TITLE
Best practice for adding a js callback feature

### ISSUE THREAD

**Issue by syoels** [K3D-tools/K3D-jupyter#331]
Hi K3D Folks! 
I was wondering how can one add a JS callback to K3D. I noticed that when working from Jupyter lab, the k3d js code isn't taken directly from the repository but rather downloaded and obfuscated via the widgets framework. 

If I want to add a js callback, and write it by myself as a merge-request, 
How would I go about doing that? 
How can I make sure that jupyter serves the modified js code written by me, and not some SVN hosted latest version? 

Thanks a lot in advance!

**Comment by artur-trzesiok** [comment]
Hi @syoels!

That depends on what that callback will do. If callbacks are independence from jupyter lab you can use:

```
cd js
npm i
grunt serve
```

that will open k3d standalone widget with livereload
