### ISSUE TITLE
Grid bounds and scaling

### ISSUE THREAD

**Issue by parkero** [K3D-tools/K3D-jupyter#335]
Hello and thanks for the great library. I have run into the following problem and I was wondering if I could get some insight.

### How to describe the following grid in k3d?
I am attempting to create a grid with the following bounds
```python
xmin, xmax = (-3, 3) # x domain
ymin, ymax = (-3, 3) # y domain
zmin, zmax = (0, 1) # probability of occurrence
```
Visualized as a cube(oid) very similar to: 
*(ignore surfaces)*
<img src="https://user-images.githubusercontent.com/7399144/160671780-f61760ac-f210-49d7-8a8f-e0338b5f7c37.png" width="200" height="200">

I have tried the following (minimized) code sample without success:
```python
import k3d
import numpy as np

xmin, xmax, xres = (-3, 3, 25)
ymin, ymax, yres = (-3, 3, 25)

plot = k3d.plot(grid=[xmin, ymin, 0, xmax, ymax, 1], grid_auto_fit=False)
plot.display()
```
which produces:
![k3dbounds](https://user-images.githubusercontent.com/7399144/160674785-6a0f10da-5f77-468a-a3e3-440ca0f9b54f.png)
which is -1 to 2 on Z instead of 0 to 1 as expected

Any advice?

**Comment by artur-trzesiok** [comment]
K3D have internal prcedure "ensureTwoTicksOnGrids": https://github.com/K3D-tools/K3D-jupyter/blob/main/js/src/providers/threejs/initializers/Scene.js#L61

At this point we cannot control it - it is always enabled.

**Comment by artur-trzesiok** [comment]
Main problem is that without 2 ticks we will lost a information about scale:
![image](https://user-images.githubusercontent.com/5256837/161870270-7bef7d43-d4bb-4c77-817b-3fd0fa950dcc.png)

We have consistent ticks for every axis.

**Comment by artur-trzesiok** [comment]
Prototype of solution:
![image](https://user-images.githubusercontent.com/5256837/161873685-44f8ef98-39e2-4ec8-9a19-3a13922bbfa3.png)

**Comment by artur-trzesiok** [comment]
Please download new version of k3d@2.13.0:
- https://pypi.org/project/k3d/
- https://anaconda.org/conda-forge/k3d

It should be there :)

**Comment by parkero** [comment]
@artur-trzesiok Thant's great! And thank you again for the library.
