### ISSUE TITLE
Wireframe line width when changing screenshot DPI

### ISSUE THREAD

**Issue by ishomam** [K3D-tools/K3D-jupyter#338]
First, thanks for the awesome library.

I was trying to export a high quality image for a graphic which has a wireframe.
To increase resolution I used
`plot.screenshot_scale = 6.0`
However, this produces an image with thin wireframe (because wireframe width is not scaled with the image). Therefore, is there a way to change wireframe width or to scale its width when exporting with higher DPI?
![K3D-1650961305642](https://user-images.githubusercontent.com/39214874/165256685-93cdaec3-d369-4d95-baac-c7f8af5fbf26.jpg)

**Comment by ishomam** [comment]
Or if the screenshot could be taken as vector-graphics-based format such as SVG, this would also be perfect!

**Comment by artur-trzesiok** [comment]
Hi @ishomam 

Svg is not supported. Wireframe is a shortcut to fast displaying and always have line with 1 pixel width. If you want to do wireframe I will intriduce k3d.lines - new primitive in k3d.

**Comment by ishomam** [comment]
Ok, thank you so much for your answer and for working on the new k3d.lines

**Comment by artur-trzesiok** [comment]
Please download new version of k3d@2.13.0:
- https://pypi.org/project/k3d/
- https://anaconda.org/conda-forge/k3d

It should be there :)
