### ISSUE TITLE
Axis helper color convention misalignment 

### ISSUE THREAD

**Issue by district10** [K3D-tools/K3D-jupyter#339]
Most 3d visualization uses XYZ-RGB correspondence in axis helper.
Is the current X/Y/Z-Red/Blue/Green configuration intentional?
How can I configure this?

![image](https://user-images.githubusercontent.com/5262037/166260313-692b0d10-5a35-4bc2-ad8f-141a90f6313a.png)

to

![image](https://user-images.githubusercontent.com/5262037/166260353-be2776aa-69e5-4ae2-a01d-bdb21ae5fe44.png)

reference:

-   https://ux.stackexchange.com/questions/79561/why-are-x-y-and-z-axes-represented-by-red-green-and-blue

**Comment by tgandor** [comment]
Right now it's hardcoded here:
https://github.com/K3D-tools/K3D-jupyter/blob/1b034ddf068e6e89511077b67e539a5267bf6e1d/js/src/providers/threejs/initializers/Scene.js#L13

I don't know if there was a reason for using this color permutation. It's also not OpenCV convention (BGR).
It's easy to change the axisHelper, but this will require updating ~30 MB of unittest references: https://github.com/K3D-tools/K3D-jupyter/tree/main/k3d/test/references

**Comment by district10** [comment]
@tgandor No necessary to change current default color permutation. Yeah, there are different conventions like you said opencv BGR versus common RGB (like in CSS, or packed color `0xff0000`).

Could we add a configuration to dat.gui, and/or scene constructor?

**Comment by artur-trzesiok** [comment]
Hi @district10 

I would like to avoid making a GUI overcrowded. plot property/constructor sounds much better.

**Comment by artur-trzesiok** [comment]
Please download new version of k3d@2.13.0:
- https://pypi.org/project/k3d/
- https://anaconda.org/conda-forge/k3d

It should be there :)
