### ISSUE TITLE
Additional line when using 'simple' shader in k3d.lines

### ISSUE THREAD

**Issue by ishomam** [K3D-tools/K3D-jupyter#348]
First, thank you so much for the new release and the new lines object, it works very well. However, I noticed a small issue.
When using 'simple' shader in k3d.lines, an additional undesired line is created.
This example will generate the problem:
```
plot = k3d.plot()
X_Ia = np.array([
    [   0.     ,    0.     ,    0.     ],
       [ 553.6447 , -970.6123 ,   37.2735 ],
       [-416.0319 , -999.26416,  279.9797 ],
       [ 416.0319 ,  999.26416,  279.9797 ],
       [-553.6447 ,  970.6123 ,   37.2735 ],
       [ 434.9501 ,    0.     ,  246.61386],
       [-434.9501 ,    0.     ,  246.61386]])
I_Fi = np.array([[0, 1, 2],
       [0, 3, 4],
       [0, 1, 5],
       [0, 5, 3],
       [0, 2, 6],
       [0, 6, 4]])
lines = k3d.lines(X_Ia, I_Fi, shader='simple')
plot += lines
plot.display()
```
With ```shader='simple'``` we see the following:

![image](https://user-images.githubusercontent.com/39214874/169351611-b371bf62-f427-44d5-b000-c0796e8cdbbf.png)

Without it, we see the following (which is correct):

![image](https://user-images.githubusercontent.com/39214874/169351652-e6d07b34-199a-4873-8f94-9c81d2fc64ee.png)

For ```shader='mesh'``` the problem is also not there.

Thanks in advance!

**Comment by artur-trzesiok** [comment]
Good spot! I'm working on it

**Comment by artur-trzesiok** [comment]
Please bump k3d to 2.13.1. It should be fixed. It is already on pypi (we are waiting for conda-forge bot)

**Comment by ishomam** [comment]
Thanks for the quick response! I've just upgrade it from conda-forge and it works properly now ;)

**Comment by artur-trzesiok** [comment]
Thanks @ishomam for your feedback!
