### ISSUE TITLE
Does K3D allow the possibility to change the coordinate system?

### ISSUE THREAD

**Issue by flacle** [K3D-tools/K3D-jupyter#358]
In case not, this would add extra value to K3D IMO; assuming the implementation is trivial.

Quoting a random recent blog that has a nice visual overview at the bottom:
> Both Blender and 3ds Max use coordinate system which were common in early 90’s. This convention is typical in architecture. You start modelling from the floor plan which uses X/Y coordinates and then extrude upwards (or downwards,may change if the system is right handed or left handed). This is called as Z-Up(or -Z-Up) coordinate systems. 3D applications like Cinema 4D,Maya,Houdini,graphics APIs and the most game engines use different kind of approach. The screen becomes a 2D plane which uses X/Y coordinates to position flat images, while Z coordinate represents depth in the scene.

![coordinate system per app](https://miro.medium.com/max/1400/1*IWv0KVHPnf_xxL05Vh7oVQ.png)

Ref: https://ahmetyasinburul.medium.com/coordinate-systems-of-3d-applications-guide-ddfa2194ed88

**Comment by artur-trzesiok** [comment]
Hi!

In K3D you can change label of axes:
`k3d.plot(axes=['\\alpha', '\\beta', '\\gamma'])`

So you can transform your (by changing dim order) and use:
`k3d.plot(axes=['x', 'z', y'])`

It is rather workaround than solution. I see extra value here but also [KISS rule](https://en.wikipedia.org/wiki/KISS_principle). Btw how many of sofwares from chart above have option to choose coordinate system in config?
