### ISSUE TITLE
Rename view_matrix attribute of objects to model_matrix?

### ISSUE THREAD

**Issue by martinal** [K3D-tools/K3D-jupyter#36]
Isn't usually the "view matrix" associated with the camera?
In that light it seems like unusual convention to associate a view matrix with each object.
Maybe rename the object matrices to "model_matrix"?

I haven't reviewed whether this is consistent everywhere, just a thought that struck me going through examples.

**Comment by artur-trzesiok** [comment]
Good point. I will change it

**Comment by martinal** [comment]
Looks like this can be closed?
