### ISSUE TITLE
add invisible plot 

### ISSUE THREAD

**Issue by modaresimr** [K3D-tools/K3D-jupyter#362]
I want to add some plots but invisible. However, there is no way to do such a thing. I want to mark it as visible in the control panel.

I found a way to mark the plot invisible but when in the control panel I mark it  as visible it will not be shown

```
plt_line = k3d.line(...)
plt_line.visible=False
plot+=plt_line
plot.display()
```

**Comment by artur-trzesiok** [comment]
Please check pip install k3d==2.14.3

**Comment by artur-trzesiok** [comment]
Please check pip install k3d==2.14.4

**Comment by modaresimr** [comment]
Sorry for the delay I didn't have access to my Jupyter server.
It works perfectly
Thank you
