### ISSUE TITLE
AttributeError: 'Line' object has no attribute 'display'

### ISSUE THREAD

**Issue by Tsingularity** [K3D-tools/K3D-jupyter#368]
* K3D version: 2.14.5
* Python version: 3.9
* Operating System: linux/ubuntu

### Description
I installed k3d using `conda install -c conda-forge k3d` and I can successfully import it in the notebook. However, when I am trying to run the following example in the doc:
```
import k3d
plot = k3d.line([[0, 0, 0],
                 [1, 1, 1]])
plot.display()
```
It got the following error for the display function: `AttributeError: 'Line' object has no attribute 'display'`.

I installed nodejs in my conda env and also enabled nbextention as described in the readme, but the above error still exists.

Could you please take a look at this issue? Huge thanks in advance!

**Comment by Tsingularity** [comment]
i just found that, after remove `.display()`, the plot is displayed in the notebook lol. Just wondering any idea why this could happen?
![image](https://user-images.githubusercontent.com/13026942/182769479-cee8954f-1556-4c56-bbe1-f765e343747d.png)

**Comment by Tsingularity** [comment]
and looks like other type of plot's display() works for me. So I guess the [doc](https://k3d-jupyter.org/user/basics.html)'s first plot example is outdated and misleading?
![image](https://user-images.githubusercontent.com/13026942/182771728-ee9c4319-1a27-4421-baa1-c5bb3c9ff96e.png)

**Comment by tgandor** [comment]
Hi, `line` is an object, which can be displayed on a plot (or multiple plots for that matter).
So it's the `plot` that should be displayed.

Using just a `line` object as Jupyter cell value causes creating of an implicit `Plot`, and displaying it below the cell. This is a convenience feature, normally you should create a `plot` and add objects to it `plot += k3d.line(...)` etc.

When you're done, you can `.display()` the plot, when the scene is ready (and not re-render it after every object added).

**Comment by Tsingularity** [comment]
Thanks for the help!

Just in case someone else encounter the same issue as me, could u please modify the installation [doc](https://k3d-jupyter.org/user/index.html)? Thanks!
![image](https://user-images.githubusercontent.com/13026942/183127961-5093b386-b01a-4197-bdb9-0e93297f39ae.png)
