### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by renefritze** [K3D-tools/K3D-jupyter#373]
The [README](https://github.com/K3D-tools/K3D-jupyter/blob/main/README.md) mentions enabling the extensions. The [docs](https://k3d-jupyter.org/user/index.html) do not mention that. From my understanding the manual enabling should indeed no longer be necessary. Is my understanding correct?

There's also an (I guess orphaned?) https://github.com/K3D-tools/K3D-jupyter/blob/main/postBuild which has the enabling in it.

**Comment by renefritze** [comment]
https://github.com/K3D-tools/K3D-jupyter/blob/main/environment.yml Should also no longer be used after the `binder/` aubdir was added, right?

**Comment by tennysontbardwell** [comment]
Between #371  and this (#373) I had a difficult time debugging. In my env (Debian 11 Docker, newest python/debian/etc) the line `jupyter labextension install k3d` would consistently fail, citing:

```
$ webpack --config webpack.prod.minimize.config.js
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve 'k3d/dist/labplugin' in '/home/admin/venv_/share/jupyter/lab/staging/build'
```

I would have been fine, except I was also trying to deal with #371, and this threw me for a loop

**Comment by renefritze** [comment]
> Between #371 and this (#373) I had a difficult time debugging. In my env (Debian 11 Docker, newest python/debian/etc) the line `jupyter labextension install k3d` would consistently fail, citing:
> 
> ```
> $ webpack --config webpack.prod.minimize.config.js
> [webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve 'k3d/dist/labplugin' in '/home/admin/venv_/share/jupyter/lab/staging/build'
> ```

I also see this in my stack: [full log](https://github.com/K3D-tools/K3D-jupyter/files/9607703/log.txt)

**Comment by oursland** [comment]
I have trouble with and without the labextension commands.  When I perform an install, JupyterLab prompts me to perform a build, which the `k3d` extension always fails as above.

As of this week I also cannot seem to get the notebook extension to work anymore.

**Comment by artur-trzesiok** [comment]
Please try 2.15.0 (https://pypi.org/project/k3d/ for conda-forge we need to wait a little bit). @renefritze contribution should solve that

> https://github.com/K3D-tools/K3D-jupyter/blob/main/environment.yml Should also no longer be used after the `binder/` subdir was added, right?

It should not. I will try to remove it soon.

> The [README](https://github.com/K3D-tools/K3D-jupyter/blob/main/README.md) mentions enabling the extensions. The [docs](https://k3d-jupyter.org/user/index.html) do not mention that. From my understanding the manual enabling should indeed no longer be necessary. Is my understanding correct?
> 
> There's also an (I guess orphaned?) https://github.com/K3D-tools/K3D-jupyter/blob/main/postBuild which has the enabling in it.

I'm not sure. Probably if you are using conda it is not. In case of pip probably enabling extension is mandatory.

**Comment by renefritze** [comment]
While working on #386 I found that both for jupyterlab and classic notebook extensions do not need to be manually enabled .

**Comment by artur-trzesiok** [comment]
Great! So We should remove instructions from readm.md then!

**Comment by artur-trzesiok** [comment]
@renefritze do you think that we can close that issue?

**Comment by renefritze** [comment]
Yeah. Thanks!
