### ISSUE TITLE
HTML snapshot function results in invalid html file

### ISSUE THREAD

**Issue by ghost** [K3D-tools/K3D-jupyter#376]
* K3D version: 2.14.5
* Python version: 3.8.7
* Operating System: Ubuntu 22..04

### Description

Generating html snapshots now results in invalid html, it still seems to contain some escape characters and it will not load in the browser

### What I Did
I uploaded the HTML file with the txt extension, otherwise github complains

[K3D-snapshot-1663682109419.txt](https://github.com/K3D-tools/K3D-jupyter/files/9608257/K3D-snapshot-1663682109419.txt)

```
import k3d
k3d.plot()
```

Click the 'snapshot HTML' button in the menu

Resulting HTML

**Comment by artur-trzesiok** [comment]
Very good spot! That is a regression for sure.

**Comment by artur-trzesiok** [comment]
Btw snapshots generated from python level works fine:
```
with open("snapshot.html", "w") as f:
    f.write(plot.get_snapshot())
```

I will catch js error

**Comment by renefritze** [comment]
Uhm, so I was pretty sure that with the `?raw` attached the javascript load would result in a 404. But maybe we actually fixed an underlying source for that and the `raw` was just incidental.

**Comment by artur-trzesiok** [comment]
> Uhm, so I was pretty sure that with the `?raw` attached the javascript load would result in a 404. But maybe we actually fixed an underlying source for that and the `raw` was just incidental.

That is fine! I should catch that ealier. Snapshot in k3d can be done in python level and pure js level. In second option k3d have to take own source code. But to keep it smaller I embed sourcecode in snapshot compressed by flatten and I need requirejs too in "bootload" code. Boundled k3d contain both packages but...it is kind of problem "unzip.zip" ;)
