### ISSUE TITLE
Arrowhead tips should be adjusted with increasing line width

### ISSUE THREAD

**Issue by martinal** [K3D-tools/K3D-jupyter#38]
To see the problem, open `vector_animation_k3d.ipynb`, run the first cell and then set
```
vector_plot.line_width = 4
```
The arrow tips need some adjustment.

**Comment by artur-trzesiok** [comment]
please take into account that line width param is quite deprecated (source: https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/lineWidth).

**Comment by artur-trzesiok** [comment]
I added new parameter to vectors and vector_fields - https://github.com/K3D-tools/K3D-jupyter/blob/devel/examples/vector.ipynb

**Comment by martinal** [comment]
Ok. In high resolution a single line will be hard to see, so the ideal solution here is to improve the array glyph to not use a line in the first place but an actual cylinder surface with customizable resolution, like the CylinderGeometry in three.js. Maybe it should be an option, as this will be more costly to render of course, but glyph plots become useless if there are too many arrows in the picture anyway.

**Comment by artur-trzesiok** [comment]
That's true. Other option is use pixel shader to render tubes on quad using math like in case of points (our points object have full z-buffer + lighting and are composed by only 2 triangles)

So because you created #40 i think this issue can be closed. @marcinofulus  ?

**Comment by martinal** [comment]
Good point, shaders would allow the highest quality for sure.

**Comment by vidartf** [comment]
This three.js PR might be good to track / checkout as well: https://github.com/mrdoob/three.js/pull/11349
