### ISSUE TITLE
A fixed view

### ISSUE THREAD

**Issue by Depth2World** [K3D-tools/K3D-jupyter#381]
Hi there,
Appreciate your brilliant work! 
Now, I want to plot a 3d volume.
How can I have an fixed view when I run the code?

**Comment by Depth2World** [comment]
>Yes, I found that. The attributes are boolean. 
I mean that I need a special view for showing the volume. How can I fix the view?

**Comment by RossBencina** [comment]
I think you mean "specific view" not "special view" -- very different!

You can set the camera matrix. For example, for a top down view I have:

```
cameraMatrix_= [
              xc, yc, zmax + 250,  
              xc ,  yc,  zc,
              0.0, 1.0, 0.0]
plot.camera = cameraMatrix_
```

**Comment by artur-trzesiok** [comment]
Hi @RossBencina show probably the best solution
plot.camera = [
x_camera_, y_camera, z_camera,
x_target, y_target, z_target,
x_up, y_up, z_up]

camera - camera position in space
target - target where camera is pointed in space
up - normal vector showing where is direction of up  in projected view (control rotation of camera around line camera,target)

@Depth2World did that solve your problem?

**Comment by artur-trzesiok** [comment]
any updates?
