### ISSUE TITLE
Model class 'PlotModel' from module 'k3d' is loaded but can not be instantiated

### ISSUE THREAD

**Issue by RonaldEnsing** [K3D-tools/K3D-jupyter#383]
K3D version: 2.14.5
Python version: 3.10.6
Operating System: Ubuntu 20.04

### Description

I am trying to show a k3d plot in a jupyter notebook.

### What I Did

I used the following conda `environment.yml`:
```
name: k3d
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - k3d
```

Created the env with: `conda env create -f environment.yml`

Installed and enabled the nbextensions:
```
$ jupyter nbextension install --py --user k3d
$ jupyter nbextension enable --py --user k3d
```

Started the notebook with `jupyter notebook`.

and executed the following code:
```
import numpy as np
import k3d
plot = k3d.plot()
plot += k3d.points(np.random.randn(100), point_size=0.1)
plot.display()
```

### Web console log / python logs

The code runs, but instead of showing the plot I get an error:

`Model class 'PlotModel' from module 'k3d' is loaded but can not be instantiated`

![image](https://user-images.githubusercontent.com/8299064/199723778-992610d7-919b-48db-a1d6-7f645a26a8e5.png)

**Comment by hboekema** [comment]
I have the same issue when following these steps.

**Comment by CRTejaswi** [comment]
Facing the same issue. Browser shows a "Host not attached" error.

<img src="https://user-images.githubusercontent.com/24400066/200077296-ca9e4470-f305-4437-8311-25f5fccc78c2.png" height="480">

**Comment by RonaldEnsing** [comment]
I don't think this is a duplicate of #371.

The error of this issue is:
> Model class 'PlotModel' from module 'k3d' is loaded but can not be instantiated

The error of #371 is:
> Failed to load model class 'PlotModel' from module 'k3d'

**Comment by anilkul98** [comment]
I have exactly the same problem even after downgrading the `ipywidgets` and `jupyterlab-widgets`. Is there any other solution. 

My Setting Details:
ubuntu 22.04 LTS
python 3.7

**Comment by artur-trzesiok** [comment]
Please try 2.15.0 (https://pypi.org/project/k3d/ for conda-forge we need to wait a little bit). @renefritze contribution should solve that

**Comment by artur-trzesiok** [comment]
any updates?
