### ISSUE TITLE
Objects empty

### ISSUE THREAD

**Issue by poro56** [K3D-tools/K3D-jupyter#385]
* K3D version: Current (2.14.5)
* Python version: 3.7.15
* Operating System: Linux (Colab); Kernel Version 5.10

Description:

I tried to execute K3D in Google Colab. I read the older issue earlier, but there was nothing mentioned like this.
Everything runs through, and the K3D Panel and Plot Volume are displayed.
But the objects are missing, and the K3D Panel says the Objects are Empty.

Further:

I verified that the plot contains the object ids.

I tried the standard examples with the Cow or the triangle, too.

Is this a limitation still in Google Colab, or did I make any mistakes?

Thank you in Advance.

**Comment by artur-trzesiok** [comment]
Can you share more detail what do tou mean by "objects are missing"? Any screenshot and code example will be helpfull

**Comment by artur-trzesiok** [comment]
I have the same results. I cannot spot even a websocket connection in colab

**Comment by artur-trzesiok** [comment]
I checked sample code in colab:
```

import ipywidgets as widgets

slider = widgets.IntSlider(20, min=0, max=100)
slider
```

It's look like they use active pooling rather than WS. K3D use binary websocket to speed up things. Probably that is a reason why it's hard to run k3d in colab. Maybe there is a option to fallback to base64 if we somehow can detect that we are in colab/no binary ws mode. Maybe someone tried something like that before?

**Comment by artur-trzesiok** [comment]
Good news @poro56 !

Experimental COLAB support is done: 
https://colab.research.google.com/drive/1aZd9vvPJBZzlX5bmaAIp8eE9f_0c3IaS?usp=sharing

**Comment by iubr** [comment]
It seems that unfortunately this issue is back... I have just tried the Google colab and the Objects are empty:

![Image](https://github.com/user-attachments/assets/2d791b5a-a414-4101-9822-e511430a06b3)
