### ISSUE TITLE
side='both' for `k3d.factory.mesh` does not seem to take effect

### ISSUE THREAD

**Issue by BALOGHBence** [K3D-tools/K3D-jupyter#392]
* K3D version: 2.14.5
* Python version: 2.14.5
* Operating System: Windows 11

### Description

The parameter side='both' does not have an effect on the results for the example at the bottom of the page here:
http://k3d-jupyter.org/reference/factory.mesh.html

### What I Did

```
import k3d
import numpy as np
from k3d.colormaps import matplotlib_color_maps
from matplotlib.tri import Triangulation

n_radii = 8
n_angles = 36

radii = np.linspace(0.125, 1.0, n_radii, dtype=np.float32)
angles = np.linspace(0, 2 * np.pi, n_angles, endpoint=False, dtype=np.float32)[..., np.newaxis]

x = np.append(np.float32(0), (radii * np.cos(angles)).flatten())
y = np.append(np.float32(0), (radii * np.sin(angles)).flatten())
z = np.sin(-x * y)

vertices = np.vstack([x, y, z]).T
indices = Triangulation(x, y).triangles.astype(np.uint32)

plt_mesh = k3d.mesh(vertices, indices,
                    color_map=matplotlib_color_maps.Jet,
                    attribute=z,
                    color_range=[-1.1, 2.01],
                    side='both')

plot = k3d.plot()
plot += plt_mesh
plot
```

One side is OK:
![image](https://user-images.githubusercontent.com/25981557/207166534-6c399ef7-d361-4f1b-978e-2f5fdda9f081.png)
The other side is not rendered:
![image](https://user-images.githubusercontent.com/25981557/207166632-cff77c1c-66a9-4019-8b9b-5607f7db3033.png)

**Comment by artur-trzesiok** [comment]
https://k3d-jupyter.org/reference/factory.mesh.html?highlight=double

**Comment by artur-trzesiok** [comment]
Hi! Please check a 2.15.3 version of k3d. It is already available :)
