### ISSUE TITLE
Minor grid lines are not visible

### ISSUE THREAD

**Issue by Davide-sd** [K3D-tools/K3D-jupyter#393]
* K3D version: 2.14.5
* ipywidgets: 7.7.1
* notebook: 6.5.2
* Python version: 3.10.6
* Operating System: Ubuntu 22.04
* Nvidia Driver: 515.86.01

### Description

I've just started using a new machine that comes with an nvidia RTX 3060. It seems like the minor grid lines are not rendered.

![Screenshot 2022-12-12 at 23-11-40 Untitled24 - Jupyter Notebook](https://user-images.githubusercontent.com/9921777/207166974-398467a5-58bf-4103-9898-932ad47362ac.png)

However, if I lower the opacity of the mesh, then they become visible underneath the mesh:

![Screenshot 2022-12-12 at 23-11-24 Untitled24 - Jupyter Notebook](https://user-images.githubusercontent.com/9921777/207167095-a87995bf-bff5-4258-8a2d-d319ddee0327.png)

Note that if I take a PNG screenshot, they will be visible.

![K3D-1670882998161](https://user-images.githubusercontent.com/9921777/207168023-f63bcfbd-894c-41d3-a028-4bdeae620c9e.png)

I'm wondering if this is a driver related issue, if anyone experienced something similar and eventually how to fix it?

### Web console log / python logs

```
K3D: (UNMASKED_VENDOR_WEBGL) NVIDIA Corporation [Renderer.js:64:12](webpack://k3d/src/providers/threejs/initializers/Renderer.js)
K3D: (UNMASKED_RENDERER_WEBGL) NVIDIA GeForce GTX 980/PCIe/SSE2 [Renderer.js:65:12](webpack://k3d/src/providers/threejs/initializers/Renderer.js)
K3D: (depth bits) 24 [Renderer.js:66:12](webpack://k3d/src/providers/threejs/initializers/Renderer.js)
K3D: (stencil bits) 8 [Renderer.js:67:12](webpack://k3d/src/providers/threejs/initializers/Renderer.js)
K3D: Object type "Mesh" loaded in:  0.287 s [Loader.js:61:32](webpack://k3d/src/core/lib/Loader.js)
```

**Comment by artur-trzesiok** [comment]
Hi @Davide-sd 

It is hard to understand this issue

![image](https://user-images.githubusercontent.com/5256837/208579237-8334f7ad-0a3a-4339-850f-a8e03a0e8312.png)

It's look like kind of...problem with display. Do you use extra bright color profile of something like that? The hint that line under a mesh is visible lead to that guess. Really! Even on your screenshots in github I see the lines. Can you open this issue on different monitor (ex. you mobile phone?)

btw. very pretty mesh with beautiful lighting :)

**Comment by Davide-sd** [comment]
> It's look like kind of...problem with display.

Indeed it was. With the old machine I was using a DVI cable to connect the monitor to the graphic card. With the new one I'm using an HDMI cable. Turns out that the display setting was **RGB HDMI PC Range** 16-255 rather than 0-255. Now I'm able to see them again.

Thank you very much for helping me! :)
