### ISSUE TITLE
Bump ipywidgets version

### ISSUE THREAD

**Issue by agoose77** [K3D-tools/K3D-jupyter#396]
It looks like I might accidentally have lowered the lower bound on `ipywidgets`. Do we need to bump it to `7.0.1`?

https://github.com/K3D-tools/K3D-jupyter/blob/391b1136649df375820aaacecc5363a678404138/pyproject.toml#L29

**Comment by artur-trzesiok** [comment]
I dont know. It's works  to me.

**Comment by artur-trzesiok** [comment]
@agoose77 I will leave it as it is. I feel that k3d 2.15.2 is ok and works. If somebody rise issue with ipywidgets problem we can bump it.
