### ISSUE TITLE
screenshots or it didn't happen! 

### ISSUE THREAD

**Issue by mgaitan** [K3D-tools/K3D-jupyter#4]
t's what everybody is looking for the first time

**Comment by artur-trzesiok** [comment]
We will add some screenshots or even demo. Meanwhile you can look at referenace image from tests:
https://github.com/K3D-tools/K3D/tree/master/app/test/reference

**Comment by bollwyvl** [comment]
Beyond the screenshots (just toss some of those in the README, or make a notebook with them, perhaps) building a [binder](https://github.com/binder-project/binder) definition of a minimal working environment would be fantastic. You can see more on [mybinder.org](http://mybinder.org/)

Likely, this would need a [custom Dockerfile](
https://github.com/binder-project/example-dockerfile) file to handle your build step.

When you're done, this badge [![Binder](http://mybinder.org/badge.svg)](http://mybinder.org/repo/K3D-tools/K3D-jupyter) would link to a live, running kernel where a prospective user could try your stuff out.

**Comment by marcinofulus** [comment]
https://hub.docker.com/r/korniichuk/scipy-k3d-notebook/

**Comment by bollwyvl** [comment]
@marcinofulus that's great!

Binder goes the step further, and hosts the thing without requiring a >1gb to your computer :)

**Comment by artur-trzesiok** [comment]
Thanks to bollwyvl we have binder so screenshots are not needed.
