### ISSUE TITLE
Click callback functions

### ISSUE THREAD

**Issue by DeepaMahm** [K3D-tools/K3D-jupyter#409]
Hello @artur-trzesiok ,

This is a follow-up to the previous question on implementing click callback functions

We have network layouts like the below created using `spheres` and `lines` in `vedo` which supports vtk.

![image](https://user-images.githubusercontent.com/29662579/210135520-a9d89b62-92cf-485e-9539-c4fde6e92033.png)

https://github.com/marcomusy/vedo/issues/334 .

I understand we could use `k3d.points` and `k3d.lines` to generate similar networks but add click_callback functions 
are not supported for points and lines at the moment.

I'm trying to understand if there are alternate ways to do this. For instance, would it be possible to use the click_callback functions in `k3d.mesh` if we export the network geometry as mesh object from `vedo` and import the mesh file in `k3d` ?

I also had a look at [BVH](https://github.com/gkjohnson/three-mesh-bvh) you mentioned in the previous post. I would like to know if there is a python implementation of this module. Or if there are other python modules that support click_callback functions for points and lines, could you please give some suggestions?

Thanks a lot for your time and kind attention

Wishing you a Happy New Year!
Deepa

**Comment by DeepaMahm** [comment]
Hi @artur-trzesiok ,

This is a kind reminder.

**Comment by DeepaMahm** [comment]
Hello @artur-trzesiok, 

May I know if it would be possible to offer support for the use case shared above? The use case currently involves ~1000 points.

**Comment by artur-trzesiok** [comment]
Hi @DeepaMahm 

I want to make sure - you need click_callbacks for point or also for lines?

**Comment by artur-trzesiok** [comment]
Hi! Please check a 2.15.3 version of k3d. It is already available :)
