### ISSUE TITLE
Add an abstraction for transforms

### ISSUE THREAD

**Issue by martinal** [K3D-tools/K3D-jupyter#41]
Here's a suggestion for a design change and/or enhancement.
I think it will make the framework much more flexible at a fairly low cost.

The association of model_matrix (formerly view_matrix) with each object is a pretty low level feature and leaves a lot of both power and responsibility up to the user in terms of placing objects in the scene.

Traditionally scene graphs are used to position objects and groups of objects relative to each other, but K3D uses a flat list of objects which does have its merits in terms of simplicity.

If, instead of having a `model_matrix` attribute, each object had a `transform` attribute, which is a reference to an instance of e.g. a `Transform` class (widget), then one transform can be shared by many objects, and changes to that transform can automatically be propagated to the relevant objects.

If the `Transform` class has a reference to a child transform, we can effectively get back the composability of a full scene graph while keeping the objects in a flat list.

Example python/pseudo-code:
```
class Transform(Widget):
    translation = array((3,))  representing translation
    rotation = array((4,))  representing quarternion
    scaling = array((3,))  representing scaling
    custom = 4x4 array defaulting to identity
    child = Instance(Transform)  allowing null

    def compute_matrix(self):
        "Compose transformations, for use on python side (client side duplicates this)."
        T = compute_translation_matrix(self.translation)
        R = compute_rotation_matrix(self.rotation)
        S = compute_scaling_matrix(self.scaling)
        H = self.custom
        C = self.child or identity
        M  = T * R * S * H * C
        return M
```

The translate/rotate/scale options are for more convenient construction of the matrix, the custom matrix is an escape hatch for full flexibility (could for example be used to set up a custom projection to a plane), and the child reference is what makes it possible to compose these transforms like a standard scene graph.

Then you can setup e.g. a shared rotation transform and separate translations of subfigures, then update the rotation and have the effects propagate:
```
R = K3D.transform(rotate=[...])

T00 = K3D.transform(translate=[-10,-10,0], child=R)
T10 = K3D.transform(translate=[+10,-10,0], child=R)
T01 = K3D.transform(translate=[-10,10,0], child=R)
T11 = K3D.transform(translate=[+10,10,0], child=R)

plot += K3d.someobject(..., transform=T00)
plot += K3d.someobject(..., transform=T10)
plot += K3d.someobject(..., transform=T01)
plot += K3d.someobject(..., transform=T11)

R.rotate = [...]  # propagates to Txy and to objects in plot
```

What do you think?

**Comment by artur-trzesiok** [comment]
Nice idea and well described 👍 . We had that improvement in mind year ago. I would like to have it in K3D.

My sugesstion:
- keep very simple api w defining xmin,xmax,ymin,ymax,zmin,zmax (this is also a helper to produce modelMatrix)
- keep raw model_matrix possibility to pass matrix to K3D to not force someone to use our K3D.transform method or add to Transform class method "fromArray"

**Comment by martinal** [comment]
The `custom` field is a matrix that can be used in place of the existing model_matrix. Maybe the factory functions can silently translate a `model_matrix` argument to a `Transform(custom=model_matrix)` to preserve compatibility?

**Comment by martinal** [comment]
> keep current very simple api defining xmin,xmax,ymin,ymax,zmin,zmax (this is also a helper to produce modelMatrix)

I'm not sure I understand this. What does specifying xmin...zmax do exactly?

You're right about parent vs child. Or maybe it should be called something that makes it clear that the parent is applied first, i.e. 'pretransform' (not quite happy with that name either).

However my design above is not quite the same as a regular scene graph, since a child can only have one parent, while in a full scene graph you can add an object to multiple parents.

If instead the `Group` (not currently exposed to the user?) can have a transform, I guess we'll recover a regular scenegraph?

I still think allowing transforms to have parents solves for example the use case above neater than using groups would, i.e. rotating multiple objects within their own model space using a shared rotation transform _before_ translating them to place them apart. Consider how to do that with groups:

```
R = K3D.transform(rotate=[...])

a = K3D.someobject(..., transform=R)
b = K3D.someobject(..., transform=R)
c = K3D.someobject(..., transform=R)
d = K3D.someobject(..., transform=R)

T00 = K3D.transform(translate=[-10,-10,0])
T10 = K3D.transform(translate=[+10,-10,0])
T01 = K3D.transform(translate=[-10,10,0])
T11 = K3D.transform(translate=[+10,10,0])

plot += K3d.group(a, transform=T00)
plot += K3d.group(b, transform=T00)
plot += K3d.group(c, transform=T00)
plot += K3d.group(d, transform=T00)

R.rotate = [...]  # propagates to objects in plot
```
vs the original from above
```
R = K3D.transform(rotate=[...])

T00 = K3D.transform(translate=[-10,-10,0], child=R)
T10 = K3D.transform(translate=[+10,-10,0], child=R)
T01 = K3D.transform(translate=[-10,10,0], child=R)
T11 = K3D.transform(translate=[+10,10,0], child=R)

plot += K3d.someobject(..., transform=T00)
plot += K3d.someobject(..., transform=T10)
plot += K3d.someobject(..., transform=T01)
plot += K3d.someobject(..., transform=T11)

R.rotate = [...]  # propagates to Txy and to objects in plot
```

**Comment by tgandor** [comment]
OK, now there is a workable situation - the transform can be either passed (like in above specifications) or defined using keyword arguments to the functions from the `k3d` module.

Now this issue only needs an ilustrative example (docstrings are there, see `k3d.transform.process_transform_arguments`).
