### ISSUE TITLE
Playwright for headless plotting / screenshots

### ISSUE THREAD

**Issue by MariusCausemann** [K3D-tools/K3D-jupyter#414]
Hi,
I recently rewrote the headless functionality of k3d to use playwright (https://playwright.dev/python/) instead of selenium, mostly because it automatically handles the setup of chrome + chromedriver. If there is interest in that, I could prepare a PR for it. 
Best,
Marius

**Comment by artur-trzesiok** [comment]
That is interesting. Did you make sure that solution works on linux/win32/mac?

If yes - I would like to incorporate that to k3d, sure!

**Comment by MariusCausemann** [comment]
I use linux and haven't tested any other OS, but playwright supports win32/mac, so I assume it should work! I see K3D runs github actions on different OS, so I could prepare the PR and see if problems pop up?

**Comment by artur-trzesiok** [comment]
@MariusCausemann sure! If you can that will be benefitial for whole k3d community.

**Comment by artur-trzesiok** [comment]
@MariusCausemann ?

**Comment by artur-trzesiok** [comment]
I'm closing a issue because of long silent here
