### ISSUE TITLE
Consider splitting Factory out of K3D class

### ISSUE THREAD

**Issue by martinal** [K3D-tools/K3D-jupyter#42]
Tab completion on the K3D object includes lots of names from the widget base class, a situation which would be much better if the factory part was available as a separate object.

What is really the advantage of having Factory as a base class of K3D?

What is really the advantage of making Factory a class in the first place?

Having a collection of factory functions can also be achieved by placing them in a submodule.

**Comment by artur-trzesiok** [comment]
Good spot. We have a lot of technical debt in python part. 

@tgandor please consider this task during fight with Python part refactor #26, ok?

**Comment by artur-trzesiok** [comment]
Probably commit https://github.com/K3D-tools/K3D-jupyter/commit/995a03feba4c5e75be8db9c6156e63cce75c9fb8 cover this issue. @tgandor please review it and decide.

**Comment by tgandor** [comment]
Yes, this is fixed in version 2.1.0 (currently on devel branch).
`import k3d`
`points = k3d.points(...)` - this is now a normal function in module, no inherited classmethods.
