### ISSUE TITLE
Grids disappear when using `grid_auto_fit=False`

### ISSUE THREAD

**Issue by panangam** [K3D-tools/K3D-jupyter#429]
* K3D version: 2.15.3
* Python version: 3.10.11
* Operating System: Ubuntu

### Description

When creating a plot with `k3d.plot(grid_auto_fit=False)` in JupyterLab, the grids disappear. The plot window is just a blank white window.
When using just `k3d.plot()` or `k3d.plot(grid_auto_fit=True)`, grids display as normal. 
Testing on Firefox 115.0.2 (64-bit). 

### What I Did

```
k3d.plot(grid_auto_fit=False)
```

### Web console log / python logs

```
K3D: (UNMASKED_VENDOR_WEBGL) Intel 573.8ab2cfe6c0651f67cce0.js:1:198293
K3D: (UNMASKED_RENDERER_WEBGL) Intel(R) HD Graphics 573.8ab2cfe6c0651f67cce0.js:1:198377
K3D: (depth bits) 24 573.8ab2cfe6c0651f67cce0.js:1:198465
K3D: (stencil bits) 8 573.8ab2cfe6c0651f67cce0.js:1:198527
```

**Comment by oursland** [comment]
I have just encountered this as well.  Plots and other actions all work as expected, but nothing seems to bring the grid back.

**Comment by artur-trzesiok** [comment]
Good catch! empty scene is a special case but for sure very popular 👍 . I will fix it
