### ISSUE TITLE
Consider renaming the project

### ISSUE THREAD

**Issue by martinal** [K3D-tools/K3D-jupyter#43]
Sorry if you feel attached to the name! But...

Searching for K3D on google gives lots of hits on 3D software, but not this project.
The links all relate to an old project for 3D modeling found here:
https://github.com/K-3D/k3d

They already own the k3d name in Ubuntu:
```
martinal:~$ apt search k3d
Sorting... Done
Full Text Search... Done
k3d/xenial 0.8.0.5-1 amd64
  3D modeling and animation system, binary files

k3d-data/xenial,xenial 0.8.0.5-1 all
  3D modeling and animation system, data files
```

It's easier to rename now than later.

**Comment by artur-trzesiok** [comment]
https://martinfowler.com/bliki/TwoHardThings.html

I'm open for changes.

**Comment by artur-trzesiok** [comment]
We will decided to use name "k3d-jupyter" on pypi. I think we should consider to close this issue. @marcinofulus
