### ISSUE TITLE
Extra grid space around high aspect data

### ISSUE THREAD

**Issue by evanmayer** [K3D-tools/K3D-jupyter#431]
* K3D version: 2.16.0
* Python version: 2.16.0
* Operating System: Ubuntu 22.04.3 LTS

### Description

When plotting data that covers a high aspect ratio volume in x,y,z, the grid has extra space around the data.

I would like the grid to conform to the volume's bounds specified by the `bounds` kwarg, or allow manual control, so that the visualization of the data is comprehensible to the viewer.

### What I Did

Here is a minimal example that exhibits the problem. `data` has shape similar to my data. The bounds of the data have an aspect ratio similar to that of the data cube I'm working with (astronomical spectral data cube: right ascension, declination, frequency). By inspection, I believe the data displayed in the plot axes (the "grid") has the span in x,y,z as specified.

```python
data = np.random.random((10, 10, 60))
ret = k3d.volume(
    data,
    bounds=[
        -0.003,0.003,
        -0.003,0.003,
        .7,1.4
    ],
)
plot = k3d.plot()
plot += ret
plot.display()
```

![image](https://github.com/K3D-tools/K3D-jupyter/assets/17206559/7a71b2ce-c33f-41af-9d46-50d7b141fd2a)

If I try to explicitly change the plot axes limits by doing

```python
[...]
plot = k3d.plot()
plot.grid=[
    -0.003,0.003,
    -0.003,0.003,
    .7,1.4
]
plot += ret
plot.display()
```

I get the same result, which seems wrong. I expected this to work somewhat like `matplotlib` or any number of other plotting libraries, where directly specifying axes limits was possible. I understand that there may be some default behavior for the grid size to be different than what is specified for "aesthetic reasons," but not being able to override this is frustrating, and the result is aesthetically worse.

I have tried every combination of `plot()` args `grid_auto_fit`, `grid=[x0, y0, z0, x1, y1, z1]`, `volume()` args `bounds`, and `scaling` I can think of, and the above is my best result. 

### Web console log / python logs

N/A

Thanks for making this library! The volume rendering results and speed are great, I'd just like to know how to have a little more control over it.

**Comment by GiudiceVitor** [comment]
Any progress on this issue? I've been facing the same problem, where manually setting the bound of the grind doesn't seem to change it

**Comment by artur-trzesiok** [comment]
I get your point. I believe that grid should always have squares on themself to have consistency in each axis.

Grid in k3d have two types of lines - for minorScale and majorScale (that looks visually good). majorScale/minorScale = 10 (always)

Right now K3D force a grid to have a least size of 2 majorScale in each axis.

for your code:

`size of scene = {x: 0.006, y: 0.006, z: 0.7}`

So:

```
majorScale = 0.1 # formula: 10 ** ceil(log10(max(0.006, 0006, 0.7))) / 10
minorScale = 0.01
```

I can change:
_Right now K3D force a grid to have a least size of 2 majorScale in each axis._
to:
_Right now K3D force a grid to have a least size of 2 minorScale in each axis._

Results will be like that:

![image](https://github.com/K3D-tools/K3D-jupyter/assets/5256837/1c479bcd-1389-46ee-b46a-e450f9f8da31)

Do you feel that this is a better solution? @marcinofulus @GiudiceVitor

**Comment by GiudiceVitor** [comment]
I feel my point is a bit different: I have a 128x128x128 cube, and I would like to see just that (or have the power to manually change the grid bounds), but it always shows up to 180 in every direction:

![image](https://github.com/K3D-tools/K3D-jupyter/assets/76233446/4e5205c5-d520-448e-adc1-8558125ce7f9)

So far, I've been trying to set the grid bound, by setting `grid=[x0, y0, z0, x1, y1, z1]` or changing the `bound` arg, just like @marcinofulus, but to no effect. If I print the grid argument of the plot, it shows (0,128,0,128,0,128), but the display shows differently.

Maybe i'm missing something?

OBS: Btw, great library! Thanks!

**Comment by GiudiceVitor** [comment]
I understand with your comment that the grid is forced to have at least 2 majorScales on each axis (in my case the major scale is 100). I feel like maybe if I manually change the bound argument, the majorScale should be rescaled to half the bound (for example, 64 in my case), so it is still visually pleasing, but in conformity with my manual bounds. Does it feel like a good solution?

**Comment by artur-trzesiok** [comment]
Hi @GiudiceVitor,

I know that new solution will not met with all yours needs but I'm feeling that we have good progress (left is previous view, right a new one [on devel branch]):

![image](https://github.com/K3D-tools/K3D-jupyter/assets/5256837/9a1da307-f243-4e06-8d4c-3e567e80e198)
![image](https://github.com/K3D-tools/K3D-jupyter/assets/5256837/e93961a5-fcec-4c1f-a1cc-54732aa76326)
![image](https://github.com/K3D-tools/K3D-jupyter/assets/5256837/425f38fd-69d6-4ac9-a877-fae9cdcae4b8)
![image](https://github.com/K3D-tools/K3D-jupyter/assets/5256837/8993f0ea-7896-4dba-a2ad-41e8de577124)

I changed extending grid to nearest minorThick. I also changed way of calculating position of labels on grid

**Comment by artur-trzesiok** [comment]
So I would like to change a scope of your issue to what is above. Please check a new version that I will release soon. If that will be still a issue for you please add another issue for tweaking it also

**Comment by artur-trzesiok** [comment]
Hi! Please check https://pypi.org/project/k3d/2.16.1/ :)

**Comment by GiudiceVitor** [comment]
Works fine by me! Thanks :)

**Comment by artur-trzesiok** [comment]
Thanks for your feedback!
