### ISSUE TITLE
Attempts to set camera position are ignored ?!

### ISSUE THREAD

**Issue by The9Cat** [K3D-tools/K3D-jupyter#432]
* K3D version: 2.16.0  (python and js version match)
* Python version: 3.10.12
* Operating System: Ubuntu 22.04

### Description

Using `plot.camera = [x, y, z, fx, fy, fz, xup, yup, zup]` does nothing for me.  I've tried before and after `plot.display()` to make sure I didn't misunderstand the API.

The relevant part of my code is something like:
```
plot1 = k3d.plot(axes=['z', 'y', 'x'])

color_map = k3d.basic_color_maps.Jet

levs = [20000.0, 30000.0, 100000.0, 200000.0, 400000.0, 600000.0, 1000000.0]
minlev = 0.0
maxlev = 1000000.0

for lev in levs:

    plot1 += k3d.marching_cubes(dens, level=lev, attribute=[lev], color_map=color_map,
                                      color_range=[minlev, maxlev],
                                      opacity=0.25,
                                      xmin=-vsize, xmax=vsize,
                                      ymin=-hsize, ymax=hsize,
                                      zmin=-hsize, zmax=hsize,
                                      compression_level=9,
                                      flat_shading=False)

plot1.camera = [0.05, 0.05, 0.05, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0] 
plot1.display()
```

I can set `plot1.camera` so some arbitrary vector and the resulting render is unchanged.

What am I missing here?

**Comment by ea42gh** [comment]
I have a similar issue in
[Quadric Surface Display Notebook](https://gitlab.com/ea42gh/elementary-linear-algebra/-/blob/master/notebooks/25a_QuadricSurfaceDisplay.ipynb)

calls to set the camera do nothing. Setting it via a holoviews panel interact function however works????!

**Comment by artur-trzesiok** [comment]
By default plot have camera_auto_fit set as True. So camera position is overwritten by display() with auto_fit

So either you can pass to k3d.plot(camera_auto_fit=False) or set position of camera in next cell after display

**Comment by The9Cat** [comment]
Good to know, thanks.  I discovered empirically that setting the camera position in the next cell does work.   Thanks for the tip about `camera_auto_fit=False`.
