### ISSUE TITLE
Flip Z axis for mesh plotting

### ISSUE THREAD

**Issue by thoth291** [K3D-tools/K3D-jupyter#433]
First of all - this is BRILLIANT project!
Thank you so much for making it to work.

I do scientific visualization all the time - and tools like this really enablers for pushing science forward!
Thank you!
 
* K3D version: 2.16
* Python version: 3.10.12
* Operating System: CentOS Linux release 7.7.1908
* vtk-osmesa

### Description

I'm plotting a custom mesh which is being generated by another engine.
Everything plots well, except that my Z axis is going in opposite direction to what I want.
It goes up - I need it to go down (visually) while my Z values go up.

What I get:
![image](https://github.com/K3D-tools/K3D-jupyter/assets/2971670/93bd83f3-75b4-4153-880a-ad551b9a174c)

What I want:
![image](https://github.com/K3D-tools/K3D-jupyter/assets/2971670/a836fc3b-6336-4d9c-a089-1e230e8f25d7)

### What I Did
Essentially this code - except that I had my own `data` with verts and inds.
```python
import k3d
import numpy as np

data = np.load('streamlines_data.npz')
plot = k3d.plot()
plot += k3d.mesh(data['vertices'], data['indices'],
                 opacity=0.25, wireframe=False, color=0x0002)
plot.display()
```

In other visualization tools I can simply set something like flip_z or z_flip - but can't figure out how to set it here.

Am I missing something obvious, or this is not possible to script in the code?

Would appreciate for your help!
Thanks in Advance!

**Comment by etienne87** [comment]
just revert the data['vertices'] Z axis in python: 
```
data['vertices'][:,z_axis] = max_z - data['vertices'][:,z_axis]
data['vertices'] = data['vertices'][::-1]   # needed otherwise k3d cancels effect of first line
```

**Comment by artur-trzesiok** [comment]
I agree with @etienne87 . I dive into topic in three.js but I found this: https://discourse.threejs.org/t/convert-from-one-coordinate-system-to-another/13240/42

Looks like there is no direct support in threejs to do that

**Comment by artur-trzesiok** [comment]
So at this moment I dont see any short way how to implement it to be consistent in all type of objects. As only threejs will add support for that we can re-open a issue
