### ISSUE TITLE
Any way to constrain the width of a plot?

### ISSUE THREAD

**Issue by ea42gh** [K3D-tools/K3D-jupyter#435]
Is there any way to constrain the width of a plot?
____
I used to be able to constrain the width of a k3d plot using holoviews panel.
Unfortunately, this no longer works.

I can set k3d plot.height, but there does not appear to be a width setting.

For reference, a plot I would like to constrain is in
[Quadric Surface Display Notebook](https://gitlab.com/ea42gh/elementary-linear-algebra/-/blob/master/notebooks/25a_QuadricSurfaceDisplay.ipynb)

**Comment by marcinofulus** [comment]
So in short e.g. : plot.layout.width='444px' will work

**Comment by artur-trzesiok** [comment]
> So in short e.g. : plot.layout.width='444px' will work

![image](https://github.com/K3D-tools/K3D-jupyter/assets/5256837/f01a981c-dc1f-41b3-acd6-af95b9df06e9)

**Comment by artur-trzesiok** [comment]
I bielieve that comment @marcinofulus solve a requested needs so I'm closing a issue. Thanks!
