### ISSUE TITLE
How to add label and ticklabel for colorbar in Points?

### ISSUE THREAD

**Issue by mushroomfire** [K3D-tools/K3D-jupyter#439]
* K3D version: 2.16.0
* Python version: 3.8.0
* Operating System: Win 10

### Description

I want to add a label for colorbar when ploting Points. Also sometimes want to modify the ticklabel. But I did not find the corresponding documents.

**Comment by artur-trzesiok** [comment]
Hi @mushroomfire 

At this moment colorbar is not customizable. It is rather simple tool. Adding a label can be manage by text2d. Based on examples/volume_renderer.ipynb:

```
embryo = k3d.volume(volume_data.astype(np.float16), 
                    color_map=np.array(k3d.basic_color_maps.BlackBodyRadiation, dtype=np.float32), 
                    bounds=bounds)

plot = k3d.plot()
plot += embryo
plot += k3d.text2d("Color legend:", position=(0.02, 0.45), is_html=True, label_box=False, color=0)
plot.display()
```

Will results with:
![image](https://github.com/K3D-tools/K3D-jupyter/assets/5256837/35fa46ce-5a27-44d1-83ed-ce92d931ce01)

If that is not sufficient please share more what you need

Artur

**Comment by mushroomfire** [comment]
That is enough. Thanks for your kind help! @artur-trzesiok
