### ISSUE TITLE
Use traitlets/widgets more?

### ISSUE THREAD

**Issue by vidartf** [K3D-tools/K3D-jupyter#44]
Is there a particular reason why you define a separate `_Attribute` class instead of using the `traitlets` package? They seem to solve mostly the same problem. In addition to being a mature python package, the latter offer the benefit of better integration with existing Jupyter environment.

Also, would it make sense to make `Drawable`/`SingleObject` classes inherit `ipywidgets.Widget`? This would allow direct use of ipywidgets' sync and serialization code (including binary buffers). Are there any performance concerns?

I could help out with any of these tasks if you find that it would make sense.

**Comment by artur-trzesiok** [comment]
No. This is a technical debt from more that one year. We have plan to migrate this.

**Comment by vidartf** [comment]
Alright, let me know if you want me to contribute anything 👍 If you have any specific needs/request for ipywidgets, now is the time to raise them, as it is currently in an alpha release fro 7.0 (so changes might still make it in).

**Comment by artur-trzesiok** [comment]
I'm focused on this task. Please be patient. That will flip upside down whole python part.

**Comment by artur-trzesiok** [comment]
@vidartf I had a problem with migration. Please help if you can.
My serialization code:
```
'use strict';

var _ = require('lodash');

// Inpspiration from https://github.com/maartenbreddels/ipyvolume/blob/master/js/src/serialize.js
// and https://github.com/jupyter-widgets/ipywidgets/blob/master/jupyter-widgets-base/test/src/dummy-manager.ts

// see https://github.com/jovyan/pythreejs/pull/80/files
// should go to a seperate package/module
var typesToArray = {
    int8: Int8Array,
    int16: Int16Array,
    int32: Int32Array,
    uint8: Uint8Array,
    uint16: Uint16Array,
    uint32: Uint32Array,
    float32: Float32Array,
    float64: Float64Array
}

function deserialize_typed_array(data) {
    var type = typesToArray[data.dtype];
    return new type(data.buffer.buffer);

}
function deserialize_array_or_json(data) {
    if (data == null) {
        return null;
    }

    if (_.isNumber(data)) { // plain number
        return data;
    } else { // should be an array of buffer+dtype+shape
        return deserialize_typed_array(data);
    }
}
function serialize_array_or_json(obj) {
    if (_.isNumber(obj)) {
        return obj;
    }

    if (obj !== null) {
        return {
            dtype: _.invert(typesToArray)[obj.constructor],
            buffer: obj
        };
    } else {
        return null;
    }
}

module.exports = {
    array_or_json: {deserialize: deserialize_array_or_json, serialize: serialize_array_or_json}
};
```
After use option "Save notebooks with widgets" and refresh a page my deserializer get in first argument "{"dtype":"float32","shape":[4,4]}". So I cannot retrieve a buffer.

**Comment by vidartf** [comment]
I'll be able to look closer at this on Tuesday, but until then: I think maybe the code in question here assumes the alpha version of IPyWidgets 7 (given the commit log for the linked code files in ipyvolume).

**Comment by artur-trzesiok** [comment]
@vidartf : Because of a lot of binary transfers we decided to move to ipywidgets 7.0.0.

**Comment by artur-trzesiok** [comment]
I rewrite whole k3d for use traitlets. I removed a legacy code with overuse of data parameter to do sync.

**Comment by vidartf** [comment]
I'll close this as solved. Any remaining points should be more specific issues/PRs.
