### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by spanag** [K3D-tools/K3D-jupyter#449]
### Description

I wanted to look at the doco but k3d-jupyter.org is not online since a couple days ago.

### What I Did
Check:  
http://k3d-jupyter.org  
https://isup.me/k3d-jupyter.org

**Comment by artur-trzesiok** [comment]
Thanks a lot @spanag 

Reson of that is quite simple - I forgot pay for DNS ;). It is already paid. We should expect dns propagation in next hours.

**Comment by spanag** [comment]
it seems to be up now.
