### ISSUE TITLE
Setup framework to autogenerate API documentation from docstrings

### ISSUE THREAD

**Issue by martinal** [K3D-tools/K3D-jupyter#45]
- [x] Wait for decision on project name change or not.
- [x] Setup a page using the new name on https://readthedocs.io
- [x] Follow https://docs.readthedocs.io/en/latest/getting_started.html to get a basic index page up.
- [x] Configure autogenerated api docs.
- [x] Agree on docstring format (make a single well written example).
- [ ] Then of course write docstrings for the entire user-level API.

**Comment by artur-trzesiok** [comment]
Finally!
https://k3d-jupyter.readthedocs.io/en/latest/examples/index.html

Quite old issue is fixed. Now we should focus on docs maintenance.
