### ISSUE TITLE
Issue with TransferFunctionModel Instantiation

### ISSUE THREAD

**Issue by SukiYume** [K3D-tools/K3D-jupyter#455]
* K3D version: 2.16.1
* Python version: 3.8.18
* Operating System: win10

### Description

I was trying to run the `transfer_function.ipynb` example from the k3d-jupyter package. When running the code, I encountered the following error:

```javascript
Model class 'TransferFunctionModel' from module 'k3d' is loaded but can not be instantiated
TypeError: r._deserialize_state is not a function
    at f._make_model
```

It seems there might be an issue with the dependency on ipywidgets. Based on the information from this [ipywidgets issue](https://github.com/jupyter-widgets/ipywidgets/issues/3607), it appears that the dependency needs to be updated.

Could you please let me know if there are plans to resolve this issue? Thank you!

**Comment by artur-trzesiok** [comment]
Hi @SukiYume I'm not able to reproduce that issue. Please tell me what ipywidgets and jupyter notebook are you using

**Comment by SukiYume** [comment]
Hi @artur-trzesiok 

Thank you for your response. I am able to consistently reproduce the issue by following these steps:

Create a new Python 3.8 environment using conda, and only install the necessary packages using conda: notebook, numpy, and k3d.

```bash
conda create -n testenv python=3.8
conda install -c conda-forge numpy notebook k3d
```

Here are the specific package versions in this environment:

`k3d=2.16.1`
`notebook=7.2.1`
`ipywidgets=8.1.3`
`jupyterlab=4.2.3`

Despite these steps, I still encounter this error. I have attached a screenshot of the error for your reference.

![test](https://github.com/K3D-tools/K3D-jupyter/assets/38221742/49619936-a093-4cde-a92d-8c87a338be94)

**Comment by artur-trzesiok** [comment]
@SukiYume I have it! It is related to notebook 7.x - trying to fix it

**Comment by SukiYume** [comment]
Thank you for resolving the issue promptly!
