### ISSUE TITLE
Passing scalars + color map instead of colors

### ISSUE THREAD

**Issue by martinal** [K3D-tools/K3D-jupyter#48]
I'd rather be passing my scalar values and then adjust the color map of the plot than computing my own colors. At least points and lines take a direct colors argument. I.e. I'd like to write lines like
```
plot += K3D.points([0,0,0, 1,1,1], values=[-2.3, 5.7])
plot += K3D.points([0,0,0, 1,1,1], values=[-2.3, 5.7], colormap=...)
plot += K3D.points([0,0,0, 1,1,1], values=[-2.3, 5.7], colormap=..., valuerange=[-3, 6])
```
Are there plans to improve the color mapping features? What's the intended usage?
I don't quite understand what the intention is with the K3D.matplotlib_color_maps.

Also I suggest changing default colors in the api from `color=255` to at least `color=0x0000ff` to make it more visible what the expected format is, or better allow `color='blue'` and do a lookup in a suitable color collection if it's a string.

I guess it would be best to use existing color mapping features from something mature like matplotlib.

**Comment by artur-trzesiok** [comment]
Colorsmap is a fresh feature in k3d. I created it to color vtk polydata. For sure right now for consistency it should ready to use in every color mapping. 

Please look at this example https://github.com/K3D-tools/K3D-jupyter/blob/devel/examples/mesh.ipynb

**Comment by martinal** [comment]
Exactly what I wanted :)

How do you want to go about changing the other object types to use this?

**Comment by tgandor** [comment]
I have written a helper function: k3d.helpers.map_colors to perform the computation and supply `colors` based on an attribute array, color map, and optional range (which can be inferred as [min(attribute), max(attribute)], but careful - if attribute is uniform, this means everything is equal to min.

Please see, if this is what you like.
