### ISSUE TITLE
Button to close widget

### ISSUE THREAD

**Issue by martinal** [K3D-tools/K3D-jupyter#49]
It would be nice with an X button in the corner to "close" the widget if that's possible.

**Comment by martinal** [comment]
`plot.close()` does the trick, but a button would still be nice.

**Comment by martinal** [comment]
Actually, `plot.close()` is not possible if the `plot` variable has been overwritten in the kernel, which can easily happen when experimenting in a notebook (which is what I'm doing now).

**Comment by marcinofulus** [comment]
in new widgets one have to do "cell output - clear"
