### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 78: ordinal not in range(128)

### ISSUE THREAD

**Issue by korniichuk** [K3D-tools/K3D-jupyter#5]
Please fix one line from``K3D-jupyter/bower.json`` file:
From::

    "Artur Trzęsiok <artur.trzesiok@gmail.com>"
to::

    "Artur Trzesiok <artur.trzesiok@gmail.com>"

**Comment by skremiec** [comment]
Thanks for reporting. This issue is fixed in v0.8.0.
