### ISSUE TITLE
Default directed light is not suitable for objective scientific visualization

### ISSUE THREAD

**Issue by martinal** [K3D-tools/K3D-jupyter#51]
A directed light source that makes one side of an object shaded differently from the other side even if the color is the same all over makes objective inspection of colors vs color maps impossible. I have a constant blue colored cube surface mesh that looks almost black on one side and almost white on another. Ambient light would be preferrable, in particular since I see no way to adjust the light?

**Comment by artur-trzesiok** [comment]
At this moment we don't have that kind of control. We need to balance beetwen low-level webgl features and high-level scientific library. Rather than control of every light on scene i would prefer state like plot.lighShading = True/False. @marcinofulus what do you think?

**Comment by martinal** [comment]
I'm not suggesting anything low level here, just (an option to) using `THREE.AmbientLight` alone and not using `THREE.PointLight`.

Also, we're exploring ways to make it easy to add things to pythreejs scenes by external libraries like k3d-jupyter. That would make it possible to use the full set of pythreejs light objects etc and add a k3d plot to the pythreejs scene.

**Comment by martinal** [comment]
The point being that these lights have arbitrarily chosen positions:
```
        lights[0] = new THREE.PointLight(0xffffff, 1, 0);
        lights[1] = new THREE.PointLight(0xffffff, 1, 0);
        lights[2] = new THREE.PointLight(0xffffff, 1, 0);
        lights[3] = new THREE.PointLight(0xffffff, 1, 0);

        lights[0].position.set(-100, -1000, -500);
        lights[1].position.set(-3000, 1000, -500);

        lights[2].position.set(-5000, 1000, 1000);
        lights[3].position.set(5000, -1000, 1000);
```
you have no reason to believe these coordinates make sense for the model that the user is plotting.

**Comment by artur-trzesiok** [comment]
I will attach lights to camera.
