### ISSUE TITLE
Individual size of Vectors in VectorField

### ISSUE THREAD

**Issue by vidartf** [K3D-tools/K3D-jupyter#53]
A typical feature for vector field plots is to have the vectors scale as a function of some vector field value (e.g. flow rate). Here, both the arrow length and the arrow head would typically scale together (see e.g. matlab's quiver plot: https://mathworks.com/help/matlab/ref/quiver.html).

**Comment by artur-trzesiok** [comment]
Our vectors had length proportional to value.
![k3d-1496939399280](https://user-images.githubusercontent.com/5256837/26939736-8a8253ec-4c78-11e7-857b-c70c75392edc.png)

**Comment by artur-trzesiok** [comment]
You want to have a property to scale them with by default value 1.0?

**Comment by artur-trzesiok** [comment]
Example: https://github.com/K3D-tools/K3D-jupyter/blob/devel/examples/vector2d.ipynb

**Comment by vidartf** [comment]
@artur-trzesiok : I think the current feature is OK. I simply did not understand the interface. This should be OK as soon as there is documentation.

**Comment by artur-trzesiok** [comment]
Thanks. Still that was a inspiration to add "scale" parameter
