### ISSUE TITLE
Grid size doesn't work as expected

### ISSUE THREAD

**Issue by martinal** [K3D-tools/K3D-jupyter#54]
Displaying a simple
```
K3D(grid=[0,0,0,1,1,1], grid_auto_fit=False)
```
doesn't show as expected. Originally I thought it was the autofit that tried to include some space around my model (too much space for my taste), but even without any data and without autofit the grid size is not respected.

![grid-auto-fit](https://cloud.githubusercontent.com/assets/378115/26669727/32a5b052-46af-11e7-942a-29893943bbec.png)

**Comment by artur-trzesiok** [comment]
We force to always have at least 3 number on axis to give information about corrner values. Without that we will have issues with overlapping numbers on corners.  From my perspective the more in this case is better that opossite. I suggest to leaft it as is for a while and focus on more important topics. Maybe in future we will implement automated positioning of corners value.

**Comment by marcinofulus** [comment]
I vote yes  for the last "maybe"

**Comment by martinal** [comment]
I think I failed to communicate my issue here. I was not thinking about the placement of numbers on axis.

When passing `grid=[0,0,0,1,1,1]` I was expecting the grid to cover exactly the interval [0,1] for x,y,z, but the grid instead covers the interval [-2,+2] for each of x,y,z.

Either I'm passing the `grid=` parameter incorrectly and there's no error message from k3d or its values are ignored when setting up the grid.
