### ISSUE TITLE
Inconsistent gaps between points

### ISSUE THREAD

**Issue by martinal** [K3D-tools/K3D-jupyter#56]
Placing three points .5 apart and using point_size .25 still leaves large gaps between them. It would be nice if the unit was intuitive.

But worse than that it seems the positioning is inaccurate:
```
from k3d import K3D
plot = K3D(grid=[0,0,0, 1,1,1], grid_auto_fit=False)
plot += K3D.points([0,0,0, 0,0,.5, 0,0,1], point_size=.9)
plot
```
These points are evenly spaced, but as you see on the screenshot there's a gap between two of them while the other two overlaps slightly:

![k3d-1496305131085](https://cloud.githubusercontent.com/assets/378115/26670923/e870f3c0-46b3-11e7-878a-f2a700d015e9.png)

You might want to rotate the camera a bit to convince yourself this is not a visual artifact of the camera angle.

**Comment by martinal** [comment]
By intuitive unit I mean radius or diameter in same coordinate scale as the grid, given default identity model matrix.

**Comment by tgandor** [comment]
I've looked into it, and for me it seems like normal behavior of a perspective projection.
When looking from an angle - for example at a row of street lights - the further ones seem closer to each other.
Also, it looks strange with specular shading like above - please look at it with:
points.shader = 'flat'
- it won't be as noticable.

Finally, this effect I observed is symmetrical - when you look from the opposite side, the other two "balls" seem to overlap and the previously "too close" points are farther.

I will assign this issue to Artur to check if my intuition is correct and maybe close issue.

**Comment by artur-trzesiok** [comment]
Issue is related to https://github.com/mrdoob/three.js/issues/10385#issuecomment-267789138

**Comment by artur-trzesiok** [comment]
Another topic: sphere projection is not only a circle. We use the trick to render points to have fast method to visualize something like 1mln points. This is a fake geometry. Proper implementation was done by IQ: http://iquilezles.org/www/articles/sphereproj/sphereproj.htm . @marcinofulus : should we try to implement it in k3d?

**Comment by marcinofulus** [comment]
Perhaps  shader='mesh'? I would propose to make a k3d.sphere and possibly redirect if shared = mesh is used.

**Comment by martinal** [comment]
With the latest devel branch, running the example code from the top here updated to use the k3d namespace:
```
import k3d
plot = k3d.plot(grid=[0,0,0, 1,1,1], grid_auto_fit=False)
plot += k3d.points([0,0,0, 0,0,.5, 0,0,1], point_size=.9)
plot
```
now only gives me a webgl error in the browser console: 
```
K3D: Object type "Points" loaded in:  0.001 s
45k3d-issue-56.ipynb:1 [.Offscreen-For-WebGL-0xa8c60c75e00]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: attempt to access out of range vertices in attribute 1
```

**Comment by artur-trzesiok** [comment]
I'm working on " shader='mesh'" solution to based on instancedGeometry to assume high-speed rendering.
