### ISSUE TITLE
Getting back screenshot as an image in python

### ISSUE THREAD

**Issue by martinal** [K3D-tools/K3D-jupyter#58]
It would be nice to be able to get a screenshot programmatically, i.e. `image = plot.screenshot()` and `plot.screenshot(filaname)`.

Example:
```
# setup a plot
plot = K3D(...)
...
plot.display()
```
then retrieve a screenshot programmatically:
```
image = plot.screenshot()
plot.close()  # don't need this anymore
image  # display image (or save to file somehow)
```

**Comment by artur-trzesiok** [comment]
I had problem with saving binary data with Bytes traitlets. Needs more investigation. Right now i pushed version that take on server base64 version. Example: https://github.com/K3D-tools/K3D-jupyter/blob/devel/examples/points.ipynb

**Comment by martinal** [comment]
I can confirm this works, and doing
```
from IPython.display import Image
Image(plot.screenshot)
```
after fetching in the points example notebook correctly displays the image in the notebook.

Two improvements to this would be

- fetching screenshow with specific resolution (higher than the resolution of the display of the canvas)
- an easy way to download the image as a file and/or store to a filename.

**Comment by marcinofulus** [comment]
In screenshot example` Image(url='screenshot.png') ` seems to show always browser cached image.
However 

`Image(data=b64decode(plot.screenshot) ) ` works fine.

**Comment by artur-trzesiok** [comment]
Hi,

We hand right now a dedicated example for screenshots : https://github.com/K3D-tools/K3D-jupyter/blob/master/examples/screenshot.ipynb 

Please notice that we had a control on resolution of screenshot with:

`plot.screenshot_scale = 5.0`

**Comment by basilevh** [comment]
This doesn't work for me as it returns an empty variable.
