### ISSUE TITLE
Grid text overlays surface mesh

### ISSUE THREAD

**Issue by martinal** [K3D-tools/K3D-jupyter#61]
Image is pretty obvious. Let me know if you need an example to reproduce it, my current one requires external dependencies.

![k3d-text-over-mesh](https://user-images.githubusercontent.com/378115/27334708-70e7ead6-55ca-11e7-8246-15aa40c8a0c3.png)

**Comment by artur-trzesiok** [comment]
I'm aware about this issue. Text2d objects are located on overlay DOM layer. This is a trade-off - nice rendered text in 2d world or ugly one in 3d. To solve this problem We will need to calculate analitical intersection with ray with all objects on scene (sometimes ~2mln triangles). That will be costly. @marcinofulus what do you think?

**Comment by vidartf** [comment]
It should be possible is three.js to place Sprite's in 3D layer. You can then apply a SpriteMaterial with a CanvasTexture to the sprite. Then you can render nice numbers with canvas, and still have them placed in 3D.

**Comment by vidartf** [comment]
My current code for generating such canvas textures, goes something like this:
```js

function createTextTexture(string, size, fontFace, squareTexture) {
  var canvas = document.createElement('canvas');
  var context = canvas.getContext('2d');

  // Pad size with two to avoid edge artifacts when interpolating
  canvas.height = size + 2;
  var font = 'Normal ' + size + 'px ' + fontFace;
  context.font = font;
  var metrics = context.measureText(string);
  var textWidth = Math.ceil(metrics.width) + 2;
  canvas.width = textWidth;
  if (squareTexture) {
    canvas.height = canvas.width = Math.max(canvas.width, canvas.height);
  }

  context.textAlign = 'center';
  context.textBaseline = 'middle';
  context.fillStyle = color;
  // Must set the font again for the fillText call
  context.font = font;
  context.fillText(string, canvas.width / 2, canvas.height / 2);
  return THREE.CanvasTexture(canvas, ...)
}
```

**Comment by artur-trzesiok** [comment]
We had that feature in k3d also. It's called k3d.texture_text. Please look at this example https://github.com/K3D-tools/K3D-jupyter/blob/master/examples/texture_text.ipynb

**Comment by vidartf** [comment]
@artur-trzesiok So does k3d now use such sprites for grid text?
