### ISSUE TITLE
Problem while drawing single point 

### ISSUE THREAD

**Issue by Kotrix** [K3D-tools/K3D-jupyter#66]
A single k3d.points() object is not drawn properly if only one position is given instead of a list of positions. That caused sierpinski3d sample fail

**Comment by tgandor** [comment]
Confirmed. I see this may have something to do with the improvements in grid calculations:
https://github.com/K3D-tools/K3D-jupyter/commit/b8dbbabf76be4da0fe22278ded13a8f41ea42767

I don't yet know what they were about, but I will look into it.

**Comment by tgandor** [comment]
It is now possible to draw a single point without collapsing the plot.
