### ISSUE TITLE
vectors origins

### ISSUE THREAD

**Issue by marcinofulus** [K3D-tools/K3D-jupyter#71]
k3d.vectors(vectors,origins) is not intuitive,

I would suggest to change it to
k3d.vectors(vectors) - origins are assumed to be 0,0,0
k3d.vectors(origins,vectors) - origins are the first argument

**Comment by tgandor** [comment]
Sorry for the delay. The previous ordering (origins, vectors) is now brought back.

I was thinking about the ([origins,] vectors) form, and didn't find a nice way of doing it, short of turning everything into keyword arguments. (there are no mandatory positional arguments after one with a default value).

Well, the arguments are called `origins` and `vectors` like before, but giving just `origins` is an idiom for unbound (or zero-bound actually) vectors.

We'll be pulling this into `master` shortly.
