### ISSUE TITLE
[ Request ] Please expose alpha (transparency) parameter

### ISSUE THREAD

**Issue by miroenev** [K3D-tools/K3D-jupyter#73]
Would appreciate the ability to set the alpha value of K3D objects (e.g., points, vectors, surfaces).

May require a change of the three.js object's material properties:
- https://stackoverflow.com/questions/8502150/three-js-how-can-i-dynamically-change-objects-opacity

**Comment by tgandor** [comment]
I'm not quite sure, how this would play together with our custom shaders (e.g. for `k3d.points()`), and we also have plans for volumetric renderning. I'll talk to the maintainers how to go about this issue.

**Comment by artur-trzesiok** [comment]
We study opacity case. It's not a simple problem related to https://en.wikipedia.org/wiki/Order-independent_transparency . ThreeJs dosen't have a good support for this.

Meanwhile we add wifreframe support for meshes (https://github.com/K3D-tools/K3D-jupyter/blob/master/examples/voxels.ipynb) - that can help with inspecting "interior" of objects.
