### ISSUE TITLE
running examples on binder gives error

### ISSUE THREAD

**Issue by oroszl** [K3D-tools/K3D-jupyter#74]
Running `k3d-jupyter` on binder results in all the examples dieing with error
```python
AttributeError: module 'k3d' has no attribute 'plot'
```

**Comment by oroszl** [comment]
It seems that the version that is pulled from pip are somewhat old and the examples provided in the repo will not work with them. A solution would be to modify the Dockerfile to pull the package from github.

**Comment by tgandor** [comment]
We hope to release the current version to PyPI soon enough.
This issue will be updated when it happens.

**Comment by marcinofulus** [comment]
We

**Comment by intijk** [comment]
Hi @oroszl 
I found the pip installed k3d still don't have plot() function. My information is like below
```
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import k3d
>>> k3d.__version__
'2.0.12'
>>> k3d.
k3d.Bool(         k3d.Int(          k3d.factory       k3d.queue
k3d.Bytes(        k3d.K3D(          k3d.json          k3d.version_info
k3d.Dict(         k3d.Queue(        k3d.k3d           k3d.widgets
k3d.Drawable(     k3d.Unicode(      k3d.objects       k3d.zlib
k3d.Factory(      k3d.base64        k3d.partial( ```

Could you tell me which version of k3d should be used?

**Comment by oroszl** [comment]
I meant cloning from github, something along these lines:
```bash
pip install git+https://github.com/K3D-tools/K3D-jupyter
```
