### ISSUE TITLE
jupyter notebook fails to display plots

### ISSUE THREAD

**Issue by JustinLiu97** [K3D-tools/K3D-jupyter#75]
I got K3D tools installed correctly, and while running the example '01_getting_started', the command 'plot.display()' fails to display the plot and just leaves a very short blank area under the cell. Is there a way to fix it? Thanks a lot!

**Comment by tgandor** [comment]
Can you open the example with development tools (e.g. F12 in Chrome, or Ctrl+Shift+C in FF) enabled? Especially the console? Are there specific error messages?

Does it contain the message:
Loading extension: k3d/extension utils.js:37
before:
Kernel: kernel started
?

**Comment by JustinLiu97** [comment]
Sorry about replying late. I can open the console, and the messages in it looks like that:
![screenshot from 2018-03-30 15-12-24](https://user-images.githubusercontent.com/37870007/38128362-d8d7c1b6-342c-11e8-8c7f-2c7edf86e841.png)
And I can find the message:Loading extension: k3d/extension, but can't find the message 'utils.js:37' following it.

**Comment by tgandor** [comment]
OK, I've more or less reproduced the result. The k3d notebook extension is not working in the above screenshot.

Please use this wheel (before we publish the current development branch to PyPI):
https://drive.google.com/drive/folders/1jMWowyVyHRNiPUjC9diHVj1369KySLhh?usp=sharing

Then, after all the dependencies install successfully, run:
`$ jupyter nbextension install --py --sys-prefix k3d`
`$ jupyter nbextension enable --py --sys-prefix k3d`

And only then start jupyter notebook and start working with K3D.
I have tested the above wheel on a conda env with Python 2.7 successfully.

**Comment by lifematrix** [comment]
I install K3D using the above whl package(in python 3.5). But get the similar problem:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-77248ba909f1> in <module>()
      1 import k3d
----> 2 plot = k3d.plot()
      3 
      4 # here you would normally create objects to display
      5 # and add them to the plot

AttributeError: module 'k3d' has no attribute 'plot'
```
The console that jupyter started in printed some error message. It seems some files whose name is in devel environment is not found. 
![screenshot from 2018-04-24 17-33-19](https://user-images.githubusercontent.com/7351519/39179082-f7d259ec-47e5-11e8-8c05-8b488f5bb9ac.png)

Thanks!

Steven

**Comment by intijk** [comment]
I think the project is kind of dead, there is no update since last May to pypi, so all version installed by pip is the old version without `.plot()` function

https://pypi.org/project/K3D/#history

Source code last update is 7 months ago. Kind of pity such a good project dead.

**Comment by artur-trzesiok** [comment]
Today I published new version on pyPi. Sorry for delay with that. We start a new bulk of sprints on K3D right now.

**Comment by artur-trzesiok** [comment]
Please use version 2.4.0 - https://pypi.org/manage/project/k3d/releases/
