### ISSUE TITLE
K3D cannot be embedded inside Box widgets

### ISSUE THREAD

**Issue by bollwyvl** [K3D-tools/K3D-jupyter#9]
For building GUIs that show interactive manipulation of geometry, it would be nice if the K3D widget could be put inside the Box widgets (VBox, HBox and the various tabs and accordions).

Right now, it looks like this:
![capture](https://cloud.githubusercontent.com/assets/45380/11641223/11afa43e-9d05-11e5-8b22-7806637f707d.PNG)

Haven't had a chance to dig into it, but figured I'd open it as a ticket after working on #8.

**Comment by panangam** [comment]
Has there been anymore development on this? Is there a way to arrange the plotters into a grid?

**Comment by onavhamid** [comment]
Any progress on this? Arranging k3d plots into box models is failing using k3d v 2.14.5 and ipywidgets v7.7.1.
