### ISSUE TITLE
vector_field

### ISSUE THREAD

**Issue by marcinofulus** [K3D-tools/K3D-jupyter#92]
arrows are all whilte

**Comment by spikeliu** [comment]
![image](https://user-images.githubusercontent.com/5734885/232442998-c5fdfbfd-5ad7-4431-a179-eef365bbac3a.png)
This is a snapshot from the official document site. All vectors should have the color as specified by parameter `color`, but it seems all origins are black and all heads are white. Also, it doesn't work when specifying `origin_color` and `head_color`.
